TTMath: ttmath::Big< exp, man > Class Template Reference
ttmath::Big< exp, man > Class Template Reference
Big implements the floating point numbers.
#include <ttmathbig.h>
Public Member Functions
uint CheckCarry (uint c)
uint Standardizing ()
void ClearInfoBit (unsigned char bit)
void SetInfoBit (unsigned char bit)
bool IsInfoBit (unsigned char bit) const
void SetZero ()
void SetOne ()
void Set05 ()
void SetNan ()
void SetZeroNan ()
void Swap (Big< exp, man > &ss2)
void SetPi ()
void Set05Pi ()
void Set2Pi ()
void SetE ()
void SetLn2 ()
void SetLn10 ()
void SetMax ()
void SetMin ()
bool IsZero () const
bool IsSign () const
bool IsNan () const
void Abs ()
void Sgn ()
void SetSign ()
void ChangeSign ()
uint Add (Big< exp, man > ss2, bool round=true, bool adding=true)
uint Sub (const Big< exp, man > &ss2, bool round=true)
uint BitAnd (Big< exp, man > ss2)
uint BitOr (Big< exp, man > ss2)
uint BitXor (Big< exp, man > ss2)
uint MulUInt (uint ss2)
uint MulInt (sint ss2)
uint Mul (const Big< exp, man > &ss2, bool round=true)
uint Div (const Big< exp, man > &ss2, bool round=true)
uint Mod (const Big< exp, man > &ss2)
uint Mod2 () const
template<uint pow_size>
uint Pow (UInt< pow_size > pow)
template<uint pow_size>
uint Pow (Int< pow_size > pow)
uint PowUInt (Big< exp, man > pow)
uint PowInt (const Big< exp, man > &pow)
uint PowFrac (const Big< exp, man > &pow)
uint Pow (const Big< exp, man > &pow)
uint Sqrt ()
uint Exp (const Big< exp, man > &x)
uint Ln (const Big< exp, man > &x)
uint Log (const Big< exp, man > &x, const Big< exp, man > &base)
template<uint another_exp, uint another_man>
uint FromBig (const Big< another_exp, another_man > &another)
uint ToUInt () const
uint ToUInt (uint &result) const
sint ToInt () const
uint ToInt (uint &result) const
uint ToInt (sint &result) const
template<uint int_size>
uint ToUInt (UInt< int_size > &result) const
template<uint int_size>
uint ToInt (UInt< int_size > &result) const
template<uint int_size>
uint ToInt (Int< int_size > &result) const
uint FromUInt (uint value)
uint FromInt (uint value)
uint FromInt (sint value)
uint FromDouble (double value)
uint FromFloat (float value)
double ToDouble () const
float ToFloat () const
uint ToFloat (float &result) const
uint ToDouble (double &result) const
Big< exp, man > & operator= (sint value)
Big< exp, man > & operator= (uint value)
Big< exp, man > & operator= (float value)
Big< exp, man > & operator= (double value)
Big (sint value)
Big (uint value)
Big (double value)
Big (float value)
uint ToUInt (unsigned int &result) const
uint ToInt (unsigned int &result) const
uint ToInt (signed int &result) const
uint FromUInt (unsigned int value)
uint FromInt (unsigned int value)
uint FromInt (signed int value)
Big< exp, man > & operator= (unsigned int value)
Big (unsigned int value)
Big< exp, man > & operator= (signed int value)
Big (signed int value)
template<uint int_size>
uint FromUInt (UInt< int_size > value)
template<uint int_size>
uint FromInt (const UInt< int_size > &value)
template<uint int_size>
uint FromInt (Int< int_size > value)
template<uint int_size>
Big< exp, man > & operator= (const Int< int_size > &value)
template<uint int_size>
Big (const Int< int_size > &value)
template<uint int_size>
Big< exp, man > & operator= (const UInt< int_size > &value)
template<uint int_size>
Big (const UInt< int_size > &value)
template<uint another_exp, uint another_man>
Big< exp, man > & operator= (const Big< another_exp, another_man > &value)
template<uint another_exp, uint another_man>
Big (const Big< another_exp, another_man > &value)
Big ()
~Big ()
Big< exp, man > & operator= (const Big< exp, man > &value)
Big (const Big< exp, man > &value)
uint ToString (std::string &result, uint base=10, bool scient=false, sint scient_from=15, sint round=-1, bool trim_zeroes=true, char comma='.') const
uint ToString (std::string &result, const Conv &conv) const
std::string ToString (const Conv &conv) const
std::string ToString (uint base=10) const
uint ToString (std::wstring &result, uint base=10, bool scient=false, sint scient_from=15, sint round=-1, bool trim_zeroes=true, wchar_t comma='.') const
uint ToString (std::wstring &result, const Conv &conv) const
std::wstring ToWString (const Conv &conv) const
std::wstring ToWString (uint base=10) const
uint FromString (const char *source, uint base=10, const char **after_source=0, bool *value_read=0)
uint FromString (const char *source, const Conv &conv, const char **after_source=0, bool *value_read=0)
uint FromString (const std::string &string, uint base=10, const char **after_source=0, bool *value_read=0)
uint FromString (const std::string &string, const Conv &conv, const char **after_source=0, bool *value_read=0)
uint FromString (const wchar_t *source, uint base=10, const wchar_t **after_source=0, bool *value_read=0)
uint FromString (const wchar_t *source, const Conv &conv, const wchar_t **after_source=0, bool *value_read=0)
uint FromString (const std::wstring &string, uint base=10, const wchar_t **after_source=0, bool *value_read=0)
uint FromString (const std::wstring &string, const Conv &conv, const wchar_t **after_source=0, bool *value_read=0)
Big (const char *string)
Big (const std::string &string)
Big< exp, man > & operator= (const char *string)
Big< exp, man > & operator= (const std::string &string)
Big (const wchar_t *string)
Big (const std::wstring &string)
Big< exp, man > & operator= (const wchar_t *string)
Big< exp, man > & operator= (const std::wstring &string)
bool SmallerWithoutSignThan (const Big< exp, man > &ss2) const
bool GreaterWithoutSignThan (const Big< exp, man > &ss2) const
bool EqualWithoutSign (const Big< exp, man > &ss2) const
bool operator< (const Big< exp, man > &ss2) const
bool operator== (const Big< exp, man > &ss2) const
bool operator> (const Big< exp, man > &ss2) const
bool operator>= (const Big< exp, man > &ss2) const
bool operator<= (const Big< exp, man > &ss2) const
bool operator!= (const Big< exp, man > &ss2) const
Big< exp, man > operator- () const
Big< exp, man > operator- (const Big< exp, man > &ss2) const
Big< exp, man > & operator-= (const Big< exp, man > &ss2)
Big< exp, man > operator+ (const Big< exp, man > &ss2) const
Big< exp, man > & operator+= (const Big< exp, man > &ss2)
Big< exp, man > operator * (const Big< exp, man > &ss2) const
Big< exp, man > & operator *= (const Big< exp, man > &ss2)
Big< exp, man > operator/ (const Big< exp, man > &ss2) const
Big< exp, man > & operator/= (const Big< exp, man > &ss2)
Big< exp, man > & operator++ ()
Big< exp, man > operator++ (int)
Big< exp, man > & operator-- ()
Big< exp, man > operator-- (int)
Big< exp, man > operator & (const Big< exp, man > &p2) const
Big< exp, man > & operator&= (const Big< exp, man > &p2)
Big< exp, man > operator| (const Big< exp, man > &p2) const
Big< exp, man > & operator|= (const Big< exp, man > &p2)
Big< exp, man > operator^ (const Big< exp, man > &p2) const
Big< exp, man > & operator^= (const Big< exp, man > &p2)
void SkipFraction ()
void RemainFraction ()
bool IsInteger () const
uint Round ()
Static Public Member Functions
static const char * LibTypeStr ()
static LibTypeCode LibType ()
Data Fields
Int< exp > exponent
UInt< man > mantissa
unsigned char info
Friends
class Big< exp-1, man >
std::ostream & operator<< (std::ostream &s, const Big< exp, man > &l)
std::wostream & operator<< (std::wostream &s, const Big< exp, man > &l)
std::istream & operator>> (std::istream &s, Big< exp, man > &l)
std::wistream & operator>> (std::wistream &s, Big< exp, man > &l)
Detailed Description
template<uint exp, uint man>
class ttmath::Big< exp, man >
Big implements the floating point numbers.
Definition at line 63 of file ttmathbig.h.
Constructor & Destructor Documentation
Big() [1/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (sint value)
a constructor for converting 'sint' to this class
Definition at line 3163 of file ttmathbig.h.
     {
         FromInt(value);
     }
References ttmath::Big< exp, man >::FromInt().
Big() [2/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (uint value)
a constructor for converting 'uint' to this class
Definition at line 3171 of file ttmathbig.h.
     {
         FromUInt(value);
     }
References ttmath::Big< exp, man >::FromUInt().
Big() [3/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (double value)
a constructor for converting 'double' to this class
Definition at line 3180 of file ttmathbig.h.
     {
         FromDouble(value);
     }
References ttmath::Big< exp, man >::FromDouble().
Big() [4/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (float value)
a constructor for converting 'float' to this class
Definition at line 3189 of file ttmathbig.h.
     {
         FromFloat(value);
     }
References ttmath::Big< exp, man >::FromFloat().
Big() [5/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (unsigned int value)
a constructor for converting 32 bit unsigned int to this class this constructor is created only on a 64bit platform***
Definition at line 3470 of file ttmathbig.h.
     {
         FromUInt(value);
     }
References ttmath::Big< exp, man >::FromUInt().
Big() [6/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (signed int value)
a constructor for converting 32 bit signed int to this class this constructor is created only on a 64bit platform***
Definition at line 3492 of file ttmathbig.h.
     {
         FromInt(value);
     }
References ttmath::Big< exp, man >::FromInt().
Big() [7/15]
template<uint exp, uint man> template<uint int_size> ttmath::Big< exp, man >::Big (const Int< int_size > & value)
a constructor for converting from 'Int<int_size>' to this class
Definition at line 3598 of file ttmathbig.h.
     {
         FromInt(value);
     }
References ttmath::Big< exp, man >::FromInt().
Big() [8/15]
template<uint exp, uint man> template<uint int_size> ttmath::Big< exp, man >::Big (const UInt< int_size > & value)
a constructor for converting from 'UInt<int_size>' to this class
Definition at line 3620 of file ttmathbig.h.
     {
         FromUInt(value);
     }
References ttmath::Big< exp, man >::FromUInt().
Big() [9/15]
template<uint exp, uint man> template<uint another_exp, uint another_man> ttmath::Big< exp, man >::Big (const Big< another_exp, another_man > & value)
a constructor for converting from 'Big<another_exp, another_man>' to this class
Definition at line 3642 of file ttmathbig.h.
     {
         FromBig(value);
     }
References ttmath::Big< exp, man >::FromBig().
Big() [10/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big ()
a default constructor
by default we don't set any of the members to zero only NaN flag is set
if you want the mantissa and exponent to be set to zero define TTMATH_BIG_DEFAULT_CLEAR macro (useful for debug purposes)
Definition at line 3658 of file ttmathbig.h.
     {
         #ifdef TTMATH_BIG_DEFAULT_CLEAR
             SetZeroNan();
         #else
             info = TTMATH_BIG_NAN;
             // we're directly setting 'info' (instead of calling SetNan())
             // in order to get rid of a warning saying that 'info' is uninitialized
         #endif
     }
References ttmath::Big< exp, man >::SetZeroNan(), and TTMATH_BIG_NAN.
~Big()
template<uint exp, uint man> ttmath::Big< exp, man >::~Big ()
a destructor
Definition at line 3677 of file ttmathbig.h.
     {
     }
Big() [11/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (const Big< exp, man > & value)
a constructor for copying from another object of this class
Definition at line 3699 of file ttmathbig.h.
     {
         operator=(value);
     }
References ttmath::Big< exp, man >::operator=().
Big() [12/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (const char * string)
a constructor for converting a string into this class
Definition at line 5321 of file ttmathbig.h.
     {
         FromString( string );
     }
References ttmath::Big< exp, man >::FromString().
Big() [13/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (const std::string & string)
a constructor for converting a string into this class
Definition at line 5330 of file ttmathbig.h.
     {
         FromString( string.c_str() );
     }
References ttmath::Big< exp, man >::FromString().
Big() [14/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (const wchar_t * string)
a constructor for converting a string into this class
Definition at line 5364 of file ttmathbig.h.
     {
         FromString( string );
     }
References ttmath::Big< exp, man >::FromString().
Big() [15/15]
template<uint exp, uint man> ttmath::Big< exp, man >::Big (const std::wstring & string)
a constructor for converting a string into this class
Definition at line 5373 of file ttmathbig.h.
     {
         FromString( string.c_str() );
     }
References ttmath::Big< exp, man >::FromString().
Member Function Documentation
Abs()
template<uint exp, uint man> void ttmath::Big< exp, man >::Abs ()
this method clears the sign (there'll be an absolute value)
samples
-1 -> 1
2 -> 2
Definition at line 682 of file ttmathbig.h.
     {
         ClearInfoBit(TTMATH_BIG_SIGN);
     }
References ttmath::Big< exp, man >::ClearInfoBit(), and TTMATH_BIG_SIGN.
Referenced by ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::MulInt(), and ttmath::Big< exp, man >::PowUInt().
Add()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Add (Big< exp, man > ss2, bool round = true, bool adding = true)
Addition this = this + ss2
it returns carry if the sum is too big
Definition at line 930 of file ttmathbig.h.
     {
     bool last_bit_set, rest_zero, do_adding, do_rounding, rounding_up;
     uint c = 0;
         if( IsNan() || ss2.IsNan() )
             return CheckCarry(1);
         if( !adding )
             ss2.ChangeSign(); // subtracting
         // (1) abs(this) will be >= abs(ss2)
         if( SmallerWithoutSignThan(ss2) )
             Swap(ss2);
         if( ss2.IsZero() )
             return 0;
         Int<exp> exp_offset( exponent );
         exp_offset.Sub( ss2.exponent );
         if( !exp_offset.Abs() )
         {
             // if there is a carry in Abs it means the value in exp_offset has only the lowest bit set
             // so the value is the smallest possible integer
             // and its Abs would be greater than mantissa size in bits
             // so the method AddCheckExponents would do nothing
             last_bit_set = rest_zero = do_adding = do_rounding = false;
             rounding_up = (IsSign() == ss2.IsSign());
             AddCheckExponents(ss2, exp_offset, last_bit_set, rest_zero, do_adding, do_rounding);
             if( do_adding )
                 c += AddMantissas(ss2, last_bit_set, rest_zero);
             if( !round || !last_bit_set )
                 do_rounding = false;
             if( do_rounding )
                 c += RoundHalfToEven(rest_zero, rounding_up);
             if( do_adding || do_rounding )
                 c += Standardizing();
         }
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::Abs(), ttmath::Big< exp, man >::ChangeSign(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::SmallerWithoutSignThan(), ttmath::Big< exp, man >::Standardizing(), ttmath::Int< value_size >::Sub(), and ttmath::Big< exp, man >::Swap().
Referenced by ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Round(), and ttmath::Big< exp, man >::Sub().
BitAnd()
template<uint exp, uint man> uint ttmath::Big< exp, man >::BitAnd (Big< exp, man > ss2)
bitwise AND
this and ss2 must be >= 0
return values:
0 - ok
1 - carry
2 - this or ss2 was negative
Definition at line 1002 of file ttmathbig.h.
     {
         uint c = 0;
         if( IsNan() || ss2.IsNan() )
             return CheckCarry(1);
         if( IsSign() || ss2.IsSign() )
         {
             SetNan();
             return 2;
         }
         if( IsZero() )
             return 0;
         if( ss2.IsZero() )
         {
             SetZero();
             return 0;
         }
         // abs(this) will be >= abs(ss2)
         if( SmallerWithoutSignThan(ss2) )
             Swap(ss2);
         Int<exp> exp_offset( exponent );
         Int<exp> mantissa_size_in_bits( man * TTMATH_BITS_PER_UINT );
         exp_offset.Sub( ss2.exponent );
         if( exp_offset.Abs() || exp_offset >= mantissa_size_in_bits )
         {
             // if there is a carry in Abs it means the value in exp_offset has only the lowest bit set
             // so the value is the smallest possible integer
             // and its Abs would be greater than mantissa size in bits
             // the second value is too small
             SetZero();
             return 0;
         }
         // exp_offset < mantissa_size_in_bits, moving 'exp_offset' times
         ss2.mantissa.Rcr( exp_offset.ToInt(), 0 );
         mantissa.BitAnd(ss2.mantissa);
         c += Standardizing();
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::Abs(), ttmath::UInt< value_size >::BitAnd(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::Rcr(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetZero(), ttmath::Big< exp, man >::SmallerWithoutSignThan(), ttmath::Big< exp, man >::Standardizing(), ttmath::Int< value_size >::Sub(), ttmath::Big< exp, man >::Swap(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::operator &().
BitOr()
template<uint exp, uint man> uint ttmath::Big< exp, man >::BitOr (Big< exp, man > ss2)
bitwise OR
this and ss2 must be >= 0 return values:
0 - ok
1 - carry
2 - this or ss2 was negative
Definition at line 1063 of file ttmathbig.h.
     {
         uint c = 0;
         if( IsNan() || ss2.IsNan() )
             return CheckCarry(1);
         if( IsSign() || ss2.IsSign() )
         {
             SetNan();
             return 2;
         }
         if( IsZero() )
         {
             *this = ss2;
             return 0;
         }
         if( ss2.IsZero() )
             return 0;
         // abs(this) will be >= abs(ss2)
         if( SmallerWithoutSignThan(ss2) )
             Swap(ss2);
         Int<exp> exp_offset( exponent );
         Int<exp> mantissa_size_in_bits( man * TTMATH_BITS_PER_UINT );
         exp_offset.Sub( ss2.exponent );
         if( exp_offset.Abs() || exp_offset >= mantissa_size_in_bits )
         {
             // if there is a carry in Abs it means the value in exp_offset has only the lowest bit set
             // so the value is the smallest possible integer
             // and its Abs would be greater than mantissa size in bits
             // the second value is too small
             return 0;
         }
         // exp_offset < mantissa_size_in_bits, moving 'exp_offset' times
         ss2.mantissa.Rcr( exp_offset.ToInt(), 0 );
         mantissa.BitOr(ss2.mantissa);
         c += Standardizing();
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::Abs(), ttmath::UInt< value_size >::BitOr(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::Rcr(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SmallerWithoutSignThan(), ttmath::Big< exp, man >::Standardizing(), ttmath::Int< value_size >::Sub(), ttmath::Big< exp, man >::Swap(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
BitXor()
template<uint exp, uint man> uint ttmath::Big< exp, man >::BitXor (Big< exp, man > ss2)
bitwise XOR
this and ss2 must be >= 0 return values:
0 - ok
1 - carry
2 - this or ss2 was negative
Definition at line 1123 of file ttmathbig.h.
     {
         uint c = 0;
         if( IsNan() || ss2.IsNan() )
             return CheckCarry(1);
         if( IsSign() || ss2.IsSign() )
         {
             SetNan();
             return 2;
         }
         if( ss2.IsZero() )
             return 0;
         if( IsZero() )
         {
             *this = ss2;
             return 0;
         }
         // abs(this) will be >= abs(ss2)
         if( SmallerWithoutSignThan(ss2) )
             Swap(ss2);
         Int<exp> exp_offset( exponent );
         Int<exp> mantissa_size_in_bits( man * TTMATH_BITS_PER_UINT );
         exp_offset.Sub( ss2.exponent );
         if( exp_offset.Abs() || exp_offset >= mantissa_size_in_bits )
         {
             // if there is a carry in Abs it means the value in exp_offset has only the lowest bit set
             // so the value is the smallest possible integer
             // and its Abs would be greater than mantissa size in bits
             // the second value is too small
             return 0;
         }
         // exp_offset < mantissa_size_in_bits, moving 'exp_offset' times
         ss2.mantissa.Rcr( exp_offset.ToInt(), 0 );
         mantissa.BitXor(ss2.mantissa);
         c += Standardizing();
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::Abs(), ttmath::UInt< value_size >::BitXor(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::Rcr(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SmallerWithoutSignThan(), ttmath::Big< exp, man >::Standardizing(), ttmath::Int< value_size >::Sub(), ttmath::Big< exp, man >::Swap(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
ChangeSign()
template<uint exp, uint man> void ttmath::Big< exp, man >::ChangeSign ()
this method changes the sign when there is a value of zero then the sign is not changed
samples
-1 -> 1
2 -> -2
Definition at line 740 of file ttmathbig.h.
     {
         // we don't have to check the NaN flag here
         if( IsZero() )
             return;
         if( IsSign() )
             ClearInfoBit(TTMATH_BIG_SIGN);
         else
             SetInfoBit(TTMATH_BIG_SIGN);
     }
References ttmath::Big< exp, man >::ClearInfoBit(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::SetInfoBit(), and TTMATH_BIG_SIGN.
Referenced by ttmath::Big< exp, man >::Add(), and ttmath::Big< exp, man >::operator-().
CheckCarry()
template<uint exp, uint man> uint ttmath::Big< exp, man >::CheckCarry (uint c)
this method sets NaN if there was a carry (and returns 1 in such a case)
c can be 0, 1 or other value different from zero
Definition at line 121 of file ttmathbig.h.
     {
         if( c != 0 )
         {
             SetNan();
             return 1;
         }
     return 0;
     }
References ttmath::Big< exp, man >::SetNan().
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::FromBig(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowFrac(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::Round(), and ttmath::Big< exp, man >::Sqrt().
ClearInfoBit()
template<uint exp, uint man> void ttmath::Big< exp, man >::ClearInfoBit (unsigned char bit)
this method clears a specific bit in the 'info' variable
bit is one of: TTMATH_BIG_SIGN, TTMATH_BIG_NAN etc.
Definition at line 224 of file ttmathbig.h.
     {
         info = info & (~bit);
     }
Referenced by ttmath::Big< exp, man >::Abs(), ttmath::Big< exp, man >::ChangeSign(), and ttmath::Big< exp, man >::Standardizing().
Div()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Div (const Big< exp, man > & ss2, bool round = true)
division this = this / ss2
return value:
0 - ok
1 - carry (in a division carry can be as well)
2 - improper argument (ss2 is zero)
Definition at line 1470 of file ttmathbig.h.
     {
         if( this == &ss2 )
         {
             Big<exp, man> copy_ss2(ss2);
             return DivRef(copy_ss2, round);
         }
         else
         {
             return DivRef(ss2, round);
         }
     }
Referenced by ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::Pow(), and ttmath::Big< exp, man >::PowInt().
EqualWithoutSign()
template<uint exp, uint man> bool ttmath::Big< exp, man >::EqualWithoutSign (const Big< exp, man > & ss2) const
this method performs the formula 'abs(this) == abs(ss2)' and returns the result
(in other words it treats 'this' and 'ss2' as values without a sign) we don't check the NaN flag
Definition at line 5491 of file ttmathbig.h.
     {
         if( IsZero() )
         {
             if( ss2.IsZero() )
             {
                 // we've got two zeroes
                 return true;
             }
             else
             {
                 // this==0 and ss2!=0
                 return false;
             }
         }
         if( ss2.IsZero() )
         {
             // this!=0 and ss2==0
             return false;
         }
         if( exponent==ss2.exponent && mantissa==ss2.mantissa )
             return true;
     return false;
     }
References ttmath::Big< exp, man >::IsZero().
Exp()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Exp (const Big< exp, man > & x)
Exponent this = exp(x) = e^x
we're using the fact that our value is stored in form of:
x = mantissa * 2^exponent
then
e^x = e^(mantissa* 2^exponent) or
e^x = (e^mantissa)^(2^exponent)
'Exp' returns a carry if we can't count the result ('x' is too big)
Definition at line 1966 of file ttmathbig.h.
     {
     uint c = 0;
         if( x.IsNan() )
             return CheckCarry(1);
         if( x.IsZero() )
         {
             SetOne();
         return 0;
         }
         // m will be the value of the mantissa in range (-1,1)
         Big<exp,man> m(x);
         m.exponent = -sint(man*TTMATH_BITS_PER_UINT);
         // 'e_' will be the value of '2^exponent'
         //   e_.mantissa.table[man-1] = TTMATH_UINT_HIGHEST_BIT;  and
         //   e_.exponent.Add(1) mean:
         //     e_.mantissa.table[0] = 1;
         //     e_.Standardizing();
         //     e_.exponent.Add(man*TTMATH_BITS_PER_UINT)
         //     (we must add 'man*TTMATH_BITS_PER_UINT' because we've taken it from the mantissa)
         Big<exp,man> e_(x);
         e_.mantissa.SetZero();
         e_.mantissa.table[man-1] = TTMATH_UINT_HIGHEST_BIT;
         c += e_.exponent.Add(1);
         e_.Abs();
         /*
             now we've got:
             m - the value of the mantissa in range (-1,1)
             e_ - 2^exponent
             e_ can be as:
             ...2^-2, 2^-1, 2^0, 2^1, 2^2 ...
             ...1/4 , 1/2 , 1  , 2  , 4   ...
             above one e_ is integer
             if e_ is greater than 1 we calculate the exponent as:
                 e^(m * e_) = ExpSurrounding0(m) ^ e_
             and if e_ is smaller or equal one we calculate the exponent in this way:
                 e^(m * e_) = ExpSurrounding0(m* e_)
             because if e_ is smaller or equal 1 then the product of m*e_ is smaller or equal m
         */
         if( e_ <= 1 )
         {
             m.Mul(e_);
             ExpSurrounding0(m);
         }
         else
         {
             ExpSurrounding0(m);
             c += PowUInt(e_);
         }
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::Abs(), ttmath::Int< value_size >::Add(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Mul(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::SetOne(), ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, and TTMATH_UINT_HIGHEST_BIT.
Referenced by ttmath::Big< exp, man >::PowFrac(), and ttmath::Big< exp, man >::Sqrt().
FromBig()
template<uint exp, uint man> template<uint another_exp, uint another_man> uint ttmath::Big< exp, man >::FromBig (const Big< another_exp, another_man > & another)
converting methods
converting from another type of a Big object
Definition at line 2240 of file ttmathbig.h.
     {
         info = another.info;
         if( IsNan() )
             return 1;
         if( exponent.FromInt(another.exponent) )
         {
             SetNan();
             return 1;
         }
         uint man_len_min = (man < another_man)? man : another_man;
         uint i;
         uint c = 0;
         for( i = 0 ; i<man_len_min ; ++i )
             mantissa.table[man-1-i] = another.mantissa.table[another_man-1-i];
         for( ; i<man ; ++i )
             mantissa.table[man-1-i] = 0;
         // MS Visual Express 2005 reports a warning (in the lines with 'uint man_diff = ...'):
         // warning C4307: '*' : integral constant overflow
         // but we're using 'if( man > another_man )' and 'if( man < another_man )' and there'll be no such situation here
         #ifdef _MSC_VER
         #pragma warning( disable: 4307 )
         #endif
         if( man > another_man )
         {
             uint man_diff = (man - another_man) * TTMATH_BITS_PER_UINT;
             c += exponent.SubInt(man_diff, 0);
         }
         else
         if( man < another_man )
         {
             uint man_diff = (another_man - man) * TTMATH_BITS_PER_UINT;
             c += exponent.AddInt(man_diff, 0);
         }
         #ifdef _MSC_VER
         #pragma warning( default: 4307 )
         #endif
         // mantissa doesn't have to be standardized (either the highest bit is set or all bits are equal zero)
         CorrectZero();
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::AddInt(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Int< value_size >::FromInt(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::SetNan(), ttmath::Int< value_size >::SubInt(), ttmath::UInt< value_size >::table, and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Big(), and ttmath::Big< exp, man >::operator=().
FromDouble()
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromDouble (double value)
this method converts from standard double into this class
standard double means IEEE-754 floating point value with 64 bits it is as follows (from http://www.psc.edu/general/software/packages/ieee/ieee.html):
The IEEE double precision floating point standard representation requires a 64 bit word, which may be represented as numbered from 0 to 63, left to right. The first bit is the sign bit, S, the next eleven bits are the exponent bits, 'E', and the final 52 bits are the fraction 'F':
S EEEEEEEEEEE FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
0 1        11 12                                                63
The value V represented by the word may be determined as follows:
If E=2047 and F is nonzero, then V=NaN ("Not a number")
If E=2047 and F is zero and S is 1, then V=-Infinity
If E=2047 and F is zero and S is 0, then V=Infinity
If 0<E<2047 then V=(-1)**S * 2 ** (E-1023) * (1.F) where "1.F" is intended to represent the binary number created by prefixing F with an implicit leading 1 and a binary point.
If E=0 and F is nonzero, then V=(-1)**S * 2 ** (-1022) * (0.F) These are "unnormalized" values.
If E=0 and F is zero and S is 1, then V=-0
If E=0 and F is zero and S is 0, then V=0
Definition at line 2736 of file ttmathbig.h.
     {
         // I am not sure what will be on a plaltform which has
         // a different endianness... but we use this library only
         // on x86 and amd (intel) 64 bits (as there's a lot of assembler code)
         union
         {
             double d;
             uint u; // one 64bit word
         } temp;
         temp.d = value;
         sint e = (temp.u & 0x7FF0000000000000ul) >> 52;
         uint m = (temp.u &    0xFFFFFFFFFFFFFul) << 11;
         if( e == 2047 )
         {
             // If E=2047 and F is nonzero, then V=NaN ("Not a number")
             // If E=2047 and F is zero and S is 1, then V=-Infinity
             // If E=2047 and F is zero and S is 0, then V=Infinity
             // we do not support -Infinity and +Infinity
             // we assume that there is always NaN
             SetNan();
         }
         else
         if( e > 0 )
         {
             // If 0<E<2047 then
             // V=(-1)**S * 2 ** (E-1023) * (1.F)
             // where "1.F" is intended to represent the binary number
             // created by prefixing F with an implicit leading 1 and a binary point.
             FromDouble_SetExpAndMan((temp.u & 0x8000000000000000ul) != 0,
                                     e - 1023 - man*TTMATH_BITS_PER_UINT + 1,
                                     0x8000000000000000ul, m);
             // we do not have to call Standardizing() here
             // because the mantissa will have the highest bit set
         }
         else
         {
             // e == 0
             if( m != 0 )
             {
                 // If E=0 and F is nonzero,
                 // then V=(-1)**S * 2 ** (-1022) * (0.F)
                 // These are "unnormalized" values.
                 FromDouble_SetExpAndMan(bool(temp.u & 0x8000000000000000ul),
                                         e - 1022 - man*TTMATH_BITS_PER_UINT + 1, 0, m);
                 Standardizing();
             }
             else
             {
                 // If E=0 and F is zero and S is 1, then V=-0
                 // If E=0 and F is zero and S is 0, then V=0
                 // we do not support -0 or 0, only is one 0
                 SetZero();
             }
         }
     return 0; // never be a carry
     }
References ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetZero(), ttmath::Big< exp, man >::Standardizing(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Big(), ttmath::Big< exp, man >::FromFloat(), and ttmath::Big< exp, man >::operator=().
FromFloat()
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromFloat (float value)
this method converts from float to this class
Definition at line 2833 of file ttmathbig.h.
     {
         return FromDouble(double(value));
     }
References ttmath::Big< exp, man >::FromDouble().
Referenced by ttmath::Big< exp, man >::Big(), and ttmath::Big< exp, man >::operator=().
FromInt() [1/4]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromInt (uint value)
a method for converting 'uint' to this class
Definition at line 2564 of file ttmathbig.h.
     {
         return FromUInt(value);
     }
References ttmath::Big< exp, man >::FromUInt().
Referenced by ttmath::Big< exp, man >::Big(), ttmath::Big< exp, man >::Ln(), and ttmath::Big< exp, man >::operator=().
FromInt() [2/4]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromInt (sint value)
a method for converting 'sint' to this class
Definition at line 2573 of file ttmathbig.h.
     {
     bool is_sign = false;
         if( value < 0 )
         {
             value   = -value;
             is_sign = true;
         }
         FromUInt(uint(value));
         if( is_sign )
             SetSign();
     return 0;
     }
References ttmath::Big< exp, man >::FromUInt(), and ttmath::Big< exp, man >::SetSign().
FromInt() [3/4]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::FromInt (const UInt< int_size > & value)
a method for converting from 'UInt<int_size>' to this class
Definition at line 3551 of file ttmathbig.h.
     {
         return FromUInt(value);
     }
References ttmath::Big< exp, man >::FromUInt().
FromInt() [4/4]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::FromInt (Int< int_size > value)
a method for converting from 'Int<int_size>' to this class
Definition at line 3561 of file ttmathbig.h.
     {
         info = 0;
         bool is_sign = false;
         if( value.IsSign() )
         {
             value.ChangeSign();
             is_sign = true;
         }
         sint compensation = (sint)value.CompensationToLeft();
         FromUIntOrInt(value, compensation);
         if( is_sign )
             SetSign();
     return 0;
     }
References ttmath::Int< value_size >::ChangeSign(), ttmath::UInt< value_size >::CompensationToLeft(), ttmath::Int< value_size >::IsSign(), and ttmath::Big< exp, man >::SetSign().
FromString() [1/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const char * source, uint base = 10, const char ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
it returns 1 if the value is too big – we cannot pass it into the range of our class Big<exp,man> (or if the base is incorrect)
that means only digits before the comma operator can make this value too big, all digits after the comma we can ignore
'source' - pointer to the string for parsing
if 'after_source' is set that when this method finishes it sets the pointer to the new first character after parsed value
'value_read' - if the pointer is provided that means the value_read will be true only when a value has been actually read, there can be situation where only such a string '-' or '+' will be parsed – 'after_source' will be different from 'source' but no value has been read (there are no digits) on other words if 'value_read' is true – there is at least one digit in the string
Definition at line 4949 of file ttmathbig.h.
     {
         Conv conv;
         conv.base = base;
         return FromStringBase(source, conv, after_source, value_read);
     }
References ttmath::Conv::base.
Referenced by ttmath::Big< exp, man >::Big(), ttmath::Big< exp, man >::FromString(), and ttmath::Big< exp, man >::operator=().
FromString() [2/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const char * source, const Conv & conv, const char ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 4961 of file ttmathbig.h.
     {
         return FromStringBase(source, conv, after_source, value_read);
     }
FromString() [3/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const std::string & string, uint base = 10, const char ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 4970 of file ttmathbig.h.
     {
         return FromString(string.c_str(), base, after_source, value_read);
     }
References ttmath::Big< exp, man >::FromString().
FromString() [4/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const std::string & string, const Conv & conv, const char ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 4979 of file ttmathbig.h.
     {
         return FromString(string.c_str(), conv, after_source, value_read);
     }
References ttmath::Big< exp, man >::FromString().
FromString() [5/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const wchar_t * source, uint base = 10, const wchar_t ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 4990 of file ttmathbig.h.
     {
         Conv conv;
         conv.base = base;
         return FromStringBase(source, conv, after_source, value_read);
     }
References ttmath::Conv::base.
FromString() [6/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const wchar_t * source, const Conv & conv, const wchar_t ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 5002 of file ttmathbig.h.
     {
         return FromStringBase(source, conv, after_source, value_read);
     }
FromString() [7/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const std::wstring & string, uint base = 10, const wchar_t ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 5011 of file ttmathbig.h.
     {
         return FromString(string.c_str(), base, after_source, value_read);
     }
References ttmath::Big< exp, man >::FromString().
FromString() [8/8]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromString (const std::wstring & string, const Conv & conv, const wchar_t ** after_source = 0, bool * value_read = 0)
a method for converting a string into its value
Definition at line 5020 of file ttmathbig.h.
     {
         return FromString(string.c_str(), conv, after_source, value_read);
     }
References ttmath::Big< exp, man >::FromString().
FromUInt() [1/2]
template<uint exp, uint man> uint ttmath::Big< exp, man >::FromUInt (uint value)
a method for converting 'uint' to this class
Definition at line 2538 of file ttmathbig.h.
     {
         if( value == 0 )
         {
             SetZero();
             return 0;
         }
         info = 0;
         for(uint i=0 ; i<man-1 ; ++i)
             mantissa.table[i] = 0;
         mantissa.table[man-1] = value;
         exponent = -sint(man-1) * sint(TTMATH_BITS_PER_UINT);
         // there shouldn't be a carry because 'value' has the 'uint' type
         Standardizing();
     return 0;
     }
References ttmath::Big< exp, man >::SetZero(), ttmath::Big< exp, man >::Standardizing(), ttmath::UInt< value_size >::table, and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Big(), ttmath::Big< exp, man >::FromInt(), and ttmath::Big< exp, man >::operator=().
FromUInt() [2/2]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::FromUInt (UInt< int_size > value)
a method for converting from 'UInt<int_size>' to this class
Definition at line 3538 of file ttmathbig.h.
     {
         info = 0;
         sint compensation = (sint)value.CompensationToLeft();
     return FromUIntOrInt(value, compensation);
     }
References ttmath::UInt< value_size >::CompensationToLeft().
GreaterWithoutSignThan()
template<uint exp, uint man> bool ttmath::Big< exp, man >::GreaterWithoutSignThan (const Big< exp, man > & ss2) const
this method performs the formula 'abs(this) > abs(ss2)' and returns the result
(in other words it treats 'this' and 'ss2' as values without a sign) we don't check the NaN flag
Definition at line 5453 of file ttmathbig.h.
     {
         if( IsZero() )
         {
             if( ss2.IsZero() )
             {
                 // we've got two zeroes
                 return false;
             }
             else
             {
                 // this==0 and ss2!=0
                 return false;
             }
         }
         if( ss2.IsZero() )
         {
             // this!=0 and ss2==0
             return true;
         }
         // we're using the fact that all bits in mantissa are pushed
         // into the left side -- Standardizing()
         if( exponent == ss2.exponent )
             return mantissa > ss2.mantissa;
     return exponent > ss2.exponent;
     }
References ttmath::Big< exp, man >::IsZero().
IsInfoBit()
template<uint exp, uint man> bool ttmath::Big< exp, man >::IsInfoBit (unsigned char bit) const
this method returns true if a specific bit in the 'info' variable is set
bit is one of: TTMATH_BIG_SIGN, TTMATH_BIG_NAN etc.
Definition at line 247 of file ttmathbig.h.
     {
         return (info & bit) != 0;
     }
Referenced by ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), and ttmath::Big< exp, man >::IsZero().
IsInteger()
template<uint exp, uint man> bool ttmath::Big< exp, man >::IsInteger () const
this method returns true if the value is integer (there is no a fraction)
(we don't check NaN)
Definition at line 5883 of file ttmathbig.h.
     {
         if( IsZero() )
             return true;
         if( !exponent.IsSign() )
             // exponent >=0 -- the value don't have any fractions
             return true;
         if( exponent <= -sint(man*TTMATH_BITS_PER_UINT) )
             // the value is from (-1,1)
             return false;
         // exponent is in range (-man*TTMATH_BITS_PER_UINT, 0)
         sint e = exponent.ToInt();
         e = -e; // e means how many bits we must check
         uint len  = e / TTMATH_BITS_PER_UINT;
         uint rest = e % TTMATH_BITS_PER_UINT;
         uint i    = 0;
         for( ; i<len ; ++i )
             if( mantissa.table[i] != 0 )
                 return false;
         if( rest > 0 )
         {
             uint rest_mask = TTMATH_UINT_MAX_VALUE >> (TTMATH_BITS_PER_UINT - rest);
             if( (mantissa.table[i] & rest_mask) != 0 )
                 return false;
         }
     return true;
     }
References ttmath::Int< value_size >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::table, ttmath::Int< value_size >::ToInt(), TTMATH_BITS_PER_UINT, and TTMATH_UINT_MAX_VALUE.
Referenced by ttmath::Big< exp, man >::Pow(), and ttmath::Big< exp, man >::Sqrt().
IsNan()
template<uint exp, uint man> bool ttmath::Big< exp, man >::IsNan () const
this method returns true when there is not a valid number
Definition at line 667 of file ttmathbig.h.
     {
         return IsInfoBit(TTMATH_BIG_NAN);
     }
References ttmath::Big< exp, man >::IsInfoBit(), and TTMATH_BIG_NAN.
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::FromBig(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::MulInt(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowFrac(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::RemainFraction(), ttmath::Big< exp, man >::Round(), ttmath::Big< exp, man >::Sgn(), ttmath::Big< exp, man >::SkipFraction(), ttmath::Big< exp, man >::Sqrt(), and ttmath::Big< exp, man >::ToDouble().
IsSign()
template<uint exp, uint man> bool ttmath::Big< exp, man >::IsSign () const
this method returns true when there's the sign set also we don't check the NaN flag
Definition at line 658 of file ttmathbig.h.
     {
         return IsInfoBit(TTMATH_BIG_SIGN);
     }
References ttmath::Big< exp, man >::IsInfoBit(), and TTMATH_BIG_SIGN.
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::ChangeSign(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::MulInt(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::Round(), ttmath::Big< exp, man >::Sgn(), ttmath::Big< exp, man >::Sqrt(), ttmath::Big< exp, man >::ToDouble(), ttmath::Big< exp, man >::ToInt(), and ttmath::Big< exp, man >::ToUInt().
IsZero()
template<uint exp, uint man> bool ttmath::Big< exp, man >::IsZero () const
testing whether there is a value zero or not
Definition at line 648 of file ttmathbig.h.
     {
         return IsInfoBit(TTMATH_BIG_ZERO);
     }
References ttmath::Big< exp, man >::IsInfoBit(), and TTMATH_BIG_ZERO.
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::ChangeSign(), ttmath::Big< exp, man >::EqualWithoutSign(), ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::GreaterWithoutSignThan(), ttmath::Big< exp, man >::IsInteger(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::MulInt(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::RemainFraction(), ttmath::Big< exp, man >::Round(), ttmath::Big< exp, man >::Sgn(), ttmath::Big< exp, man >::SkipFraction(), ttmath::Big< exp, man >::SmallerWithoutSignThan(), ttmath::Big< exp, man >::Sqrt(), and ttmath::Big< exp, man >::ToDouble().
LibType()
template<uint exp, uint man> static LibTypeCode ttmath::Big< exp, man >::LibType () static
returning the currect type of the library
Definition at line 154 of file ttmathbig.h.
     {
         return UInt<man>::LibType();
     }
References ttmath::UInt< value_size >::LibType().
LibTypeStr()
template<uint exp, uint man> static const char* ttmath::Big< exp, man >::LibTypeStr () static
returning the string represents the currect type of the library we have following types:
asm_vc_32 - with asm code designed for Microsoft Visual C++ (32 bits)
asm_gcc_32 - with asm code designed for GCC (32 bits)
asm_vc_64 - with asm for VC (64 bit)
asm_gcc_64 - with asm for GCC (64 bit)
no_asm_32 - pure C++ version (32 bit) - without any asm code
no_asm_64 - pure C++ version (64 bit) - without any asm code
Definition at line 145 of file ttmathbig.h.
     {
         return UInt<man>::LibTypeStr();
     }
References ttmath::UInt< value_size >::LibTypeStr().
Ln()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Ln (const Big< exp, man > & x)
Natural logarithm this = ln(x) (a logarithm with the base equal 'e')
we're using the fact that our value is stored in form of:
x = mantissa * 2^exponent
then
ln(x) = ln (mantissa * 2^exponent) = ln (mantissa) + (exponent * ln (2))
the mantissa we'll show as a value from range <1,2) because the logarithm is decreasing too fast when 'x' is going to 0
return values:
0 - ok
1 - overflow (carry)
2 - incorrect argument (x<=0)
Definition at line 2144 of file ttmathbig.h.
     {
         if( x.IsNan() )
             return CheckCarry(1);
         if( x.IsSign() || x.IsZero() )
         {
             SetNan();
             return 2;
         }
         Big<exp,man> exponent_temp;
         exponent_temp.FromInt( x.exponent );
         // m will be the value of the mantissa in range <1,2)
         Big<exp,man> m(x);
         m.exponent = -sint(man*TTMATH_BITS_PER_UINT - 1);
         // we must add 'man*TTMATH_BITS_PER_UINT-1' because we've taken it from the mantissa
         uint c = exponent_temp.Add(man*TTMATH_BITS_PER_UINT-1);
         LnSurrounding1(m);
         Big<exp,man> ln2;
         ln2.SetLn2();
         c += exponent_temp.Mul(ln2);
         c += Add(exponent_temp);
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::FromInt(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Mul(), ttmath::Big< exp, man >::SetLn2(), ttmath::Big< exp, man >::SetNan(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::PowFrac(), and ttmath::Big< exp, man >::Sqrt().
Log()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Log (const Big< exp, man > & x, const Big< exp, man > & base)
Logarithm from 'x' with a 'base'
we're using the formula:
Log(x) with 'base' = ln(x) / ln(base)
return values:
0 - ok
1 - overflow
2 - incorrect argument (x<=0)
3 - incorrect base (a<=0 or a=1)
Definition at line 2189 of file ttmathbig.h.
     {
         if( x.IsNan() || base.IsNan() )
             return CheckCarry(1);
         if( x.IsSign() || x.IsZero() )
         {
             SetNan();
             return 2;
         }
         Big<exp,man> denominator;;
         denominator.SetOne();
         if( base.IsSign() || base.IsZero() || base==denominator )
         {
             SetNan();
             return 3;
         }
         if( x == denominator ) // (this is: if x == 1)
         {
             // log(1) is 0
             SetZero();
             return 0;
         }
         // another error values we've tested at the beginning
         // there can only be a carry
         uint c = Ln(x);
         c += denominator.Ln(base);
         c += Div(denominator);
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::Div(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetOne(), and ttmath::Big< exp, man >::SetZero().
Mod()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Mod (const Big< exp, man > & ss2)
caltulate the remainder from a division
samples
12.6 mod 3 = 0.6 because 12.6 = 3*4 + 0.6
-12.6 mod 3 = -0.6 bacause -12.6 = 3*(-4) + (-0.6)
12.6 mod -3 = 0.6
-12.6 mod -3 = -0.6
in other words: this(old) = ss2 * q + this(new)
return value:
0 - ok
1 - carry
2 - improper argument (ss2 is zero)
Definition at line 1539 of file ttmathbig.h.
     {
         if( this == &ss2 )
         {
             Big<exp, man> copy_ss2(ss2);
             return ModRef(copy_ss2);
         }
         else
         {
             return ModRef(ss2);
         }
     }
Mod2()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Mod2 () const
this method returns: 'this' mod 2 (either zero or one)
this method is much faster than using Mod(object_with_value_two)
Definition at line 1559 of file ttmathbig.h.
     {
         if( exponent>sint(0) || exponent<=-sint(man*TTMATH_BITS_PER_UINT) )
             return 0;
         sint exp_int = exponent.ToInt();
         // 'exp_int' is negative (or zero), we set it as positive
         exp_int = -exp_int;
     return mantissa.GetBit(exp_int);
     }
References ttmath::UInt< value_size >::GetBit(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::PowUInt().
Mul()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Mul (const Big< exp, man > & ss2, bool round = true)
multiplication this = this * ss2 this method returns a carry
Definition at line 1373 of file ttmathbig.h.
     {
         if( this == &ss2 )
         {
             Big<exp, man> copy_ss2(ss2);
             return MulRef(copy_ss2, round);
         }
         else
         {
             return MulRef(ss2, round);
         }
     }
Referenced by ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowFrac(), ttmath::Big< exp, man >::PowUInt(), and ttmath::Big< exp, man >::Sqrt().
MulInt()
template<uint exp, uint man> uint ttmath::Big< exp, man >::MulInt (sint ss2)
Multiplication this = this * ss2 (ss2 is sint)
ss2 with a sign
Definition at line 1233 of file ttmathbig.h.
     {
         if( IsNan() )
             return 1;
         if( ss2 == 0 )
         {
             SetZero();
             return 0;
         }
         if( IsZero() )
             return 0;
         if( IsSign() == (ss2<0) )
         {
             // the signs are the same (both are either - or +), the result is positive
             Abs();
         }
         else
         {
             // the signs are different, the result is negative
             SetSign();
         }
         if( ss2<0 )
             ss2 = -ss2;
     return MulUInt( uint(ss2) );
     }
References ttmath::Big< exp, man >::Abs(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::SetSign(), and ttmath::Big< exp, man >::SetZero().
MulUInt()
template<uint exp, uint man> uint ttmath::Big< exp, man >::MulUInt (uint ss2)
Multiplication this = this * ss2 (ss2 is uint)
ss2 without a sign
Definition at line 1179 of file ttmathbig.h.
     {
     UInt<man+1> man_result;
     uint i,c = 0;
         if( IsNan() )
             return 1;
         if( IsZero() )
             return 0;
         if( ss2 == 0 )
         {
             SetZero();
             return 0;
         }
         // man_result = mantissa * ss2.mantissa
         mantissa.MulInt(ss2, man_result);
         sint bit = UInt<man>::FindLeadingBitInWord(man_result.table[man]); // man - last word
         if( bit!=-1 && uint(bit) > (TTMATH_BITS_PER_UINT/2) )
         {
             // 'i' will be from 0 to TTMATH_BITS_PER_UINT
             i = man_result.CompensationToLeft();
             c = exponent.Add( TTMATH_BITS_PER_UINT - i );
             for(i=0 ; i<man ; ++i)
                 mantissa.table[i] = man_result.table[i+1];
         }
         else
         {
             if( bit != -1 )
             {
                 man_result.Rcr(bit+1, 0);
                 c += exponent.Add(bit+1);
             }
             for(i=0 ; i<man ; ++i)
                 mantissa.table[i] = man_result.table[i];
         }
         c += Standardizing();
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::Add(), ttmath::Big< exp, man >::CheckCarry(), ttmath::UInt< value_size >::CompensationToLeft(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::MulInt(), ttmath::UInt< value_size >::Rcr(), ttmath::Big< exp, man >::SetZero(), ttmath::Big< exp, man >::Standardizing(), ttmath::UInt< value_size >::table, and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::MulInt().
operator &()
template<uint exp, uint man> Big<exp,man> ttmath::Big< exp, man >::operator & (const Big< exp, man > & p2) const
bitwise operators (we do not define bitwise not)
Definition at line 5739 of file ttmathbig.h.
     {
         Big<exp,man> temp( *this );
         temp.BitAnd(p2);
     return temp;
     }
References ttmath::Big< exp, man >::BitAnd().
operator++() [1/2]
template<uint exp, uint man> Big<exp,man>& ttmath::Big< exp, man >::operator++ ()
Prefix operator e.g ++variable
Definition at line 5692 of file ttmathbig.h.
     {
         AddOne();
     return *this;
     }
operator++() [2/2]
template<uint exp, uint man> Big<exp,man> ttmath::Big< exp, man >::operator++ (int)
Postfix operator e.g variable++
Definition at line 5703 of file ttmathbig.h.
     {
     Big<exp,man> temp( *this );
         AddOne();
     return temp;
     }
operator-()
template<uint exp, uint man> Big<exp,man> ttmath::Big< exp, man >::operator- () const
standard mathematical operators
an operator for changing the sign
this method is not changing 'this' but the changed value is returned
Definition at line 5608 of file ttmathbig.h.
     {
         Big<exp,man> temp(*this);
         temp.ChangeSign();
     return temp;
     }
References ttmath::Big< exp, man >::ChangeSign().
operator=() [1/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (sint value)
an operator= for converting 'sint' to this class
Definition at line 3119 of file ttmathbig.h.
     {
         FromInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromInt().
Referenced by ttmath::Big< exp, man >::Big().
operator=() [2/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (uint value)
an operator= for converting 'uint' to this class
Definition at line 3130 of file ttmathbig.h.
     {
         FromUInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromUInt().
operator=() [3/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (float value)
an operator= for converting 'float' to this class
Definition at line 3141 of file ttmathbig.h.
     {
         FromFloat(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromFloat().
operator=() [4/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (double value)
an operator= for converting 'double' to this class
Definition at line 3152 of file ttmathbig.h.
     {
         FromDouble(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromDouble().
operator=() [5/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (unsigned int value)
an operator= for converting 32 bit unsigned int to this class this operator is created only on a 64bit platform***
Definition at line 3458 of file ttmathbig.h.
     {
         FromUInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromUInt().
operator=() [6/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (signed int value)
an operator for converting 32 bit signed int to this class this operator is created only on a 64bit platform***
Definition at line 3480 of file ttmathbig.h.
     {
         FromInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromInt().
operator=() [7/14]
template<uint exp, uint man> template<uint int_size> Big<exp,man>& ttmath::Big< exp, man >::operator= (const Int< int_size > & value)
an operator= for converting from 'Int<int_size>' to this class
Definition at line 3586 of file ttmathbig.h.
     {
         FromInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromInt().
operator=() [8/14]
template<uint exp, uint man> template<uint int_size> Big<exp,man>& ttmath::Big< exp, man >::operator= (const UInt< int_size > & value)
an operator= for converting from 'UInt<int_size>' to this class
Definition at line 3608 of file ttmathbig.h.
     {
         FromUInt(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromUInt().
operator=() [9/14]
template<uint exp, uint man> template<uint another_exp, uint another_man> Big<exp,man>& ttmath::Big< exp, man >::operator= (const Big< another_exp, another_man > & value)
an operator= for converting from 'Big<another_exp, another_man>' to this class
Definition at line 3630 of file ttmathbig.h.
     {
         FromBig(value);
     return *this;
     }
References ttmath::Big< exp, man >::FromBig().
operator=() [10/14]
template<uint exp, uint man> Big<exp,man>& ttmath::Big< exp, man >::operator= (const Big< exp, man > & value)
the default assignment operator
Definition at line 3685 of file ttmathbig.h.
     {
         info     = value.info;
         exponent = value.exponent;
         mantissa = value.mantissa;
     return *this;
     }
operator=() [11/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (const char * string)
an operator= for converting a string into its value
Definition at line 5339 of file ttmathbig.h.
     {
         FromString( string );
     return *this;
     }
References ttmath::Big< exp, man >::FromString().
operator=() [12/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (const std::string & string)
an operator= for converting a string into its value
Definition at line 5350 of file ttmathbig.h.
     {
         FromString( string.c_str() );
     return *this;
     }
References ttmath::Big< exp, man >::FromString().
operator=() [13/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (const wchar_t * string)
an operator= for converting a string into its value
Definition at line 5382 of file ttmathbig.h.
     {
         FromString( string );
     return *this;
     }
References ttmath::Big< exp, man >::FromString().
operator=() [14/14]
template<uint exp, uint man> Big<exp, man>& ttmath::Big< exp, man >::operator= (const std::wstring & string)
an operator= for converting a string into its value
Definition at line 5393 of file ttmathbig.h.
     {
         FromString( string.c_str() );
     return *this;
     }
References ttmath::Big< exp, man >::FromString().
Pow() [1/3]
template<uint exp, uint man> template<uint pow_size> uint ttmath::Big< exp, man >::Pow (UInt< pow_size > pow)
power this = this ^ pow (pow without a sign)
binary algorithm (r-to-l)
return values:
0 - ok
1 - carry
2 - incorrect arguments (0^0)
Definition at line 1584 of file ttmathbig.h.
     {
         if( IsNan() )
             return 1;
         if( IsZero() )
         {
             if( pow.IsZero() )
             {
                 // we don't define zero^zero
                 SetNan();
                 return 2;
             }
             // 0^(+something) is zero
             return 0;
         }
         Big<exp, man> start(*this);
         Big<exp, man> result;
         result.SetOne();
         uint c = 0;
         while( !c )
         {
             if( pow.table[0] & 1 )
                 c += result.Mul(start);
             pow.Rcr(1);
             if( pow.IsZero() )
                 break;
             c += start.Mul(start);
         }
         *this = result;
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::IsZero(), ttmath::Big< exp, man >::Mul(), ttmath::UInt< value_size >::Rcr(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetOne(), and ttmath::UInt< value_size >::table.
Referenced by ttmath::Big< exp, man >::Pow().
Pow() [2/3]
template<uint exp, uint man> template<uint pow_size> uint ttmath::Big< exp, man >::Pow (Int< pow_size > pow)
power this = this ^ pow p can be negative
return values:
0 - ok
1 - carry
2 - incorrect arguments 0^0 or 0^(-something)
Definition at line 1636 of file ttmathbig.h.
     {
         if( IsNan() )
             return 1;
         if( !pow.IsSign() )
             return Pow( UInt<pow_size>(pow) );
         if( IsZero() )
         {
             // if 'p' is negative then
             // 'this' must be different from zero
             SetNan();
             return 2;
         }
         uint c = pow.ChangeSign();
         Big<exp, man> t(*this);
         c += t.Pow( UInt<pow_size>(pow) ); // here can only be a carry (return:1)
         SetOne();
         c += Div(t);
     return CheckCarry(c);
     }
References ttmath::Int< value_size >::ChangeSign(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::Div(), ttmath::Big< exp, man >::IsNan(), ttmath::Int< value_size >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::SetNan(), and ttmath::Big< exp, man >::SetOne().
Pow() [3/3]
template<uint exp, uint man> uint ttmath::Big< exp, man >::Pow (const Big< exp, man > & pow)
power this = this ^ pow pow can be negative and with fraction
return values:
0 - ok
1 - carry
2 - incorrect argument ('this' or 'pow')
Definition at line 1797 of file ttmathbig.h.
     {
         if( IsNan() || pow.IsNan() )
             return CheckCarry(1);
         if( IsZero() )
         {
             // 0^pow will be 0 only for pow>0
             if( pow.IsSign() || pow.IsZero() )
             {
                 SetNan();
                 return 2;
             }
             SetZero();
         return 0;
         }
         if( pow.exponent>-sint(man*TTMATH_BITS_PER_UINT) && pow.exponent<=0 )
         {
             if( pow.IsInteger() )
                 return PowInt( pow );
         }
     return PowFrac(pow);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsInteger(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::PowFrac(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetZero(), and TTMATH_BITS_PER_UINT.
PowFrac()
template<uint exp, uint man> uint ttmath::Big< exp, man >::PowFrac (const Big< exp, man > & pow)
power this = this ^ pow this must be greater than zero (this > 0) pow can be negative and with fraction
return values:
0 - ok
1 - carry
2 - incorrect argument ('this' <= 0)
Definition at line 1767 of file ttmathbig.h.
     {
         if( IsNan() || pow.IsNan() )
             return CheckCarry(1);
         Big<exp, man> temp;
         uint c = temp.Ln(*this);
         if( c != 0 ) // can be 2 from Ln()
         {
             SetNan();
             return c;
         }
         c += temp.Mul(pow);
         c += Exp(temp);
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Mul(), and ttmath::Big< exp, man >::SetNan().
Referenced by ttmath::Big< exp, man >::Pow().
PowInt()
template<uint exp, uint man> uint ttmath::Big< exp, man >::PowInt (const Big< exp, man > & pow)
power this = this ^ [pow] pow is treated as a value without a fraction pow can be negative
return values:
0 - ok
1 - carry
2 - incorrect arguments 0^0 or 0^(-something)
Definition at line 1731 of file ttmathbig.h.
     {
         if( IsNan() || pow.IsNan() )
             return CheckCarry(1);
         if( !pow.IsSign() )
             return PowUInt(pow);
         if( IsZero() )
         {
             // if 'pow' is negative then
             // 'this' must be different from zero
             SetNan();
             return 2;
         }
         Big<exp, man> temp(*this);
         uint c = temp.PowUInt(pow); // here can only be a carry (result:1)
         SetOne();
         c += Div(temp);
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::Div(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::SetNan(), and ttmath::Big< exp, man >::SetOne().
Referenced by ttmath::Big< exp, man >::Pow().
PowUInt()
template<uint exp, uint man> uint ttmath::Big< exp, man >::PowUInt (Big< exp, man > pow)
power this = this ^ abs([pow]) pow is treated as a value without a sign and without a fraction if pow has a sign then the method pow.Abs() is used if pow has a fraction the fraction is skipped (not used in calculation)
return values:
0 - ok
1 - carry
2 - incorrect arguments (0^0)
Definition at line 1675 of file ttmathbig.h.
     {
         if( IsNan() || pow.IsNan() )
             return CheckCarry(1);
         if( IsZero() )
         {
             if( pow.IsZero() )
             {
                 SetNan();
                 return 2;
             }
             // 0^(+something) is zero
             return 0;
         }
         if( pow.IsSign() )
             pow.Abs();
         Big<exp, man> start(*this);
         Big<exp, man> result;
         Big<exp, man> one;
         uint c = 0;
         one.SetOne();
         result = one;
         while( !c )
         {
             if( pow.Mod2() )
                 c += result.Mul(start);
             c += pow.exponent.SubOne();
             if( pow < one )
                 break;
             c += start.Mul(start);
         }
         *this = result;
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::Abs(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Mod2(), ttmath::Big< exp, man >::Mul(), ttmath::Big< exp, man >::SetNan(), ttmath::Big< exp, man >::SetOne(), and ttmath::Int< value_size >::SubOne().
Referenced by ttmath::Big< exp, man >::Exp(), and ttmath::Big< exp, man >::PowInt().
RemainFraction()
template<uint exp, uint man> void ttmath::Big< exp, man >::RemainFraction ()
this method remains only a fraction from the value
samples:
30.56 will be 0.56
-12.67 will be -0.67
Definition at line 5842 of file ttmathbig.h.
     {
         if( IsNan() || IsZero() )
             return;
         if( !exponent.IsSign() )
         {
             // exponent >= 0 -- the value doesn't have any fractions
             // we return zero
             SetZero();
             return;
         }
         if( exponent <= -sint(man*TTMATH_BITS_PER_UINT) )
         {
             // the value is from (-1,1)
             // we don't make anything with the value
             return;
         }
         // e will be from (-man*TTMATH_BITS_PER_UINT, 0)
         sint e = exponent.ToInt();
         sint how_many_bits_leave = sint(man*TTMATH_BITS_PER_UINT) + e; // there'll be a subtraction -- e is negative
         mantissa.Rcl( how_many_bits_leave, 0);
         // there'll not be a carry because the exponent is too small
         exponent.Sub( how_many_bits_leave );
         // we must call Standardizing() here
         Standardizing();
     }
References ttmath::Big< exp, man >::IsNan(), ttmath::Int< value_size >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::UInt< value_size >::Rcl(), ttmath::Big< exp, man >::SetZero(), ttmath::Big< exp, man >::Standardizing(), ttmath::Int< value_size >::Sub(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
Round()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Round ()
this method rounds to the nearest integer value (it returns a carry if it was)
samples:
2.3 = 2
2.8 = 3
-2.3 = -2
-2.8 = 3
Definition at line 5929 of file ttmathbig.h.
     {
     Big<exp,man> half;
     uint c;
         if( IsNan() )
             return 1;
         if( IsZero() )
             return 0;
         half.Set05();
         if( IsSign() )
         {
             // 'this' is < 0
             c = Sub( half );
         }
         else
         {
             // 'this' is > 0
             c = Add( half );
         }
         SkipFraction();
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Set05(), ttmath::Big< exp, man >::SkipFraction(), and ttmath::Big< exp, man >::Sub().
Referenced by ttmath::Big< exp, man >::Sqrt().
Set05()
template<uint exp, uint man> void ttmath::Big< exp, man >::Set05 ()
this method sets value 0.5
Definition at line 285 of file ttmathbig.h.
     {
         SetOne();
         exponent.SubOne();
     }
References ttmath::Big< exp, man >::SetOne(), and ttmath::Int< value_size >::SubOne().
Referenced by ttmath::Big< exp, man >::Round().
Set05Pi()
template<uint exp, uint man> void ttmath::Big< exp, man >::Set05Pi ()
this method sets the value of 0.5 * pi
Definition at line 406 of file ttmathbig.h.
     {
         // IMPROVE ME
         // give some compiler-time warning when the size of mantissa is greater than the builtin size of the mantissa pi
         SetMantissaPi();
         info = 0;
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT) + 1;
     }
References TTMATH_BITS_PER_UINT.
Set2Pi()
template<uint exp, uint man> void ttmath::Big< exp, man >::Set2Pi ()
this method sets the value of 2 * pi
Definition at line 419 of file ttmathbig.h.
     {
         // IMPROVE ME
         // give some compiler-time warning when the size of mantissa is greater than the builtin size of the mantissa pi
         SetMantissaPi();
         info = 0;
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT) + 3;
     }
References TTMATH_BITS_PER_UINT.
SetE()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetE ()
this method sets the value of e (the base of the natural logarithm)
Definition at line 433 of file ttmathbig.h.
     {
     static const unsigned int temp_table[] = {
         0xadf85458, 0xa2bb4a9a, 0xafdc5620, 0x273d3cf1, 0xd8b9c583, 0xce2d3695, 0xa9e13641, 0x146433fb,
         0xcc939dce, 0x249b3ef9, 0x7d2fe363, 0x630c75d8, 0xf681b202, 0xaec4617a, 0xd3df1ed5, 0xd5fd6561,
         0x2433f51f, 0x5f066ed0, 0x85636555, 0x3ded1af3, 0xb557135e, 0x7f57c935, 0x984f0c70, 0xe0e68b77,
         0xe2a689da, 0xf3efe872, 0x1df158a1, 0x36ade735, 0x30acca4f, 0x483a797a, 0xbc0ab182, 0xb324fb61,
         0xd108a94b, 0xb2c8e3fb, 0xb96adab7, 0x60d7f468, 0x1d4f42a3, 0xde394df4, 0xae56ede7, 0x6372bb19,
         0x0b07a7c8, 0xee0a6d70, 0x9e02fce1, 0xcdf7e2ec, 0xc03404cd, 0x28342f61, 0x9172fe9c, 0xe98583ff,
         0x8e4f1232, 0xeef28183, 0xc3fe3b1b, 0x4c6fad73, 0x3bb5fcbc, 0x2ec22005, 0xc58ef183, 0x7d1683b2,
         0xc6f34a26, 0xc1b2effa, 0x886b4238, 0x611fcfdc, 0xde355b3b, 0x6519035b, 0xbc34f4de, 0xf99c0238,
         0x61b46fc9, 0xd6e6c907, 0x7ad91d26, 0x91f7f7ee, 0x598cb0fa, 0xc186d91c, 0xaefe1309, 0x85139270,
         0xb4130c93, 0xbc437944, 0xf4fd4452, 0xe2d74dd3, 0x64f2e21e, 0x71f54bff, 0x5cae82ab, 0x9c9df69e,
         0xe86d2bc5, 0x22363a0d, 0xabc52197, 0x9b0deada, 0x1dbf9a42, 0xd5c4484e, 0x0abcd06b, 0xfa53ddef,
         0x3c1b20ee, 0x3fd59d7c, 0x25e41d2b, 0x669e1ef1, 0x6e6f52c3, 0x164df4fb, 0x7930e9e4, 0xe58857b6,
         0xac7d5f42, 0xd69f6d18, 0x7763cf1d, 0x55034004, 0x87f55ba5, 0x7e31cc7a, 0x7135c886, 0xefb4318a,
         0xed6a1e01, 0x2d9e6832, 0xa907600a, 0x918130c4, 0x6dc778f9, 0x71ad0038, 0x092999a3, 0x33cb8b7a,
         0x1a1db93d, 0x7140003c, 0x2a4ecea9, 0xf98d0acc, 0x0a8291cd, 0xcec97dcf, 0x8ec9b55a, 0x7f88a46b,
         0x4db5a851, 0xf44182e1, 0xc68a007e, 0x5e0dd902, 0x0bfd64b6, 0x45036c7a, 0x4e677d2c, 0x38532a3a,
         0x23ba4442, 0xcaf53ea6, 0x3bb45432, 0x9b7624c8, 0x917bdd64, 0xb1c0fd4c, 0xb38e8c33, 0x4c701c3a,
         0xcdad0657, 0xfccfec71, 0x9b1f5c3e, 0x4e46041f, 0x388147fb, 0x4cfdb477, 0xa52471f7, 0xa9a96910,
         0xb855322e, 0xdb6340d8, 0xa00ef092, 0x350511e3, 0x0abec1ff, 0xf9e3a26e, 0x7fb29f8c, 0x183023c3,
         0x587e38da, 0x0077d9b4, 0x763e4e4b, 0x94b2bbc1, 0x94c6651e, 0x77caf992, 0xeeaac023, 0x2a281bf6,
         0xb3a739c1, 0x22611682, 0x0ae8db58, 0x47a67cbe, 0xf9c9091b, 0x462d538c, 0xd72b0374, 0x6ae77f5e,
         0x62292c31, 0x1562a846, 0x505dc82d, 0xb854338a, 0xe49f5235, 0xc95b9117, 0x8ccf2dd5, 0xcacef403,
         0xec9d1810, 0xc6272b04, 0x5b3b71f9, 0xdc6b80d6, 0x3fdd4a8e, 0x9adb1e69, 0x62a69526, 0xd43161c1,
         0xa41d570d, 0x7938dad4, 0xa40e329c, 0xcff46aaa, 0x36ad004c, 0xf600c838, 0x1e425a31, 0xd951ae64,
         0xfdb23fce, 0xc9509d43, 0x687feb69, 0xedd1cc5e, 0x0b8cc3bd, 0xf64b10ef, 0x86b63142, 0xa3ab8829,
         0x555b2f74, 0x7c932665, 0xcb2c0f1c, 0xc01bd702, 0x29388839, 0xd2af05e4, 0x54504ac7, 0x8b758282,
         0x2846c0ba, 0x35c35f5c, 0x59160cc0, 0x46fd8251, 0x541fc68c, 0x9c86b022, 0xbb709987, 0x6a460e74,
         0x51a8a931, 0x09703fee, 0x1c217e6c, 0x3826e52c, 0x51aa691e, 0x0e423cfc, 0x99e9e316, 0x50c1217b,
         0x624816cd, 0xad9a95f9, 0xd5b80194, 0x88d9c0a0, 0xa1fe3075, 0xa577e231, 0x83f81d4a, 0x3f2fa457,
         0x1efc8ce0, 0xba8a4fe8, 0xb6855dfe, 0x72b0a66e, 0xded2fbab, 0xfbe58a30, 0xfafabe1c, 0x5d71a87e,
         0x2f741ef8, 0xc1fe86fe, 0xa6bbfde5, 0x30677f0d, 0x97d11d49, 0xf7a8443d, 0x0822e506, 0xa9f4614e,
         0x011e2a94, 0x838ff88c, 0xd68c8bb7, 0xc51eef6d, 0x49ea8ab4, 0xf2c3df5b, 0xb4e0735a, 0xb0d68749
         // 0x2fe26dd4, ...
         // 256 32bit words for the mantissa -- about 2464 valid decimal digits
         };
         // above value was calculated using Big<1,400> type on a 32bit platform
         // and then the first 256 words were taken,
         // the calculating was made by using ExpSurrounding0(1) method
         // which took 1420 iterations
         // (the result was compared with e taken from http://antwrp.gsfc.nasa.gov/htmltest/gifcity/e.2mil)
         // (TTMATH_BUILTIN_VARIABLES_SIZE on 32bit platform should have the value 256,
         // and on 64bit platform value 128 (256/2=128))
         mantissa.SetFromTable(temp_table, sizeof(temp_table) / sizeof(int));
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT) + 2;
         info = 0;
     }
References ttmath::UInt< value_size >::SetFromTable(), and TTMATH_BITS_PER_UINT.
SetInfoBit()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetInfoBit (unsigned char bit)
this method sets a specific bit in the 'info' variable
bit is one of: TTMATH_BIG_SIGN, TTMATH_BIG_NAN etc.
Definition at line 236 of file ttmathbig.h.
     {
         info = info | bit;
     }
Referenced by ttmath::Big< exp, man >::ChangeSign(), ttmath::Big< exp, man >::SetNan(), and ttmath::Big< exp, man >::SetSign().
SetLn10()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetLn10 ()
this method sets the value of ln(10) the natural logarithm from 10
I introduced this constant especially to make the conversion ToString() being faster. In fact the method ToString() is keeping values of logarithms it has calculated but it must calculate the logarithm at least once. If a program, which uses this library, is running for a long time this would be ok, but for programs which are running shorter, for example for CGI applications which only once are printing values, this would be much inconvenience. Then if we're printing with base (radix) 10 and the mantissa of our value is smaller than or equal to TTMATH_BUILTIN_VARIABLES_SIZE we don't calculate the logarithm but take it from this constant.
Definition at line 558 of file ttmathbig.h.
     {
     static const unsigned int temp_table[] = {
         0x935d8ddd, 0xaaa8ac16, 0xea56d62b, 0x82d30a28, 0xe28fecf9, 0xda5df90e, 0x83c61e82, 0x01f02d72,
         0x962f02d7, 0xb1a8105c, 0xcc70cbc0, 0x2c5f0d68, 0x2c622418, 0x410be2da, 0xfb8f7884, 0x02e516d6,
         0x782cf8a2, 0x8a8c911e, 0x765aa6c3, 0xb0d831fb, 0xef66ceb0, 0x4ab3c6fa, 0x5161bb49, 0xd219c7bb,
         0xca67b35b, 0x23605085, 0x8e93368d, 0x44789c4f, 0x5b08b057, 0xd5ede20f, 0x469ea58e, 0x9305e981,
         0xe2478fca, 0xad3aee98, 0x9cd5b42e, 0x6a271619, 0xa47ecb26, 0x978c5d4f, 0xdb1d28ea, 0x57d4fdc0,
         0xe40bf3cc, 0x1e14126a, 0x45765cde, 0x268339db, 0xf47fa96d, 0xeb271060, 0xaf88486e, 0xa9b7401e,
         0x3dfd3c51, 0x748e6d6e, 0x3848c8d2, 0x5faf1bca, 0xe88047f1, 0x7b0d9b50, 0xa949eaaa, 0xdf69e8a5,
         0xf77e3760, 0x4e943960, 0xe38a5700, 0xffde2db1, 0xad6bfbff, 0xd821ba0a, 0x4cb0466d, 0x61ba648e,
         0xef99c8e5, 0xf6974f36, 0x3982a78c, 0xa45ddfc8, 0x09426178, 0x19127a6e, 0x3b70fcda, 0x2d732d47,
         0xb5e4b1c8, 0xc0e5a10a, 0xaa6604a5, 0x324ec3dc, 0xbc64ea80, 0x6e198566, 0x1f1d366c, 0x20663834,
         0x4d5e843f, 0x20642b97, 0x0a62d18e, 0x478f7bd5, 0x8fcd0832, 0x4a7b32a6, 0xdef85a05, 0xeb56323a,
         0x421ef5e0, 0xb00410a0, 0xa0d9c260, 0x794a976f, 0xf6ff363d, 0xb00b6b33, 0xf42c58de, 0xf8a3c52d,
         0xed69b13d, 0xc1a03730, 0xb6524dc1, 0x8c167e86, 0x99d6d20e, 0xa2defd2b, 0xd006f8b4, 0xbe145a2a,
         0xdf3ccbb3, 0x189da49d, 0xbc1261c8, 0xb3e4daad, 0x6a36cecc, 0xb2d5ae5b, 0x89bf752f, 0xb5dfb353,
         0xff3065c4, 0x0cfceec8, 0x1be5a9a9, 0x67fddc57, 0xc4b83301, 0x006bf062, 0x4b40ed7a, 0x56c6cdcd,
         0xa2d6fe91, 0x388e9e3e, 0x48a93f5f, 0x5e3b6eb4, 0xb81c4a5b, 0x53d49ea6, 0x8e668aea, 0xba83c7f8,
         0xfb5f06c3, 0x58ac8f70, 0xfa9d8c59, 0x8c574502, 0xbaf54c96, 0xc84911f0, 0x0482d095, 0x1a0af022,
         0xabbab080, 0xec97efd3, 0x671e4e0e, 0x52f166b6, 0xcd5cd226, 0x0dc67795, 0x2e1e34a3, 0xf799677f,
         0x2c1d48f1, 0x2944b6c5, 0x2ba1307e, 0x704d67f9, 0x1c1035e4, 0x4e927c63, 0x03cf12bf, 0xe2cd2e31,
         0xf8ee4843, 0x344d51b0, 0xf37da42b, 0x9f0b0fd9, 0x134fb2d9, 0xf815e490, 0xd966283f, 0x23962766,
         0xeceab1e4, 0xf3b5fc86, 0x468127e2, 0xb606d10d, 0x3a45f4b6, 0xb776102d, 0x2fdbb420, 0x80c8fa84,
         0xd0ff9f45, 0xc58aef38, 0xdb2410fd, 0x1f1cebad, 0x733b2281, 0x52ca5f36, 0xddf29daa, 0x544334b8,
         0xdeeaf659, 0x4e462713, 0x1ed485b4, 0x6a0822e1, 0x28db471c, 0xa53938a8, 0x44c3bef7, 0xf35215c8,
         0xb382bc4e, 0x3e4c6f15, 0x6285f54c, 0x17ab408e, 0xccbf7f5e, 0xd16ab3f6, 0xced2846d, 0xf457e14f,
         0xbb45d9c5, 0x646ad497, 0xac697494, 0x145de32e, 0x93907128, 0xd263d521, 0x79efb424, 0xd64651d6,
         0xebc0c9f0, 0xbb583a44, 0xc6412c84, 0x85bb29a6, 0x4d31a2cd, 0x92954469, 0xa32b1abd, 0xf7f5202c,
         0xa4aa6c93, 0x2e9b53cf, 0x385ab136, 0x2741f356, 0x5de9c065, 0x6009901c, 0x88abbdd8, 0x74efcf73,
         0x3f761ad4, 0x35f3c083, 0xfd6b8ee0, 0x0bef11c7, 0xc552a89d, 0x58ce4a21, 0xd71e54f2, 0x4157f6c7,
         0xd4622316, 0xe98956d7, 0x450027de, 0xcbd398d8, 0x4b98b36a, 0x0724c25c, 0xdb237760, 0xe9324b68,
         0x7523e506, 0x8edad933, 0x92197f00, 0xb853a326, 0xb330c444, 0x65129296, 0x34bc0670, 0xe177806d,
         0xe338dac4, 0x5537492a, 0xe19add83, 0xcf45000f, 0x5b423bce, 0x6497d209, 0xe30e18a1, 0x3cbf0687,
         0x67973103, 0xd9485366, 0x81506bba, 0x2e93a9a4, 0x7dd59d3f, 0xf17cd746, 0x8c2075be, 0x552a4348 // last one was: 0x552a4347
         // 0xb4a638ef, ...
         //(the last word 0x552a4347 was rounded up because the next one is 0xb4a638ef -- first bit is one 0xb..)
         // 256 32bit words for the mantissa -- about 2464 valid digits (decimal)
         };
         // above value was calculated using Big<1,400> type on a 32bit platform
         // and then the first 256 32bit words were taken,
         // the calculating was made by using LnSurrounding1(10) method
         // which took 22080 iterations
         // (the result was compared with ln(10) taken from http://ja0hxv.calico.jp/pai/estart.html)
         // (the formula used in LnSurrounding1(x) converges badly when
         // the x is greater than one but in fact we can use it, only the
         // number of iterations will be greater)
         // (TTMATH_BUILTIN_VARIABLES_SIZE on 32bit platform should have the value 256,
         // and on 64bit platform value 128 (256/2=128))
         mantissa.SetFromTable(temp_table, sizeof(temp_table) / sizeof(int));
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT) + 2;
         info = 0;
     }
References ttmath::UInt< value_size >::SetFromTable(), and TTMATH_BITS_PER_UINT.
SetLn2()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetLn2 ()
this method sets the value of ln(2) the natural logarithm from 2
Definition at line 490 of file ttmathbig.h.
     {
     static const unsigned int temp_table[] = {
         0xb17217f7, 0xd1cf79ab, 0xc9e3b398, 0x03f2f6af, 0x40f34326, 0x7298b62d, 0x8a0d175b, 0x8baafa2b,
         0xe7b87620, 0x6debac98, 0x559552fb, 0x4afa1b10, 0xed2eae35, 0xc1382144, 0x27573b29, 0x1169b825,
         0x3e96ca16, 0x224ae8c5, 0x1acbda11, 0x317c387e, 0xb9ea9bc3, 0xb136603b, 0x256fa0ec, 0x7657f74b,
         0x72ce87b1, 0x9d6548ca, 0xf5dfa6bd, 0x38303248, 0x655fa187, 0x2f20e3a2, 0xda2d97c5, 0x0f3fd5c6,
         0x07f4ca11, 0xfb5bfb90, 0x610d30f8, 0x8fe551a2, 0xee569d6d, 0xfc1efa15, 0x7d2e23de, 0x1400b396,
         0x17460775, 0xdb8990e5, 0xc943e732, 0xb479cd33, 0xcccc4e65, 0x9393514c, 0x4c1a1e0b, 0xd1d6095d,
         0x25669b33, 0x3564a337, 0x6a9c7f8a, 0x5e148e82, 0x074db601, 0x5cfe7aa3, 0x0c480a54, 0x17350d2c,
         0x955d5179, 0xb1e17b9d, 0xae313cdb, 0x6c606cb1, 0x078f735d, 0x1b2db31b, 0x5f50b518, 0x5064c18b,
         0x4d162db3, 0xb365853d, 0x7598a195, 0x1ae273ee, 0x5570b6c6, 0x8f969834, 0x96d4e6d3, 0x30af889b,
         0x44a02554, 0x731cdc8e, 0xa17293d1, 0x228a4ef9, 0x8d6f5177, 0xfbcf0755, 0x268a5c1f, 0x9538b982,
         0x61affd44, 0x6b1ca3cf, 0x5e9222b8, 0x8c66d3c5, 0x422183ed, 0xc9942109, 0x0bbb16fa, 0xf3d949f2,
         0x36e02b20, 0xcee886b9, 0x05c128d5, 0x3d0bd2f9, 0x62136319, 0x6af50302, 0x0060e499, 0x08391a0c,
         0x57339ba2, 0xbeba7d05, 0x2ac5b61c, 0xc4e9207c, 0xef2f0ce2, 0xd7373958, 0xd7622658, 0x901e646a,
         0x95184460, 0xdc4e7487, 0x156e0c29, 0x2413d5e3, 0x61c1696d, 0xd24aaebd, 0x473826fd, 0xa0c238b9,
         0x0ab111bb, 0xbd67c724, 0x972cd18b, 0xfbbd9d42, 0x6c472096, 0xe76115c0, 0x5f6f7ceb, 0xac9f45ae,
         0xcecb72f1, 0x9c38339d, 0x8f682625, 0x0dea891e, 0xf07afff3, 0xa892374e, 0x175eb4af, 0xc8daadd8,
         0x85db6ab0, 0x3a49bd0d, 0xc0b1b31d, 0x8a0e23fa, 0xc5e5767d, 0xf95884e0, 0x6425a415, 0x26fac51c,
         0x3ea8449f, 0xe8f70edd, 0x062b1a63, 0xa6c4c60c, 0x52ab3316, 0x1e238438, 0x897a39ce, 0x78b63c9f,
         0x364f5b8a, 0xef22ec2f, 0xee6e0850, 0xeca42d06, 0xfb0c75df, 0x5497e00c, 0x554b03d7, 0xd2874a00,
         0x0ca8f58d, 0x94f0341c, 0xbe2ec921, 0x56c9f949, 0xdb4a9316, 0xf281501e, 0x53daec3f, 0x64f1b783,
         0x154c6032, 0x0e2ff793, 0x33ce3573, 0xfacc5fdc, 0xf1178590, 0x3155bbd9, 0x0f023b22, 0x0224fcd8,
         0x471bf4f4, 0x45f0a88a, 0x14f0cd97, 0x6ea354bb, 0x20cdb5cc, 0xb3db2392, 0x88d58655, 0x4e2a0e8a,
         0x6fe51a8c, 0xfaa72ef2, 0xad8a43dc, 0x4212b210, 0xb779dfe4, 0x9d7307cc, 0x846532e4, 0xb9694eda,
         0xd162af05, 0x3b1751f3, 0xa3d091f6, 0x56658154, 0x12b5e8c2, 0x02461069, 0xac14b958, 0x784934b8,
         0xd6cce1da, 0xa5053701, 0x1aa4fb42, 0xb9a3def4, 0x1bda1f85, 0xef6fdbf2, 0xf2d89d2a, 0x4b183527,
         0x8fd94057, 0x89f45681, 0x2b552879, 0xa6168695, 0xc12963b0, 0xff01eaab, 0x73e5b5c1, 0x585318e7,
         0x624f14a5, 0x1a4a026b, 0x68082920, 0x57fd99b6, 0x6dc085a9, 0x8ac8d8ca, 0xf9eeeea9, 0x8a2400ca,
         0xc95f260f, 0xd10036f9, 0xf91096ac, 0x3195220a, 0x1a356b2a, 0x73b7eaad, 0xaf6d6058, 0x71ef7afb,
         0x80bc4234, 0x33562e94, 0xb12dfab4, 0x14451579, 0xdf59eae0, 0x51707062, 0x4012a829, 0x62c59cab,
         0x347f8304, 0xd889659e, 0x5a9139db, 0x14efcc30, 0x852be3e8, 0xfc99f14d, 0x1d822dd6, 0xe2f76797,
         0xe30219c8, 0xaa9ce884, 0x8a886eb3, 0xc87b7295, 0x988012e8, 0x314186ed, 0xbaf86856, 0xccd3c3b6,
         0xee94e62f, 0x110a6783, 0xd2aae89c, 0xcc3b76fc, 0x435a0ce1, 0x34c2838f, 0xd571ec6c, 0x1366a993 // last one was: 0x1366a992
         //0xcbb9ac40, ...
         // (the last word 0x1366a992 was rounded up because the next one is 0xcbb9ac40 -- first bit is one 0xc..)
         // 256 32bit words for the mantissa -- about 2464 valid decimal digits
         };
         // above value was calculated using Big<1,400> type on a 32bit platform
         // and then the first 256 words were taken,
         // the calculating was made by using LnSurrounding1(2) method
         // which took 4035 iterations
         // (the result was compared with ln(2) taken from http://ja0hxv.calico.jp/pai/estart.html)
         // (TTMATH_BUILTIN_VARIABLES_SIZE on 32bit platform should have the value 256,
         // and on 64bit platform value 128 (256/2=128))
         mantissa.SetFromTable(temp_table, sizeof(temp_table) / sizeof(int));
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT);
         info = 0;
     }
References ttmath::UInt< value_size >::SetFromTable(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Ln().
SetMax()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetMax ()
this method sets the maximum value which can be held in this type
Definition at line 618 of file ttmathbig.h.
     {
         info = 0;
         mantissa.SetMax();
         exponent.SetMax();
         // we don't have to use 'Standardizing()' because the last bit from
         // the mantissa is set
     }
References ttmath::Int< value_size >::SetMax(), and ttmath::UInt< value_size >::SetMax().
SetMin()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetMin ()
this method sets the minimum value which can be held in this type
Definition at line 632 of file ttmathbig.h.
     {
         info = 0;
         mantissa.SetMax();
         exponent.SetMax();
         SetSign();
         // we don't have to use 'Standardizing()' because the last bit from
         // the mantissa is set
     }
References ttmath::Int< value_size >::SetMax(), ttmath::UInt< value_size >::SetMax(), and ttmath::Big< exp, man >::SetSign().
SetNan()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetNan ()
this method sets NaN flag (Not a Number) when this flag is set that means there is no a valid number
Definition at line 296 of file ttmathbig.h.
     {
         SetInfoBit(TTMATH_BIG_NAN);
     }
References ttmath::Big< exp, man >::SetInfoBit(), and TTMATH_BIG_NAN.
Referenced by ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::FromBig(), ttmath::Big< exp, man >::FromDouble(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowFrac(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::SetZeroNan(), and ttmath::Big< exp, man >::Sqrt().
SetOne()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetOne ()
this method sets one
Definition at line 271 of file ttmathbig.h.
     {
         info = 0;
         mantissa.SetZero();
         mantissa.table[man-1] = TTMATH_UINT_HIGHEST_BIT;
         exponent = -sint(man * TTMATH_BITS_PER_UINT - 1);
         // don't have to Standardize() - the last bit from mantissa is set
     }
References ttmath::UInt< value_size >::SetZero(), ttmath::UInt< value_size >::table, TTMATH_BITS_PER_UINT, and TTMATH_UINT_HIGHEST_BIT.
Referenced by ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::PowInt(), ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::Set05(), and ttmath::Big< exp, man >::Sgn().
SetPi()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetPi ()
this method sets the value of pi
Definition at line 393 of file ttmathbig.h.
     {
         // IMPROVE ME
         // give some compiler-time warning when the size of mantissa is greater than the builtin size of the mantissa pi
         SetMantissaPi();
         info = 0;
         exponent = -sint(man)*sint(TTMATH_BITS_PER_UINT) + 2;
     }
References TTMATH_BITS_PER_UINT.
SetSign()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetSign ()
this method sets the sign
samples
-1 -> -1
2 -> -2
we do not check whether there is a zero or not, if you're using this method you must be sure that the value is (or will be afterwards) different from zero
Definition at line 726 of file ttmathbig.h.
     {
         SetInfoBit(TTMATH_BIG_SIGN);
     }
References ttmath::Big< exp, man >::SetInfoBit(), and TTMATH_BIG_SIGN.
Referenced by ttmath::Big< exp, man >::FromInt(), ttmath::Big< exp, man >::MulInt(), ttmath::Big< exp, man >::SetMin(), and ttmath::Big< exp, man >::Sgn().
SetZero()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetZero ()
this method sets zero
Definition at line 256 of file ttmathbig.h.
     {
         info = TTMATH_BIG_ZERO;
         exponent.SetZero();
         mantissa.SetZero();
         /*
             we don't have to compensate zero
         */
     }
References ttmath::UInt< value_size >::SetZero(), and TTMATH_BIG_ZERO.
Referenced by ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::FromDouble(), ttmath::Big< exp, man >::FromUInt(), ttmath::Big< exp, man >::Log(), ttmath::Big< exp, man >::MulInt(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::RemainFraction(), ttmath::Big< exp, man >::SetZeroNan(), ttmath::Big< exp, man >::Sgn(), and ttmath::Big< exp, man >::SkipFraction().
SetZeroNan()
template<uint exp, uint man> void ttmath::Big< exp, man >::SetZeroNan ()
this method sets NaN flag (Not a Number) also clears the mantissa and exponent (similarly as it would be a zero value)
Definition at line 306 of file ttmathbig.h.
     {
         SetZero();
         SetNan();
     }
References ttmath::Big< exp, man >::SetNan(), and ttmath::Big< exp, man >::SetZero().
Referenced by ttmath::Big< exp, man >::Big().
Sgn()
template<uint exp, uint man> void ttmath::Big< exp, man >::Sgn ()
this method remains the 'sign' of the value
samples
-2 = -1
0 = 0
10 = 1
Definition at line 696 of file ttmathbig.h.
     {
         // we have to check the NaN flag, because the next SetOne() method would clear it
         if( IsNan() )
             return;
         if( IsSign() )
         {
             SetOne();
             SetSign();
         }
         else
         if( IsZero() )
             SetZero(); // !! is nedeed here?
         else
             SetOne();
     }
References ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::SetOne(), ttmath::Big< exp, man >::SetSign(), and ttmath::Big< exp, man >::SetZero().
SkipFraction()
template<uint exp, uint man> void ttmath::Big< exp, man >::SkipFraction ()
this method makes an integer value by skipping any fractions
samples:
10.7 will be 10
12.1 – 12
-20.2 – 20
-20.9 – 20
-0.7 – 0
0.8 – 0
Definition at line 5808 of file ttmathbig.h.
     {
         if( IsNan() || IsZero() )
             return;
         if( !exponent.IsSign() )
             // exponent >=0 -- the value don't have any fractions
             return;
         if( exponent <= -sint(man*TTMATH_BITS_PER_UINT) )
         {
             // the value is from (-1,1), we return zero
             SetZero();
             return;
         }
         // exponent is in range (-man*TTMATH_BITS_PER_UINT, 0)
         sint e = exponent.ToInt();
         mantissa.ClearFirstBits( -e );
         // we don't have to standardize 'Standardizing()' the value because
         // there's at least one bit in the mantissa
         // (the highest bit which we didn't touch)
     }
References ttmath::UInt< value_size >::ClearFirstBits(), ttmath::Big< exp, man >::IsNan(), ttmath::Int< value_size >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::SetZero(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
Referenced by ttmath::Big< exp, man >::Round().
SmallerWithoutSignThan()
template<uint exp, uint man> bool ttmath::Big< exp, man >::SmallerWithoutSignThan (const Big< exp, man > & ss2) const
methods for comparing
this method performs the formula 'abs(this) < abs(ss2)' and returns the result
(in other words it treats 'this' and 'ss2' as values without a sign) we don't check the NaN flag
Definition at line 5419 of file ttmathbig.h.
     {
         if( IsZero() )
         {
             if( ss2.IsZero() )
                 // we've got two zeroes
                 return false;
             else
                 // this==0 and ss2!=0
                 return true;
         }
         if( ss2.IsZero() )
         {
             // this!=0 and ss2==0
             return false;
         }
         // we're using the fact that all bits in mantissa are pushed
         // into the left side -- Standardizing()
         if( exponent == ss2.exponent )
             return mantissa < ss2.mantissa;
     return exponent < ss2.exponent;
     }
References ttmath::Big< exp, man >::IsZero().
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), and ttmath::Big< exp, man >::BitXor().
Sqrt()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Sqrt ()
this function calculates the square root e.g. let this=9 then this.Sqrt() gives 3
return:
0 - ok
1 - carry
2 - improper argument (this<0 or NaN)
Definition at line 1835 of file ttmathbig.h.
     {
         if( IsNan() || IsSign() )
         {
             SetNan();
             return 2;
         }
         if( IsZero() )
             return 0;
         Big<exp, man> old(*this);
         Big<exp, man> ln;
         uint c = 0;
         // we're using the formula: sqrt(x) = e ^ (ln(x) / 2)
         c += ln.Ln(*this);
         c += ln.exponent.SubOne(); // ln = ln / 2
         c += Exp(ln);
         // above formula doesn't give accurate results for some integers
         // e.g. Sqrt(81) would not be 9 but a value very closed to 9
         // we're rounding the result, calculating result*result and comparing
         // with the old value, if they are equal then the result is an integer too
         if( !c && old.IsInteger() && !IsInteger() )
         {
             Big<exp, man> temp(*this);
             c += temp.Round();
             Big<exp, man> temp2(temp);
             c += temp.Mul(temp2);
             if( temp == old )
                 *this = temp2;
         }
     return CheckCarry(c);
     }
References ttmath::Big< exp, man >::CheckCarry(), ttmath::Big< exp, man >::Exp(), ttmath::Big< exp, man >::IsInteger(), ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Big< exp, man >::Ln(), ttmath::Big< exp, man >::Mul(), ttmath::Big< exp, man >::Round(), ttmath::Big< exp, man >::SetNan(), and ttmath::Int< value_size >::SubOne().
Standardizing()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Standardizing ()
this method moves all bits from mantissa into its left side (suitably changes the exponent) or if the mantissa is zero it sets the exponent to zero as well (and clears the sign bit and sets the zero bit)
it can return a carry the carry will be when we don't have enough space in the exponent
you don't have to use this method if you don't change the mantissa and exponent directly
Definition at line 173 of file ttmathbig.h.
     {
         if( mantissa.IsTheHighestBitSet() )
         {
             ClearInfoBit(TTMATH_BIG_ZERO);
             return 0;
         }
         if( CorrectZero() )
             return 0;
         uint comp = mantissa.CompensationToLeft();
     return exponent.Sub( comp );
     }
References ttmath::Big< exp, man >::ClearInfoBit(), ttmath::UInt< value_size >::CompensationToLeft(), ttmath::UInt< value_size >::IsTheHighestBitSet(), ttmath::Int< value_size >::Sub(), and TTMATH_BIG_ZERO.
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::FromDouble(), ttmath::Big< exp, man >::FromUInt(), ttmath::Big< exp, man >::MulUInt(), and ttmath::Big< exp, man >::RemainFraction().
Sub()
template<uint exp, uint man> uint ttmath::Big< exp, man >::Sub (const Big< exp, man > & ss2, bool round = true)
Subtraction this = this - ss2
it returns carry if the result is too big
Definition at line 986 of file ttmathbig.h.
     {
         return Add(ss2, round, false);
     }
References ttmath::Big< exp, man >::Add().
Referenced by ttmath::Big< exp, man >::Round().
Swap()
template<uint exp, uint man> void ttmath::Big< exp, man >::Swap (Big< exp, man > & ss2)
this method swappes this for an argument
Definition at line 316 of file ttmathbig.h.
     {
         unsigned char info_temp = info;
         info = ss2.info;
         ss2.info = info_temp;
         exponent.Swap(ss2.exponent);
         mantissa.Swap(ss2.mantissa);
     }
References ttmath::UInt< value_size >::Swap().
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), and ttmath::Big< exp, man >::BitXor().
ToDouble() [1/2]
template<uint exp, uint man> double ttmath::Big< exp, man >::ToDouble () const
this method converts from this class into the 'double'
if the value is too big: 'result' will be +/-infinity (depending on the sign)
if the value is too small: 'result' will be 0
Definition at line 2848 of file ttmathbig.h.
     {
     double result;
         ToDouble(result);
     return result;
     }
Referenced by ttmath::Big< exp, man >::ToFloat().
ToDouble() [2/2]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToDouble (double & result) const
this method converts from this class into the 'double'
if the value is too big:
'result' will be +/-infinity (depending on the sign)
and the method returns 1
if the value is too small:
'result' will be 0
and the method returns 1
Definition at line 2979 of file ttmathbig.h.
     {
         if( IsZero() )
         {
             result = 0.0;
             return 0;
         }
         if( IsNan() )
         {
             result = ToDouble_SetDouble( false, 2047, 0, false, true);
         return 0;
         }
         sint e_correction = sint(man*TTMATH_BITS_PER_UINT) - 1;
         if( exponent >= 1024 - e_correction )
         {
             // +/- infinity
             result = ToDouble_SetDouble( IsSign(), 2047, 0, true);
         return 1;
         }
         else
         if( exponent <= -1023 - 52 - e_correction )
         {
             // too small value - we assume that there'll be a zero
             result = 0;
             // and return a carry
         return 1;
         }
         sint e = exponent.ToInt() + e_correction;
         if( e <= -1023 )
         {
             // -1023-52 < e <= -1023  (unnormalized value)
             result = ToDouble_SetDouble( IsSign(), 0, -(e + 1023));
         }
         else
         {
             // -1023 < e < 1024
             result = ToDouble_SetDouble( IsSign(), e + 1023, -1);
         }
     return 0;
     }
References ttmath::Big< exp, man >::IsNan(), ttmath::Big< exp, man >::IsSign(), ttmath::Big< exp, man >::IsZero(), ttmath::Int< value_size >::ToInt(), and TTMATH_BITS_PER_UINT.
ToFloat() [1/2]
template<uint exp, uint man> float ttmath::Big< exp, man >::ToFloat () const
this method converts from this class into the 'float'
if the value is too big: 'result' will be +/-infinity (depending on the sign)
if the value is too small: 'result' will be 0
Definition at line 2920 of file ttmathbig.h.
     {
     float result;
         ToFloat(result);
     return result;
     }
ToFloat() [2/2]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToFloat (float & result) const
this method converts from this class into the 'float'
if the value is too big:
'result' will be +/-infinity (depending on the sign)
and the method returns 1
if the value is too small:
'result' will be 0
and the method returns 1
Definition at line 2941 of file ttmathbig.h.
     {
     double result_double;
         uint c = ToDouble(result_double);
         result = float(result_double);
         if( result == -0.0f )
             result = 0.0f;
         if( c )
             return 1;
         // although the result_double can have a correct value
         // but after converting to float there can be infinity
         if( IsInf(result) )
             return 1;
         if( result == 0.0f && result_double != 0.0 )
             // result_double was too small for float
             return 1;
     return 0;
     }
References ttmath::Big< exp, man >::ToDouble().
ToInt() [1/7]
template<uint exp, uint man> sint ttmath::Big< exp, man >::ToInt () const
this method converts 'this' into sint
Definition at line 2366 of file ttmathbig.h.
     {
     sint result;
         ToInt(result);
     return result;
     }
Referenced by ttmath::Big< exp, man >::ToInt().
ToInt() [2/7]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToInt (uint & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2381 of file ttmathbig.h.
     {
         return ToUInt(result);
     }
References ttmath::Big< exp, man >::ToUInt().
ToInt() [3/7]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToInt (sint & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2392 of file ttmathbig.h.
     {
     uint result_uint;
         uint c = ToUIntOrInt(result_uint);
         result = sint(result_uint);
         if( c )
             return 1;
         uint mask = 0;
         if( IsSign() )
         {
             mask = TTMATH_UINT_MAX_VALUE;
             result = -result;
         }
     return ((result & TTMATH_UINT_HIGHEST_BIT) == (mask & TTMATH_UINT_HIGHEST_BIT)) ? 0 : 1;
     }
References ttmath::Big< exp, man >::IsSign(), TTMATH_UINT_HIGHEST_BIT, and TTMATH_UINT_MAX_VALUE.
ToInt() [4/7]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::ToInt (UInt< int_size > & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2504 of file ttmathbig.h.
     {
         return ToUInt(result);
     }
References ttmath::Big< exp, man >::ToUInt().
ToInt() [5/7]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::ToInt (Int< int_size > & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2516 of file ttmathbig.h.
     {
         uint c = ToUIntOrInt(result);
         if( c )
             return 1;
         uint mask = 0;
         if( IsSign() )
         {
             result.ChangeSign();
             mask = TTMATH_UINT_MAX_VALUE;
         }
     return ((result.table[int_size-1] & TTMATH_UINT_HIGHEST_BIT) == (mask & TTMATH_UINT_HIGHEST_BIT))? 0 : 1;
     }
References ttmath::Int< value_size >::ChangeSign(), ttmath::Big< exp, man >::IsSign(), ttmath::UInt< value_size >::table, TTMATH_UINT_HIGHEST_BIT, and TTMATH_UINT_MAX_VALUE.
ToInt() [6/7]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToInt (unsigned int & result) const
this method converts 'this' into 'result' (32 bit unsigned integer) this method is created only on a 64bit platform*** if the value is too big this method returns a carry (1)
Definition at line 3399 of file ttmathbig.h.
     {
         return ToUInt(result);
     }
References ttmath::Big< exp, man >::ToUInt().
ToInt() [7/7]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToInt (signed int & result) const
this method converts 'this' into 'result' (32 bit signed integer) this method is created only on a 64bit platform*** if the value is too big this method returns a carry (1)
Definition at line 3410 of file ttmathbig.h.
     {
     sint result_sint;
         uint c = ToInt(result_sint);
         result = (signed int)result_sint;
         if( c || result_sint != sint(result) )
             return 1;
     return 0;
     }
References ttmath::Big< exp, man >::ToInt().
ToString() [1/6]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToString (std::string & result, uint base = 10, bool scient = false, sint scient_from = 15, sint round = -1, bool trim_zeroes = true, char comma = '.') const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
return value:
0 - ok and 'result' will be an object of type std::string (or std::wstring) which holds the value
1 - if there is a carry (it shoudn't be in a normal situation - if it is that means there is somewhere an error in the library)
Definition at line 3715 of file ttmathbig.h.
     {
         Conv conv;
         conv.base         = base;
         conv.scient       = scient;
         conv.scient_from  = scient_from;
         conv.round        = round;
         conv.trim_zeroes  = trim_zeroes;
         conv.comma        = static_cast<uint>(comma);
     return ToStringBase<std::string, char>(result, conv);
     }
References ttmath::Conv::base, ttmath::Conv::comma, ttmath::Conv::round, ttmath::Conv::scient, ttmath::Conv::scient_from, and ttmath::Conv::trim_zeroes.
Referenced by ttmath::Big< exp, man >::ToString().
ToString() [2/6]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToString (std::string & result, const Conv & conv) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3740 of file ttmathbig.h.
     {
         return ToStringBase<std::string, char>(result, conv);
     }
ToString() [3/6]
template<uint exp, uint man> std::string ttmath::Big< exp, man >::ToString (const Conv & conv) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3750 of file ttmathbig.h.
     {
         std::string result;
         ToStringBase<std::string, char>(result, conv);
     return result;
     }
ToString() [4/6]
template<uint exp, uint man> std::string ttmath::Big< exp, man >::ToString (uint base = 10) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3763 of file ttmathbig.h.
     {
         Conv conv;
         conv.base = base;
     return ToString(conv);
     }
References ttmath::Conv::base, and ttmath::Big< exp, man >::ToString().
ToString() [5/6]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToString (std::wstring & result, uint base = 10, bool scient = false, sint scient_from = 15, sint round = -1, bool trim_zeroes = true, wchar_t comma = '.') const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3780 of file ttmathbig.h.
     {
         Conv conv;
         conv.base         = base;
         conv.scient       = scient;
         conv.scient_from  = scient_from;
         conv.round        = round;
         conv.trim_zeroes  = trim_zeroes;
         conv.comma        = static_cast<uint>(comma);
     return ToStringBase<std::wstring, wchar_t>(result, conv);
     }
References ttmath::Conv::base, ttmath::Conv::comma, ttmath::Conv::round, ttmath::Conv::scient, ttmath::Conv::scient_from, and ttmath::Conv::trim_zeroes.
ToString() [6/6]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToString (std::wstring & result, const Conv & conv) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3805 of file ttmathbig.h.
     {
         return ToStringBase<std::wstring, wchar_t>(result, conv);
     }
ToUInt() [1/4]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToUInt () const
this method converts 'this' into uint
Definition at line 2336 of file ttmathbig.h.
     {
     uint result;
         ToUInt(result);
     return result;
     }
Referenced by ttmath::Big< exp, man >::ToInt(), and ttmath::Big< exp, man >::ToUInt().
ToUInt() [2/4]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToUInt (uint & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2351 of file ttmathbig.h.
     {
         if( ToUIntOrInt(result) )
             return 1;
         if( IsSign() )
             return 1;
     return 0;
     }
References ttmath::Big< exp, man >::IsSign().
ToUInt() [3/4]
template<uint exp, uint man> template<uint int_size> uint ttmath::Big< exp, man >::ToUInt (UInt< int_size > & result) const
this method converts 'this' into 'result'
if the value is too big this method returns a carry (1)
Definition at line 2484 of file ttmathbig.h.
     {
         uint c = ToUIntOrInt(result);
         if( c )
             return 1;
         if( IsSign() )
             return 1;
     return 0;
     }
References ttmath::Big< exp, man >::IsSign().
ToUInt() [4/4]
template<uint exp, uint man> uint ttmath::Big< exp, man >::ToUInt (unsigned int & result) const
this method converts 'this' into 'result' (32 bit unsigned integer) this method is created only on a 64bit platform*** if the value is too big this method returns a carry (1)
Definition at line 3380 of file ttmathbig.h.
     {
     uint result_uint;
         uint c = ToUInt(result_uint);
         result = (unsigned int)result_uint;
         if( c || result_uint != uint(result) )
             return 1;
     return 0;
     }
References ttmath::Big< exp, man >::ToUInt().
ToWString() [1/2]
template<uint exp, uint man> std::wstring ttmath::Big< exp, man >::ToWString (const Conv & conv) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3815 of file ttmathbig.h.
     {
         std::wstring result;
         ToStringBase<std::wstring, wchar_t>(result, conv);
     return result;
     }
Referenced by ttmath::Big< exp, man >::ToWString().
ToWString() [2/2]
template<uint exp, uint man> std::wstring ttmath::Big< exp, man >::ToWString (uint base = 10) const
a method for converting into a string struct Conv is defined in ttmathtypes.h, look there for more information about parameters
Definition at line 3828 of file ttmathbig.h.
     {
         Conv conv;
         conv.base = base;
     return ToWString(conv);
     }
References ttmath::Conv::base, and ttmath::Big< exp, man >::ToWString().
Friends And Related Function Documentation
Big< exp-1, man >
template<uint exp, uint man> friend class Big< exp-1, man > friend
in the method 'ToString_CreateNewMantissaAndExponent()' we're using type 'Big<exp+1,man>' and we should have the ability to use some necessary methods from that class (methods which are private here)
Definition at line 3917 of file ttmathbig.h.
operator<< [1/2]
template<uint exp, uint man> std::ostream& operator<< (std::ostream & s, const Big< exp, man > & l) friend
output to standard streams
Definition at line 5989 of file ttmathbig.h.
     {
         return OutputToStream<std::ostream, std::string>(s, l);
     }
operator<< [2/2]
template<uint exp, uint man> std::wostream& operator<< (std::wostream & s, const Big< exp, man > & l) friend
output to standard streams
Definition at line 6000 of file ttmathbig.h.
     {
         return OutputToStream<std::wostream, std::wstring>(s, l);
     }
operator>> [1/2]
template<uint exp, uint man> std::istream& operator>> (std::istream & s, Big< exp, man > & l) friend
input from standard streams
Definition at line 6088 of file ttmathbig.h.
     {
         return InputFromStream<std::istream, std::string, char>(s, l);
     }
operator>> [2/2]
template<uint exp, uint man> std::wistream& operator>> (std::wistream & s, Big< exp, man > & l) friend
input from standard streams
Definition at line 6099 of file ttmathbig.h.
     {
         return InputFromStream<std::wistream, std::wstring, wchar_t>(s, l);
     }
The documentation for this class was generated from the following file:
ttmathbig.h