TTMath: ttmath::Misc Class Reference
ttmath::Misc Class Reference
#include <ttmathmisc.h>
Static Public Member Functions
static void AssignString (std::string &result, const char *str)
static void AssignString (std::wstring &result, const char *str)
static void AssignString (std::wstring &result, const std::string &str)
static void AssignString (std::string &result, const wchar_t *str)
static void AssignString (std::string &result, const std::wstring &str)
static void AddString (std::string &result, const char *str)
static void AddString (std::wstring &result, const char *str)
template<class char_type >
static void SkipWhiteCharacters (const char_type *&c)
static uint CharToDigit (uint c)
static sint CharToDigit (uint c, uint base)
static uint DigitToChar (uint digit)
Detailed Description
some helpful functions
Definition at line 57 of file ttmathmisc.h.
Member Function Documentation
AddString() [1/2]
static void ttmath::Misc::AddString (std::string & result, const char * str) static
result += str
Definition at line 135 of file ttmathmisc.h.
 {
     result += str;
 }
AddString() [2/2]
static void ttmath::Misc::AddString (std::wstring & result, const char * str) static
result += str
Definition at line 146 of file ttmathmisc.h.
 {
     for( ; *str ; ++str )
         result += *str;
 }
AssignString() [1/5]
static void ttmath::Misc::AssignString (std::string & result, const char * str) static
result = str
Definition at line 72 of file ttmathmisc.h.
 {
     result = str;
 }
Referenced by ttmath::Objects::Add(), AssignString(), ttmath::Objects::Delete(), ttmath::Objects::EditName(), ttmath::Objects::EditValue(), ttmath::Objects::GetValue(), ttmath::Objects::GetValueAndParam(), ttmath::Parser< ValueType >::InsertFunctionToTable(), ttmath::Parser< ValueType >::InsertVariableToTable(), ttmath::Objects::IsDefined(), and ttmath::Parser< ValueType >::Parse().
AssignString() [2/5]
static void ttmath::Misc::AssignString (std::wstring & result, const char * str) static
result = str
Definition at line 83 of file ttmathmisc.h.
 {
     result.clear();
     for( ; *str ; ++str )
         result += *str;
 }
AssignString() [3/5]
static void ttmath::Misc::AssignString (std::wstring & result, const std::string & str) static
result = str
Definition at line 95 of file ttmathmisc.h.
 {
     return AssignString(result, str.c_str());
 }
References AssignString().
AssignString() [4/5]
static void ttmath::Misc::AssignString (std::string & result, const wchar_t * str) static
result = str
Definition at line 104 of file ttmathmisc.h.
 {
     result.clear();
     for( ; *str ; ++str )
         result += static_cast<char>(*str);
 }
AssignString() [5/5]
static void ttmath::Misc::AssignString (std::string & result, const std::wstring & str) static
result = str
Definition at line 116 of file ttmathmisc.h.
 {
     return AssignString(result, str.c_str());
 }
References AssignString().
CharToDigit() [1/2]
static uint ttmath::Misc::CharToDigit (uint c) static
this static method converts one character into its value
for example:
1 -> 1
8 -> 8
A -> 10
f -> 15
this method don't check whether c is correct or not
Definition at line 181 of file ttmathmisc.h.
 {
     if(c>='0' && c<='9')
         return c-'0';
     if(c>='a' && c<='z')
         return c-'a'+10;
 return c-'A'+10;
 }
Referenced by ttmath::Parser< ValueType >::ValueStarts().
CharToDigit() [2/2]
static sint ttmath::Misc::CharToDigit (uint c, uint base) static
this method changes a character 'c' into its value (if there can't be a correct value it returns -1)
for example:
c=2, base=10 -> function returns 2
c=A, base=10 -> function returns -1
c=A, base=16 -> function returns 10
Definition at line 202 of file ttmathmisc.h.
 {
     if( c>='0' && c<='9' )
         c=c-'0';
     else
     if( c>='a' && c<='z' )
         c=c-'a'+10;
     else
     if( c>='A' && c<='Z' )
         c=c-'A'+10;
     else
         return -1;
     if( c >= base )
         return -1;
 return sint(c);
 }
DigitToChar()
static uint ttmath::Misc::DigitToChar (uint digit) static
this method converts a digit into a char digit should be from <0,F> (we don't have to get a base)
for example:
1 -> 1
8 -> 8
10 -> A
15 -> F
Definition at line 236 of file ttmathmisc.h.
 {
     if( digit < 10 )
         return digit + '0';
 return digit - 10 + 'A';
 }
Referenced by ttmath::UInt< man >::ToStringBase().
The documentation for this class was generated from the following file:
ttmathmisc.h