TTMath: ttmath::Objects Class Reference
ttmath::Objects Class Reference
#include <ttmathobjects.h>
Data Structures
struct Item
Public Types
typedef std::map< std::string, Item > Table
typedef Table::iterator Iterator
typedef Table::const_iterator CIterator
Public Member Functions
bool IsDefined (const std::string &name)
bool IsDefined (const std::wstring &name)
ErrorCode Add (const std::string &name, const std::string &value, int param=0)
ErrorCode Add (const std::wstring &name, const std::wstring &value, int param=0)
bool Empty () const
void Clear ()
CIterator Begin () const
CIterator End () const
ErrorCode EditValue (const std::string &name, const std::string &value, int param=0)
ErrorCode EditValue (const std::wstring &name, const std::wstring &value, int param=0)
ErrorCode EditName (const std::string &old_name, const std::string &new_name)
ErrorCode EditName (const std::wstring &old_name, const std::wstring &new_name)
ErrorCode Delete (const std::string &name)
ErrorCode Delete (const std::wstring &name)
ErrorCode GetValue (const std::string &name, std::string &value) const
ErrorCode GetValue (const std::wstring &name, std::wstring &value)
ErrorCode GetValue (const std::string &name, const char **value) const
ErrorCode GetValue (const std::wstring &name, const char **value)
ErrorCode GetValueAndParam (const std::string &name, std::string &value, int *param) const
ErrorCode GetValueAndParam (const std::wstring &name, std::wstring &value, int *param)
ErrorCode GetValueAndParam (const std::string &name, const char **value, int *param) const
ErrorCode GetValueAndParam (const std::wstring &name, const char **value, int *param)
Table * GetTable ()
Static Public Member Functions
static bool CorrectCharacter (int c, bool can_be_digit)
template<class string_type >
static bool IsNameCorrect (const string_type &name)
Detailed Description
objects of this class are used with the mathematical parser they hold variables or functions defined by a user
each object has its own table in which we're keeping variables or functions
Definition at line 65 of file ttmathobjects.h.
Member Function Documentation
Add() [1/2]
ErrorCode ttmath::Objects::Add (const std::string & name, const std::string & value, int param = 0)
this method adds one object (variable of function) into the table
Definition at line 175 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Iterator i = table.find(name);
         if( i != table.end() )
             // we have this object in our table
             return err_object_exists;
         table.insert( std::make_pair(name, Item(value, param)) );
     return err_ok;
     }
References IsNameCorrect().
Referenced by Add(), and EditName().
Add() [2/2]
ErrorCode ttmath::Objects::Add (const std::wstring & name, const std::wstring & value, int param = 0)
this method adds one object (variable of function) into the table
Definition at line 197 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
         Misc::AssignString(str_tmp2, value);
     return Add(str_tmp1, str_tmp2, param);
     }
References Add(), ttmath::Misc::AssignString(), and IsNameCorrect().
Begin()
CIterator ttmath::Objects::Begin () const
this method returns 'const_iterator' on the first item on the table
Definition at line 234 of file ttmathobjects.h.
     {
         return table.begin();
     }
Clear()
void ttmath::Objects::Clear ()
this method clears the table
Definition at line 225 of file ttmathobjects.h.
     {
         return table.clear();
     }
CorrectCharacter()
static bool ttmath::Objects::CorrectCharacter (int c, bool can_be_digit) static
this method returns true if a character 'c' is a character which can be in a name
if 'can_be_digit' is true that means when the 'c' is a digit this method returns true otherwise it returns false
Definition at line 102 of file ttmathobjects.h.
     {
         if( (c>='a' && c<='z') || (c>='A' && c<='Z') )
             return true;
         if( can_be_digit && ((c>='0' && c<='9') || c=='_') )
             return true;
     return false;
     }
Referenced by IsNameCorrect().
Delete() [1/2]
ErrorCode ttmath::Objects::Delete (const std::string & name)
this method deletes an object
Definition at line 349 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Iterator i = table.find(name);
         if( i == table.end() )
             return err_unknown_object;
         table.erase( i );
     return err_ok;
     }
References IsNameCorrect().
Referenced by Delete().
Delete() [2/2]
ErrorCode ttmath::Objects::Delete (const std::wstring & name)
this method deletes an object
Definition at line 371 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
     return Delete(str_tmp1);
     }
References ttmath::Misc::AssignString(), Delete(), and IsNameCorrect().
EditName() [1/2]
ErrorCode ttmath::Objects::EditName (const std::string & old_name, const std::string & new_name)
this method changes the name of a specific object
Definition at line 295 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(old_name) || !IsNameCorrect(new_name) )
             return err_incorrect_name;
         Iterator old_i = table.find(old_name);
         if( old_i == table.end() )
             return err_unknown_object;
         if( old_name == new_name )
             // the new name is the same as the old one
             // we treat it as a normal situation
             return err_ok;
         ErrorCode err = Add(new_name, old_i->second.value, old_i->second.param);
         if( err == err_ok )
         {
             old_i = table.find(old_name);
             TTMATH_ASSERT( old_i != table.end() )
             table.erase(old_i);
         }
     return err;
     }
References Add(), and IsNameCorrect().
Referenced by EditName().
EditName() [2/2]
ErrorCode ttmath::Objects::EditName (const std::wstring & old_name, const std::wstring & new_name)
this method changes the name of a specific object
Definition at line 330 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(old_name) || !IsNameCorrect(new_name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, old_name);
         Misc::AssignString(str_tmp2, new_name);
     return EditName(str_tmp1, str_tmp2);
     }
References ttmath::Misc::AssignString(), EditName(), and IsNameCorrect().
EditValue() [1/2]
ErrorCode ttmath::Objects::EditValue (const std::string & name, const std::string & value, int param = 0)
this method changes the value and the number of parameters for a specific object
Definition at line 253 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Iterator i = table.find(name);
         if( i == table.end() )
             return err_unknown_object;
         i->second.value = value;
         i->second.param = param;
     return err_ok;
     }
References IsNameCorrect().
Referenced by EditValue().
EditValue() [2/2]
ErrorCode ttmath::Objects::EditValue (const std::wstring & name, const std::wstring & value, int param = 0)
this method changes the value and the number of parameters for a specific object
Definition at line 276 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
         Misc::AssignString(str_tmp2, value);
     return EditValue(str_tmp1, str_tmp2, param);
     }
References ttmath::Misc::AssignString(), EditValue(), and IsNameCorrect().
Empty()
bool ttmath::Objects::Empty () const
this method returns 'true' if the table is empty
Definition at line 216 of file ttmathobjects.h.
     {
         return table.empty();
     }
End()
CIterator ttmath::Objects::End () const
this method returns 'const_iterator' pointing at the space after last item (returns table.end())
Definition at line 244 of file ttmathobjects.h.
     {
         return table.end();
     }
GetTable()
Table* ttmath::Objects::GetTable ()
this method returns a pointer into the table
Definition at line 576 of file ttmathobjects.h.
     {
         return &table;
     }
GetValue() [1/4]
ErrorCode ttmath::Objects::GetValue (const std::string & name, std::string & value) const
this method gets the value of a specific object
Definition at line 389 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         CIterator i = table.find(name);
         if( i == table.end() )
         {
             value.clear();
             return err_unknown_object;
         }
         value = i->second.value;
     return err_ok;
     }
References IsNameCorrect().
Referenced by GetValue(), and ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable().
GetValue() [2/4]
ErrorCode ttmath::Objects::GetValue (const std::wstring & name, std::wstring & value)
this method gets the value of a specific object
Definition at line 413 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
         ErrorCode err = GetValue(str_tmp1, str_tmp2);
         Misc::AssignString(value, str_tmp2);
     return err;
     }
References ttmath::Misc::AssignString(), GetValue(), and IsNameCorrect().
GetValue() [3/4]
ErrorCode ttmath::Objects::GetValue (const std::string & name, const char ** value) const
this method gets the value of a specific object (this version is used for not copying the whole string)
Definition at line 434 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         CIterator i = table.find(name);
         if( i == table.end() )
         {
             *value = 0;
             return err_unknown_object;
         }
         *value = i->second.value.c_str();
     return err_ok;
     }
References IsNameCorrect().
GetValue() [4/4]
ErrorCode ttmath::Objects::GetValue (const std::wstring & name, const char ** value)
this method gets the value of a specific object (this version is used for not copying the whole string)
Definition at line 459 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
     return GetValue(str_tmp1, value);
     }
References ttmath::Misc::AssignString(), GetValue(), and IsNameCorrect().
GetValueAndParam() [1/4]
ErrorCode ttmath::Objects::GetValueAndParam (const std::string & name, std::string & value, int * param) const
this method gets the value and the number of parameters of a specific object
Definition at line 478 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         CIterator i = table.find(name);
         if( i == table.end() )
         {
             value.clear();
             *param = 0;
             return err_unknown_object;
         }
         value = i->second.value;
         *param = i->second.param;
     return err_ok;
     }
References IsNameCorrect().
Referenced by GetValueAndParam(), and ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction().
GetValueAndParam() [2/4]
ErrorCode ttmath::Objects::GetValueAndParam (const std::wstring & name, std::wstring & value, int * param)
this method gets the value and the number of parameters of a specific object
Definition at line 505 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
         ErrorCode err = GetValueAndParam(str_tmp1, str_tmp2, param);
         Misc::AssignString(value, str_tmp2);
     return err;
     }
References ttmath::Misc::AssignString(), GetValueAndParam(), and IsNameCorrect().
GetValueAndParam() [3/4]
ErrorCode ttmath::Objects::GetValueAndParam (const std::string & name, const char ** value, int * param) const
this method sets the value and the number of parameters of a specific object (this version is used for not copying the whole string)
Definition at line 527 of file ttmathobjects.h.
     {
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         CIterator i = table.find(name);
         if( i == table.end() )
         {
             *value = 0;
             *param = 0;
             return err_unknown_object;
         }
         *value = i->second.value.c_str();
         *param = i->second.param;
     return err_ok;
     }
References IsNameCorrect().
GetValueAndParam() [4/4]
ErrorCode ttmath::Objects::GetValueAndParam (const std::wstring & name, const char ** value, int * param)
this method sets the value and the number of parameters of a specific object (this version is used for not copying the whole string but in fact we make one copying during AssignString())
Definition at line 557 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return err_incorrect_name;
         Misc::AssignString(str_tmp1, name);
     return GetValueAndParam(str_tmp1, value, param);
     }
References ttmath::Misc::AssignString(), GetValueAndParam(), and IsNameCorrect().
IsDefined() [1/2]
bool ttmath::Objects::IsDefined (const std::string & name)
this method returns true if such an object is defined (name exists)
Definition at line 139 of file ttmathobjects.h.
     {
         Iterator i = table.find(name);
         if( i != table.end() )
             // we have this object in our table
             return true;
     return false;
     }
Referenced by IsDefined().
IsDefined() [2/2]
bool ttmath::Objects::IsDefined (const std::wstring & name)
this method returns true if such an object is defined (name exists)
Definition at line 157 of file ttmathobjects.h.
     {
         // we should check whether the name (in wide characters) are correct
         // before calling AssignString() function
         if( !IsNameCorrect(name) )
             return false;
         Misc::AssignString(str_tmp1, name);
     return IsDefined(str_tmp1);
     }
References ttmath::Misc::AssignString(), IsDefined(), and IsNameCorrect().
IsNameCorrect()
template<class string_type > static bool ttmath::Objects::IsNameCorrect (const string_type & name) static
this method returns true if the name can be as a name of an object
Definition at line 118 of file ttmathobjects.h.
     {
         if( name.empty() )
             return false;
         if( !CorrectCharacter(name[0], false) )
             return false;
         typename string_type::const_iterator i = name.begin();
         for(++i ; i!=name.end() ; ++i)
             if( !CorrectCharacter(*i, true) )
                 return false;
     return true;
     }
References CorrectCharacter().
Referenced by Add(), Delete(), EditName(), EditValue(), GetValue(), GetValueAndParam(), and IsDefined().
The documentation for this class was generated from the following file:
ttmathobjects.h