TTMath: ttmath::Parser< ValueType > Class Template Reference
ttmath::Parser< ValueType > Class Template Reference
Mathematical parser.
#include <ttmathparser.h>
Data Structures
struct Item
class MatOperator
Public Member Functions
bool GetValueOfUserDefinedVariable (const std::string &variable_name, ValueType &result)
bool GetValueOfFunctionLocalVariable (const std::string &variable_name, ValueType &result)
virtual ValueType GetValueOfVariable (const std::string &variable_name)
Parser ()
Parser< ValueType > & operator= (const Parser< ValueType > &p)
virtual ~Parser ()
Parser (const Parser< ValueType > &p)
void SetBase (int b)
void SetDegRadGrad (int angle)
void SetStopObject (const volatile StopCalculating *ps)
void SetVariables (const Objects *pv)
void SetFunctions (const Objects *pf)
void SetGroup (int g)
void SetComma (int c, int c2=0)
void SetParamSep (int s)
ErrorCode Parse (const char *str)
ErrorCode Parse (const std::string &str)
ErrorCode Parse (const wchar_t *str)
ErrorCode Parse (const std::wstring &str)
bool Calculated ()
void InitCGamma ()
Data Fields
std::vector< Item > stack
Protected Types
typedef std::map< std::string, ValueType > FunctionLocalVariables
typedef void(Parser< ValueType >::* pfunction) (unsigned int pstack, int amount_of_arg, ValueType &result)
typedef void(ValueType::* pfunction_var) ()
typedef std::map< std::string, pfunction > FunctionsTable
typedef std::map< std::string, typename MatOperator::Type > OperatorsTable
typedef std::map< std::string, pfunction_var > VariablesTable
Protected Member Functions
void SkipWhiteCharacters ()
virtual void EnsurePlaceOnStack ()
void AddToStack (ValueType &value)
void AddToStack (typename Item::Type type, bool is_sign)
void AddToStack (typename MatOperator::Type mat_operator_type)
void AddToStack (typename Item::Type type, const std::string &name, bool is_function, bool is_sign)
void RecurrenceParsingVariablesOrFunction_CheckStopCondition (bool variable, const std::string &name)
void RecurrenceParsingVariablesOrFunction_AddName (bool variable, const std::string &name)
void RecurrenceParsingVariablesOrFunction_DeleteName (bool variable, const std::string &name)
ValueType RecurrenceParsingVariablesOrFunction (bool variable, const std::string &name, const char *new_string, FunctionLocalVariables *local_variables=0)
ValueType ConvertAngleToRad (const ValueType &input)
ValueType ConvertRadToAngle (const ValueType &input)
void Gamma (unsigned int index, int amount_of_args, ValueType &result)
void Factorial (unsigned int index, int amount_of_args, ValueType &result)
void Abs (unsigned int index, int amount_of_args, ValueType &result)
void Sin (unsigned int index, int amount_of_args, ValueType &result)
void Cos (unsigned int index, int amount_of_args, ValueType &result)
void Tan (unsigned int index, int amount_of_args, ValueType &result)
void Cot (unsigned int index, int amount_of_args, ValueType &result)
void Int (unsigned int index, int amount_of_args, ValueType &result)
void Round (unsigned int index, int amount_of_args, ValueType &result)
void Ln (unsigned int index, int amount_of_args, ValueType &result)
void Log (unsigned int index, int amount_of_args, ValueType &result)
void Exp (unsigned int index, int amount_of_args, ValueType &result)
void Max (unsigned int index, int amount_of_args, ValueType &result)
void Min (unsigned int index, int amount_of_args, ValueType &result)
void ASin (unsigned int index, int amount_of_args, ValueType &result)
void ACos (unsigned int index, int amount_of_args, ValueType &result)
void ATan (unsigned int index, int amount_of_args, ValueType &result)
void ACot (unsigned int index, int amount_of_args, ValueType &result)
void Sgn (unsigned int index, int amount_of_args, ValueType &result)
void Mod (unsigned int index, int amount_of_args, ValueType &result)
void If (unsigned int index, int amount_of_args, ValueType &result)
void Or (unsigned int index, int amount_of_args, ValueType &result)
void And (unsigned int index, int amount_of_args, ValueType &result)
void Not (unsigned int index, int amount_of_args, ValueType &result)
void DegToRad (unsigned int index, int amount_of_args, ValueType &result)
void RadToDeg (unsigned int index, int amount_of_args, ValueType &result)
void DegToDeg (unsigned int index, int amount_of_args, ValueType &result)
void GradToRad (unsigned int index, int amount_of_args, ValueType &result)
void RadToGrad (unsigned int index, int amount_of_args, ValueType &result)
void DegToGrad (unsigned int index, int amount_of_args, ValueType &result)
void GradToDeg (unsigned int index, int amount_of_args, ValueType &result)
void Ceil (unsigned int index, int amount_of_args, ValueType &result)
void Floor (unsigned int index, int amount_of_args, ValueType &result)
void Sqrt (unsigned int index, int amount_of_args, ValueType &result)
void Sinh (unsigned int index, int amount_of_args, ValueType &result)
void Cosh (unsigned int index, int amount_of_args, ValueType &result)
void Tanh (unsigned int index, int amount_of_args, ValueType &result)
void Coth (unsigned int index, int amount_of_args, ValueType &result)
void Root (unsigned int index, int amount_of_args, ValueType &result)
void ASinh (unsigned int index, int amount_of_args, ValueType &result)
void ACosh (unsigned int index, int amount_of_args, ValueType &result)
void ATanh (unsigned int index, int amount_of_args, ValueType &result)
void ACoth (unsigned int index, int amount_of_args, ValueType &result)
void BitAnd (unsigned int index, int amount_of_args, ValueType &result)
void BitOr (unsigned int index, int amount_of_args, ValueType &result)
void BitXor (unsigned int index, int amount_of_args, ValueType &result)
void Sum (unsigned int index, int amount_of_args, ValueType &result)
void Avg (unsigned int index, int amount_of_args, ValueType &result)
void Frac (unsigned int index, int amount_of_args, ValueType &result)
void Sprintf (char *buffer, int par)
bool GetValueOfUserDefinedFunction (const std::string &function_name, int amount_of_args, unsigned int index)
virtual void CallFunction (const std::string &function_name, int amount_of_args, unsigned int index)
void InsertFunctionToTable (const char *function_name, pfunction pf)
void InsertVariableToTable (const char *variable_name, pfunction_var pf)
void CreateFunctionsTable ()
void CreateVariablesTable ()
int ToLowerCase (int c)
virtual bool IsValidNameCharacter (int c)
virtual void ReadName (std::string &result)
virtual bool ReadVariableOrFunction (bool was_sign, bool was_minus_sign)
virtual void ReadValue (int reading_base, bool change_sign)
virtual bool ValueStarts (int character, int character_base)
virtual void CheckSignBeforeExpression (bool &was_sign, bool &was_minus_sign)
virtual bool ReadToken ()
virtual void ReadTokens ()
void InsertOperatorToTable (const char *name, typename MatOperator::Type type)
void CreateMathematicalOperatorsTable ()
virtual bool IsSubstring (const std::string &short_str, const std::string &long_str)
void ReadMathematicalOperator ()
void OperatorPercentage ()
virtual bool ReadOperator ()
virtual void ReadOperators ()
virtual void MakeStandardMathematicOperation (Item &item1, typename MatOperator::Type mat_operator, const Item &item2)
void RollUpStackWithOperatorsPriority ()
void RollUPStack ()
void HowManyParameters (unsigned int &size, unsigned int &index)
void RollingUpFinalBracket ()
virtual void CheckStackIntegrity ()
virtual void Parse ()
void NormalizeStack ()
Static Protected Member Functions
static void Error (ErrorCode code)
Protected Attributes
const int default_stack_size
unsigned int stack_index
ErrorCode error
const char * pstring
int base
int deg_rad_grad
const volatile StopCalculating * pstop_calculating
const Objects * puser_variables
const Objects * puser_functions
const FunctionLocalVariables * pfunction_local_variables
std::set< std::string > visited_variables
std::set< std::string > visited_functions
FunctionsTable functions_table
OperatorsTable operators_table
VariablesTable variables_table
CGamma< ValueType > cgamma
std::string wide_to_ansi
int group
int comma
int comma2
int param_sep
bool calculated
Detailed Description
template<class ValueType>
class ttmath::Parser< ValueType >
Mathematical parser.
let x will be an input string meaning an expression for converting:
x = [+|-]Value[operator[+|-]Value][operator[+|-]Value]... where: an operator can be: ^ (pow) (the heighest priority)
(mul) (or multiplication without an operator – short mul) / (div) (* and / have the same priority)
(add)
(sub) (+ and - have the same priority)
< (lower than) > (greater than) <= (lower or equal than) >= (greater or equal than) == (equal) != (not equal) (all above logical operators have the same priority)
&& (logical and)
|| (logical or) (the lowest priority)
short mul: if the second Value (Var below) is either a variable or function there might not be an operator between them, e.g. "[+|-]Value Var" is treated as "[+|-]Value * Var" and the multiplication has the same priority as a normal multiplication: 4x = 4 * x 2^3m = (2^3)* m 6h^3 = 6 * (h^3) 2sin(pi) = 2 * sin(pi) etc.
Value can be: constant e.g. 100, can be preceded by operators for changing the base (radix): [#|&]
- hex
& - bin sample: #10 = 16 &10 = 2 variable e.g. pi another expression between brackets e.g (x) function e.g. sin(x)
for example a correct input string can be: "1" "2.1234" "2,1234" (they are the same, by default we can either use a comma or a dot) "1 + 2" "(1 + 2) * 3" "pi" "sin(pi)" "(1+2)*(2+3)" "log(2;1234)" there's a semicolon here (not a comma), we use it in functions for separating parameters "1 < 2" (the result will be: 1) "4 < 3" (the result will be: 0) "2+x" (of course if the variable 'x' is defined) "4x+10" "#20+10" = 32 + 10 = 42 "10 ^ -&101" = 10 ^ -5 = 0.00001 "8 * -&10" = 8 * -2 = -16 etc.
we can also use a semicolon for separating any 'x' input strings for example: "1+2;4+5" the result will be on the stack as follows: stack[0].value=3 stack[1].value=9
Definition at line 138 of file ttmathparser.h.
Member Typedef Documentation
FunctionsTable
template<class ValueType> typedef std::map<std::string, pfunction> ttmath::Parser< ValueType >::FunctionsTable protected
table of mathematic functions
this map consists of: std::string - function's name pfunction - pointer to specific function
Definition at line 436 of file ttmathparser.h.
OperatorsTable
template<class ValueType> typedef std::map<std::string, typename MatOperator::Type> ttmath::Parser< ValueType >::OperatorsTable protected
table of mathematic operators
this map consists of: std::string - operators's name MatOperator::Type - type of the operator
Definition at line 447 of file ttmathparser.h.
pfunction
template<class ValueType> typedef void(Parser<ValueType>::* ttmath::Parser< ValueType >::pfunction) (unsigned int pstack, int amount_of_arg, ValueType &result) protected
pfunction is the type of pointer to a mathematic function
these mathematic functions are private members of this class, they are the wrappers for standard mathematics function
'pstack' is the pointer to the first argument on our stack 'amount_of_arg' tell us how many argument there are in our stack 'result' is the reference for result of function
Definition at line 420 of file ttmathparser.h.
pfunction_var
template<class ValueType> typedef void(ValueType::* ttmath::Parser< ValueType >::pfunction_var) () protected
pfunction is the type of pointer to a method which returns value of variable
Definition at line 426 of file ttmathparser.h.
VariablesTable
template<class ValueType> typedef std::map<std::string, pfunction_var> ttmath::Parser< ValueType >::VariablesTable protected
table of mathematic variables
this map consists of: std::string - variable's name pfunction_var - pointer to specific function which returns value of variable
Definition at line 458 of file ttmathparser.h.
Constructor & Destructor Documentation
Parser() [1/2]
template<class ValueType> ttmath::Parser< ValueType >::Parser ()
the default constructor
Definition at line 2524 of file ttmathparser.h.
         : default_stack_size(100)
 {
     pstop_calculating = 0;
     puser_variables   = 0;
     puser_functions   = 0;
     pfunction_local_variables = 0;
     base              = 10;
     deg_rad_grad      = 1;
     error             = err_ok;
     group             = 0;
     comma             = '.';
     comma2            = ',';
     param_sep         = 0;
     CreateFunctionsTable();
     CreateVariablesTable();
     CreateMathematicalOperatorsTable();
 }
References ttmath::Parser< ValueType >::base, ttmath::Parser< ValueType >::comma, ttmath::Parser< ValueType >::CreateFunctionsTable(), ttmath::Parser< ValueType >::CreateMathematicalOperatorsTable(), ttmath::Parser< ValueType >::CreateVariablesTable(), ttmath::Parser< ValueType >::deg_rad_grad, ttmath::Parser< ValueType >::error, ttmath::Parser< ValueType >::group, ttmath::Parser< ValueType >::param_sep, ttmath::Parser< ValueType >::pfunction_local_variables, ttmath::Parser< ValueType >::pstop_calculating, ttmath::Parser< ValueType >::puser_functions, and ttmath::Parser< ValueType >::puser_variables.
~Parser()
template<class ValueType> virtual ttmath::Parser< ValueType >::~Parser () virtual
dctor
Definition at line 2579 of file ttmathparser.h.
 {
 }
Parser() [2/2]
template<class ValueType> ttmath::Parser< ValueType >::Parser (const Parser< ValueType > & p)
the copying constructor
Definition at line 2588 of file ttmathparser.h.
                                    : default_stack_size(p.default_stack_size)
 {
     operator=(p);
 }
References ttmath::Parser< ValueType >::operator=().
Member Function Documentation
AddToStack() [1/4]
template<class ValueType> void ttmath::Parser< ValueType >::AddToStack (ValueType & value) protected
add a new item (numerical value) to the stack
Definition at line 540 of file ttmathparser.h.
 {
     EnsurePlaceOnStack();
     stack[stack_index].Clear();
     stack[stack_index].type = Item::numerical_value;
     stack[stack_index].value = value;
     stack_index += 1;
 }
References ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::ReadMathematicalOperator(), ttmath::Parser< ValueType >::ReadOperator(), ttmath::Parser< ValueType >::ReadValue(), and ttmath::Parser< ValueType >::ReadVariableOrFunction().
AddToStack() [2/4]
template<class ValueType> void ttmath::Parser< ValueType >::AddToStack (typename Item::Type type, bool is_sign) protected
add a new item to the stack
Definition at line 554 of file ttmathparser.h.
 {
     EnsurePlaceOnStack();
     stack[stack_index].Clear();
     stack[stack_index].type = type;
     stack[stack_index].function = false;
     stack[stack_index].sign = is_sign;
     stack_index += 1;
 }
References ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
AddToStack() [3/4]
template<class ValueType> void ttmath::Parser< ValueType >::AddToStack (typename MatOperator::Type mat_operator_type) protected
add a new item (math operator) to the stack
Definition at line 569 of file ttmathparser.h.
 {
     EnsurePlaceOnStack();
     stack[stack_index].Clear();
     stack[stack_index].type = Item::mat_operator;
     stack[stack_index].moperator.SetType(mat_operator_type);
     stack_index += 1;
 }
References ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
AddToStack() [4/4]
template<class ValueType> void ttmath::Parser< ValueType >::AddToStack (typename Item::Type type, const std::string & name, bool is_function, bool is_sign) protected
add a new item (function or variable) to the stack
if is_function is true then we add a function name when false then we add a variable (such a case is only when an assigment operator = is used e.g. a = 10)
Definition at line 586 of file ttmathparser.h.
 {
     EnsurePlaceOnStack();
     stack[stack_index].Clear();
     stack[stack_index].type = type;
     stack[stack_index].function_name = name;
     stack[stack_index].function = is_function;
     stack[stack_index].sign = is_sign;
     stack_index += 1;
 }
References ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Calculated()
template<class ValueType> bool ttmath::Parser< ValueType >::Calculated ()
this method returns true is something was calculated (at least one mathematical operator was used or a function or variable) e.g. true if the string to Parse() looked like this: "1+1" "2*3" "sin(5)"
if the string was e.g. "678" the result is false
Definition at line 2757 of file ttmathparser.h.
 {
     return calculated;
 }
References ttmath::Parser< ValueType >::calculated.
CheckStackIntegrity()
template<class ValueType> virtual void ttmath::Parser< ValueType >::CheckStackIntegrity () protected virtual
we check wheter there are only numerical value's on the stack
Definition at line 2451 of file ttmathparser.h.
 {
     for(unsigned int i=0 ; i<stack_index; ++i)
     {
         if( stack[i].type != Item::numerical_value )
         {
             /*
                 on the stack we must only have 'numerical_value'
                 if there is something another that means
                 we probably didn't close any of the 'first' brackets
             */
             Error( err_stack_not_clear );
         }
     }
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::Parse().
ConvertAngleToRad()
template<class ValueType> ValueType ttmath::Parser< ValueType >::ConvertAngleToRad (const ValueType & input) protected
wrappers for mathematic functions
'index' is pointing on the first argument on the stack, the second argument has 'index+1' and so on 'result' will be the result of the function
(we're using exceptions here for example when function gets an improper argument)
used by: sin,cos,tan,cot
Definition at line 777 of file ttmathparser.h.
 {
     if( deg_rad_grad == 1 ) // rad
         return input;
     ValueType result;
     ErrorCode err;
     if( deg_rad_grad == 0 ) // deg
         result = ttmath::DegToRad(input, &err);
     else // grad
         result = ttmath::GradToRad(input, &err);
     if( err != err_ok )
         Error( err );
 return result;
 }
References ttmath::Parser< ValueType >::deg_rad_grad, ttmath::DegToRad(), ttmath::Parser< ValueType >::Error(), and ttmath::GradToRad().
ConvertRadToAngle()
template<class ValueType> ValueType ttmath::Parser< ValueType >::ConvertRadToAngle (const ValueType & input) protected
used by: asin,acos,atan,acot
Definition at line 800 of file ttmathparser.h.
 {
     if( deg_rad_grad == 1 ) // rad
         return input;
     ValueType result;
     ErrorCode err;
     if( deg_rad_grad == 0 ) // deg
         result = ttmath::RadToDeg(input, &err);
     else // grad
         result = ttmath::RadToGrad(input, &err);
     if( err != err_ok )
         Error( err );
 return result;
 }
References ttmath::Parser< ValueType >::deg_rad_grad, ttmath::Parser< ValueType >::Error(), ttmath::RadToDeg(), and ttmath::RadToGrad().
CreateFunctionsTable()
template<class ValueType> void ttmath::Parser< ValueType >::CreateFunctionsTable () protected
this method creates the table of functions
Definition at line 1655 of file ttmathparser.h.
 {
     InsertFunctionToTable("gamma",      &Parser<ValueType>::Gamma);
     InsertFunctionToTable("factorial",  &Parser<ValueType>::Factorial);
     InsertFunctionToTable("abs",        &Parser<ValueType>::Abs);
     InsertFunctionToTable("sin",        &Parser<ValueType>::Sin);
     InsertFunctionToTable("cos",        &Parser<ValueType>::Cos);
     InsertFunctionToTable("tan",        &Parser<ValueType>::Tan);
     InsertFunctionToTable("tg",         &Parser<ValueType>::Tan);
     InsertFunctionToTable("cot",        &Parser<ValueType>::Cot);
     InsertFunctionToTable("ctg",        &Parser<ValueType>::Cot);
     InsertFunctionToTable("int",        &Parser<ValueType>::Int);
     InsertFunctionToTable("round",      &Parser<ValueType>::Round);
     InsertFunctionToTable("ln",         &Parser<ValueType>::Ln);
     InsertFunctionToTable("log",        &Parser<ValueType>::Log);
     InsertFunctionToTable("exp",        &Parser<ValueType>::Exp);
     InsertFunctionToTable("max",        &Parser<ValueType>::Max);
     InsertFunctionToTable("min",        &Parser<ValueType>::Min);
     InsertFunctionToTable("asin",       &Parser<ValueType>::ASin);
     InsertFunctionToTable("acos",       &Parser<ValueType>::ACos);
     InsertFunctionToTable("atan",       &Parser<ValueType>::ATan);
     InsertFunctionToTable("atg",        &Parser<ValueType>::ATan);
     InsertFunctionToTable("acot",       &Parser<ValueType>::ACot);
     InsertFunctionToTable("actg",       &Parser<ValueType>::ACot);
     InsertFunctionToTable("sgn",        &Parser<ValueType>::Sgn);
     InsertFunctionToTable("mod",        &Parser<ValueType>::Mod);
     InsertFunctionToTable("if",         &Parser<ValueType>::If);
     InsertFunctionToTable("or",         &Parser<ValueType>::Or);
     InsertFunctionToTable("and",        &Parser<ValueType>::And);
     InsertFunctionToTable("not",        &Parser<ValueType>::Not);
     InsertFunctionToTable("degtorad",   &Parser<ValueType>::DegToRad);
     InsertFunctionToTable("radtodeg",   &Parser<ValueType>::RadToDeg);
     InsertFunctionToTable("degtodeg",   &Parser<ValueType>::DegToDeg);
     InsertFunctionToTable("gradtorad",  &Parser<ValueType>::GradToRad);
     InsertFunctionToTable("radtograd",  &Parser<ValueType>::RadToGrad);
     InsertFunctionToTable("degtograd",  &Parser<ValueType>::DegToGrad);
     InsertFunctionToTable("gradtodeg",  &Parser<ValueType>::GradToDeg);
     InsertFunctionToTable("ceil",       &Parser<ValueType>::Ceil);
     InsertFunctionToTable("floor",      &Parser<ValueType>::Floor);
     InsertFunctionToTable("sqrt",       &Parser<ValueType>::Sqrt);
     InsertFunctionToTable("sinh",       &Parser<ValueType>::Sinh);
     InsertFunctionToTable("cosh",       &Parser<ValueType>::Cosh);
     InsertFunctionToTable("tanh",       &Parser<ValueType>::Tanh);
     InsertFunctionToTable("tgh",        &Parser<ValueType>::Tanh);
     InsertFunctionToTable("coth",       &Parser<ValueType>::Coth);
     InsertFunctionToTable("ctgh",       &Parser<ValueType>::Coth);
     InsertFunctionToTable("root",       &Parser<ValueType>::Root);
     InsertFunctionToTable("asinh",      &Parser<ValueType>::ASinh);
     InsertFunctionToTable("acosh",      &Parser<ValueType>::ACosh);
     InsertFunctionToTable("atanh",      &Parser<ValueType>::ATanh);
     InsertFunctionToTable("atgh",       &Parser<ValueType>::ATanh);
     InsertFunctionToTable("acoth",      &Parser<ValueType>::ACoth);
     InsertFunctionToTable("actgh",      &Parser<ValueType>::ACoth);
     InsertFunctionToTable("bitand",     &Parser<ValueType>::BitAnd);
     InsertFunctionToTable("bitor",      &Parser<ValueType>::BitOr);
     InsertFunctionToTable("bitxor",     &Parser<ValueType>::BitXor);
     InsertFunctionToTable("band",       &Parser<ValueType>::BitAnd);
     InsertFunctionToTable("bor",        &Parser<ValueType>::BitOr);
     InsertFunctionToTable("bxor",       &Parser<ValueType>::BitXor);
     InsertFunctionToTable("sum",        &Parser<ValueType>::Sum);
     InsertFunctionToTable("avg",        &Parser<ValueType>::Avg);
     InsertFunctionToTable("frac",       &Parser<ValueType>::Frac);
 }
References ttmath::Parser< ValueType >::InsertFunctionToTable().
Referenced by ttmath::Parser< ValueType >::Parser().
CreateMathematicalOperatorsTable()
template<class ValueType> void ttmath::Parser< ValueType >::CreateMathematicalOperatorsTable () protected
this method creates the table of operators
Definition at line 2008 of file ttmathparser.h.
 {
     InsertOperatorToTable("||", MatOperator::lor);
     InsertOperatorToTable("&&", MatOperator::land);
     InsertOperatorToTable("!=", MatOperator::neq);
     InsertOperatorToTable("==", MatOperator::eq);
     InsertOperatorToTable(">=", MatOperator::get);
     InsertOperatorToTable("<=", MatOperator::let);
     InsertOperatorToTable(">",  MatOperator::gt);
     InsertOperatorToTable("<",  MatOperator::lt);
     InsertOperatorToTable("-",  MatOperator::sub);
     InsertOperatorToTable("+",  MatOperator::add);
     InsertOperatorToTable("/",  MatOperator::div);
     InsertOperatorToTable("*",  MatOperator::mul);
     InsertOperatorToTable("^",  MatOperator::pow);
     InsertOperatorToTable("=",  MatOperator::assign);
 }
Referenced by ttmath::Parser< ValueType >::Parser().
CreateVariablesTable()
template<class ValueType> void ttmath::Parser< ValueType >::CreateVariablesTable () protected
this method creates the table of variables
Definition at line 1723 of file ttmathparser.h.
 {
     InsertVariableToTable("pi", &ValueType::SetPi);
     InsertVariableToTable("e",  &ValueType::SetE);
 }
References ttmath::Parser< ValueType >::InsertVariableToTable().
Referenced by ttmath::Parser< ValueType >::Parser().
EnsurePlaceOnStack()
template<class ValueType> virtual void ttmath::Parser< ValueType >::EnsurePlaceOnStack () protected virtual
make sure there is a space for a new item at position stack_index
Definition at line 528 of file ttmathparser.h.
 {
     if( stack_index >= stack.size() )
     {
         stack.push_back(Item());
     }
 }
References ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::AddToStack().
Error()
template<class ValueType> static void ttmath::Parser< ValueType >::Error (ErrorCode code) static protected
we're using this method for reporting an error
Definition at line 506 of file ttmathparser.h.
 {
     throw code;
 }
Referenced by ttmath::Parser< ValueType >::CheckStackIntegrity(), ttmath::Parser< ValueType >::ConvertAngleToRad(), ttmath::Parser< ValueType >::ConvertRadToAngle(), ttmath::Parser< ValueType >::Factorial(), ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction(), ttmath::Parser< ValueType >::GetValueOfVariable(), ttmath::Parser< ValueType >::HowManyParameters(), ttmath::Parser< ValueType >::MakeStandardMathematicOperation(), ttmath::Parser< ValueType >::OperatorPercentage(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::ReadMathematicalOperator(), ttmath::Parser< ValueType >::ReadValue(), ttmath::Parser< ValueType >::ReadVariableOrFunction(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_CheckStopCondition(), and ttmath::Parser< ValueType >::RollingUpFinalBracket().
Factorial()
template<class ValueType> void ttmath::Parser< ValueType >::Factorial (unsigned int index, int amount_of_args, ValueType & result) protected
factorial result = 1 * 2 * 3 * 4 * .... * x
Definition at line 838 of file ttmathparser.h.
 {
     if( amount_of_args != 1 )
         Error( err_improper_amount_of_arguments );
     ErrorCode err;
     result = ttmath::Factorial(stack[index].value, cgamma, &err, pstop_calculating);
     if(err != err_ok)
         Error( err );
 }
References ttmath::Parser< ValueType >::cgamma, ttmath::Parser< ValueType >::Error(), ttmath::Factorial(), ttmath::Parser< ValueType >::pstop_calculating, and ttmath::Parser< ValueType >::stack.
GetValueOfFunctionLocalVariable()
template<class ValueType> bool ttmath::Parser< ValueType >::GetValueOfFunctionLocalVariable (const std::string & variable_name, ValueType & result)
this method returns the value of a local variable of a function
Definition at line 716 of file ttmathparser.h.
 {
     if( !pfunction_local_variables )
         return false;
     typename FunctionLocalVariables::const_iterator i = pfunction_local_variables->find(variable_name);
     if( i == pfunction_local_variables->end() )
         return false;
     result = i->second;
 return true;
 }
References ttmath::Parser< ValueType >::pfunction_local_variables.
Referenced by ttmath::Parser< ValueType >::GetValueOfVariable().
GetValueOfUserDefinedFunction()
template<class ValueType> bool ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction (const std::string & function_name, int amount_of_args, unsigned int index) protected
this method returns the value from a user-defined function
(look at the description in 'CallFunction(...)')
Definition at line 1545 of file ttmathparser.h.
 {
     if( !puser_functions )
         return false;
     const char * string_value;
     int param;
     if( puser_functions->GetValueAndParam(function_name, &string_value, &param) != err_ok )
         return false;
     if( param != amount_of_args )
         Error( err_improper_amount_of_arguments );
     FunctionLocalVariables local_variables;
     if( amount_of_args > 0 )
     {
         char buffer[30];
         // x = x1
         buffer[0] = 'x';
         buffer[1] = 0;
         local_variables.insert( std::make_pair(buffer, stack[index].value) );
         for(int i=0 ; i<amount_of_args ; ++i)
         {
             buffer[0] = 'x';
             Sprintf(buffer+1, i+1);
             local_variables.insert( std::make_pair(buffer, stack[index + i].value) );
         }
     }
     stack[index-1].value = RecurrenceParsingVariablesOrFunction(false, function_name, string_value, &local_variables);
     calculated = true;
 return true;
 }
References ttmath::Parser< ValueType >::calculated, ttmath::Parser< ValueType >::Error(), ttmath::Objects::GetValueAndParam(), ttmath::Parser< ValueType >::puser_functions, ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction(), ttmath::Parser< ValueType >::Sprintf(), and ttmath::Parser< ValueType >::stack.
GetValueOfUserDefinedVariable()
template<class ValueType> bool ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable (const std::string & variable_name, ValueType & result)
this method returns the user-defined value of a variable
Definition at line 696 of file ttmathparser.h.
 {
     if( !puser_variables )
         return false;
     const char * string_value;
     if( puser_variables->GetValue(variable_name, &string_value) != err_ok )
         return false;
     result = RecurrenceParsingVariablesOrFunction(true, variable_name, string_value);
     calculated = true;
 return true;
 }
References ttmath::Parser< ValueType >::calculated, ttmath::Objects::GetValue(), ttmath::Parser< ValueType >::puser_variables, and ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
Referenced by ttmath::Parser< ValueType >::GetValueOfVariable().
GetValueOfVariable()
template<class ValueType> virtual ValueType ttmath::Parser< ValueType >::GetValueOfVariable (const std::string & variable_name) virtual
this method returns the value of a variable from variables' table
we make an object of type ValueType then call a method which sets the correct value in it and finally we'll return the object
Definition at line 738 of file ttmathparser.h.
 {
 ValueType result;
     if( GetValueOfFunctionLocalVariable(variable_name, result) )
         return result;
     if( GetValueOfUserDefinedVariable(variable_name, result) )
         return result;
     typename std::map<std::string, pfunction_var>::iterator i =
                                                     variables_table.find(variable_name);
     if( i == variables_table.end() )
         Error( err_unknown_variable );
     (result.*(i->second))();
     calculated = true;
 return result;
 }
References ttmath::Parser< ValueType >::calculated, ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::GetValueOfFunctionLocalVariable(), and ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable().
Referenced by ttmath::Parser< ValueType >::ReadVariableOrFunction().
HowManyParameters()
template<class ValueType> void ttmath::Parser< ValueType >::HowManyParameters (unsigned int & size, unsigned int & index) protected
this method calculate how many parameters there are on the stack and the index of the first parameter
if there are no parameters on the stack this method returns 'size' equals zero and 'index' pointing after the first bracket (on non-existend element)
Definition at line 2341 of file ttmathparser.h.
 {
     size  = 0;
     index = stack_index;
     for( ; index > 0 && stack[index-1].type != Item::first_bracket ; --index )
     {
         if( stack[index-1].type != Item::numerical_value )
         {
             /*
                 this element must be 'numerical_value', if not that means
                 there's an error in our algorithm
             */
             Error( err_internal_error );
         }
         ++size;
     }
     if( index<1 || stack[index-1].type != Item::first_bracket )
     {
         /*
             we haven't put a first bracket on the stack
         */
         Error( err_unexpected_final_bracket );
     }
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::RollingUpFinalBracket().
InitCGamma()
template<class ValueType> void ttmath::Parser< ValueType >::InitCGamma ()
initializing coefficients used when calculating the gamma (or factorial) function this speed up the next calculations you don't have to call this method explicitly these coefficients will be calculated when needed
Definition at line 2769 of file ttmathparser.h.
 {
     cgamma.InitAll();
 }
References ttmath::Parser< ValueType >::cgamma.
InsertFunctionToTable()
template<class ValueType> void ttmath::Parser< ValueType >::InsertFunctionToTable (const char * function_name, pfunction pf) protected
inserting a function to the functions' table
function_name - name of the function pf - pointer to the function (to the wrapper)
Definition at line 1626 of file ttmathparser.h.
 {
     std::string str;
     Misc::AssignString(str, function_name);
     functions_table.insert( std::make_pair(str, pf) );
 }
References ttmath::Misc::AssignString().
Referenced by ttmath::Parser< ValueType >::CreateFunctionsTable().
InsertVariableToTable()
template<class ValueType> void ttmath::Parser< ValueType >::InsertVariableToTable (const char * variable_name, pfunction_var pf) protected
inserting a function to the variables' table (this function returns value of variable)
variable_name - name of the function pf - pointer to the function
Definition at line 1643 of file ttmathparser.h.
 {
     std::string str;
     Misc::AssignString(str, variable_name);
     variables_table.insert( std::make_pair(str, pf) );
 }
References ttmath::Misc::AssignString().
Referenced by ttmath::Parser< ValueType >::CreateVariablesTable().
IsSubstring()
template<class ValueType> virtual bool ttmath::Parser< ValueType >::IsSubstring (const std::string & short_str, const std::string & long_str) protected virtual
returns true if 'short_str' is the substring of long_str
e.g. true when short_str="te" and long_str="test"
Definition at line 2033 of file ttmathparser.h.
 {
     if( short_str.length() > long_str.length() )
         return false;
     for(typename std::string::size_type i=0 ; i<short_str.length() ; ++i)
         if( short_str[i] != long_str[i] )
             return false;
 return true;
 }
Referenced by ttmath::Parser< ValueType >::ReadMathematicalOperator().
IsValidNameCharacter()
template<class ValueType> virtual bool ttmath::Parser< ValueType >::IsValidNameCharacter (int c) protected virtual
return true if c is a valid function or variable name character
Definition at line 1747 of file ttmathparser.h.
 {
     return( (c>='a' && c<='z') ||
             (c>='A' && c<='Z') ||
             (c>='0' && c<='9') ||
             c=='_' );
 }
Referenced by ttmath::Parser< ValueType >::ReadName().
MakeStandardMathematicOperation()
template<class ValueType> virtual void ttmath::Parser< ValueType >::MakeStandardMathematicOperation (Item & item1, typename MatOperator::Type mat_operator, const Item & item2) protected virtual
this method is making the standard mathematic operation like '-' '+' '*' '/' and '^'
the operation is made between 'value1' and 'value2' the result of this operation is stored in the 'value1'
Definition at line 2182 of file ttmathparser.h.
 {
 uint res;
     calculated = true;
     ValueType & value1  = item1.value;
     const ValueType & value2 = item2.value;
     switch( mat_operator )
     {
     case MatOperator::land:
         (!value1.IsZero() && !value2.IsZero()) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::lor:
         (!value1.IsZero() || !value2.IsZero()) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::eq:
         (value1 == value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::neq:
         (value1 != value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::lt:
         (value1 < value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::gt:
         (value1 > value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::let:
         (value1 <= value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::get:
         (value1 >= value2) ? value1.SetOne() : value1.SetZero();
         break;
     case MatOperator::sub:
         if( value1.Sub(value2) ) Error( err_overflow );
         break;
     case MatOperator::add:
         if( value1.Add(value2) ) Error( err_overflow );
         break;
     case MatOperator::mul:
     case MatOperator::shortmul:
         if( value1.Mul(value2) ) Error( err_overflow );
         break;
     case MatOperator::div:
         if( value2.IsZero() )    Error( err_division_by_zero );
         if( value1.Div(value2) ) Error( err_overflow );
         break;
     case MatOperator::pow:
         res = value1.Pow( value2 );
         if( res == 1 ) Error( err_overflow );
         else
         if( res == 2 ) Error( err_improper_argument );
         break;
     default:
         /*
             on the stack left an unknown operator but we had to recognize its before
             that means there's an error in our algorithm
         */
         Error( err_internal_error );
     }
 }
References ttmath::Parser< ValueType >::calculated, and ttmath::Parser< ValueType >::Error().
Referenced by ttmath::Parser< ValueType >::RollUPStack(), and ttmath::Parser< ValueType >::RollUpStackWithOperatorsPriority().
NormalizeStack()
template<class ValueType> void ttmath::Parser< ValueType >::NormalizeStack () protected
this method is called at the end of the parsing process
Definition at line 2501 of file ttmathparser.h.
 {
     if( error!=err_ok || stack_index==0 )
     {
         stack.clear();
         return;
     }
     /*
         'stack_index' tell us how many elements there are on the stack,
         we must resize the stack now because 'stack_index' is using only for parsing
         and stack has more (or equal) elements than value of 'stack_index'
     */
     stack.resize( stack_index );
 }
References ttmath::Parser< ValueType >::error, ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::Parse().
operator=()
template<class ValueType> Parser<ValueType>& ttmath::Parser< ValueType >::operator= (const Parser< ValueType > & p)
the assignment operator
Definition at line 2547 of file ttmathparser.h.
 {
     pstop_calculating = p.pstop_calculating;
     puser_variables   = p.puser_variables;
     puser_functions   = p.puser_functions;
     pfunction_local_variables = 0;
     base              = p.base;
     deg_rad_grad      = p.deg_rad_grad;
     error             = p.error;
     group             = p.group;
     comma             = p.comma;
     comma2            = p.comma2;
     param_sep         = p.param_sep;
     /*
         we don't have to call 'CreateFunctionsTable()' etc.
         we can only copy these tables
     */
     functions_table   = p.functions_table;
     variables_table   = p.variables_table;
     operators_table   = p.operators_table;
     visited_variables = p.visited_variables;
     visited_functions = p.visited_functions;
 return *this;
 }
References ttmath::Parser< ValueType >::base, ttmath::Parser< ValueType >::comma, ttmath::Parser< ValueType >::deg_rad_grad, ttmath::Parser< ValueType >::error, ttmath::Parser< ValueType >::group, ttmath::Parser< ValueType >::param_sep, ttmath::Parser< ValueType >::pfunction_local_variables, ttmath::Parser< ValueType >::pstop_calculating, ttmath::Parser< ValueType >::puser_functions, ttmath::Parser< ValueType >::puser_variables, ttmath::Parser< ValueType >::visited_functions, and ttmath::Parser< ValueType >::visited_variables.
Referenced by ttmath::Parser< ValueType >::Parser().
OperatorPercentage()
template<class ValueType> void ttmath::Parser< ValueType >::OperatorPercentage () protected
this method makes a calculation for the percentage operator e.g. 1000-50% = 1000-(1000*0,5) = 500
Definition at line 2084 of file ttmathparser.h.
 {
     if( stack_index < 3                                     ||
         stack[stack_index-1].type != Item::numerical_value  ||
         stack[stack_index-2].type != Item::mat_operator     ||
         stack[stack_index-3].type != Item::numerical_value  )
     {
         Error( err_percent_from );
     }
     else
     {
         uint c = 0;
         c += stack[stack_index-1].value.Div(100);
         c += stack[stack_index-1].value.Mul(stack[stack_index-3].value);
         if( c )
         {
             Error( err_overflow );
         }
     }
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::ReadOperator().
Parse() [1/5]
template<class ValueType> virtual void ttmath::Parser< ValueType >::Parse () protected virtual
the main loop of parsing
Definition at line 2472 of file ttmathparser.h.
 {
     while( *pstring )
     {
         const char * old_pstring = pstring;
         if( pstop_calculating && pstop_calculating->WasStopSignal() )
             Error( err_interrupt );
         ReadTokens();
         ReadOperators();
         RollUpStackWithOperatorsPriority();
         if( old_pstring == pstring )
             Error( err_internal_error ); // pstring should be incremented in ReadTokens() or ReadOperators()
     }
     if( stack_index == 0 )
         Error( err_nothing_has_read );
     RollUPStack();
     CheckStackIntegrity();
 }
References ttmath::Parser< ValueType >::CheckStackIntegrity(), ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::pstop_calculating, ttmath::Parser< ValueType >::pstring, ttmath::Parser< ValueType >::ReadOperators(), ttmath::Parser< ValueType >::ReadTokens(), ttmath::Parser< ValueType >::RollUPStack(), ttmath::Parser< ValueType >::RollUpStackWithOperatorsPriority(), and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::Parse(), and ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
Parse() [2/5]
template<class ValueType> ErrorCode ttmath::Parser< ValueType >::Parse (const char * str)
the main method using for parsing string
Definition at line 2688 of file ttmathparser.h.
 {
     stack_index  = 0;
     pstring      = str;
     error        = err_ok;
     calculated   = false;
     try
     {
         stack.resize(default_stack_size);
         Parse();
     }
     catch(ErrorCode c)
     {
         error = c;
         calculated = false;
     }
     NormalizeStack();
 return error;
 }
References ttmath::Parser< ValueType >::calculated, ttmath::Parser< ValueType >::default_stack_size, ttmath::Parser< ValueType >::error, ttmath::Parser< ValueType >::NormalizeStack(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::pstring, ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Parse() [3/5]
template<class ValueType> ErrorCode ttmath::Parser< ValueType >::Parse (const std::string & str)
the main method using for parsing string
Definition at line 2715 of file ttmathparser.h.
 {
     return Parse(str.c_str());
 }
References ttmath::Parser< ValueType >::Parse().
Parse() [4/5]
template<class ValueType> ErrorCode ttmath::Parser< ValueType >::Parse (const wchar_t * str)
the main method using for parsing string
Definition at line 2726 of file ttmathparser.h.
 {
     Misc::AssignString(wide_to_ansi, str);
 return Parse(wide_to_ansi.c_str());
     // !! wide_to_ansi clearing can be added here
 }
References ttmath::Misc::AssignString(), ttmath::Parser< ValueType >::Parse(), and ttmath::Parser< ValueType >::wide_to_ansi.
Parse() [5/5]
template<class ValueType> ErrorCode ttmath::Parser< ValueType >::Parse (const std::wstring & str)
the main method using for parsing string
Definition at line 2739 of file ttmathparser.h.
 {
     return Parse(str.c_str());
 }
References ttmath::Parser< ValueType >::Parse().
ReadMathematicalOperator()
template<class ValueType> void ttmath::Parser< ValueType >::ReadMathematicalOperator () protected
this method reads a mathematical (or logical) operator
Definition at line 2049 of file ttmathparser.h.
 {
 std::string oper;
 typename OperatorsTable::iterator iter_old, iter_new;
     iter_old = operators_table.end();
     for( ; true ; ++pstring )
     {
         oper += *pstring;
         iter_new = operators_table.lower_bound(oper);
         if( iter_new == operators_table.end() || !IsSubstring(oper, iter_new->first) )
         {
             oper.erase(oper.begin() + oper.size() - 1); // we've got minimum one element
             if( iter_old != operators_table.end() && iter_old->first == oper )
             {
                 AddToStack(iter_old->second);
                 break;
             }
             Error( err_unknown_operator );
         }
         iter_old = iter_new;
     }
 }
References ttmath::Parser< ValueType >::AddToStack(), ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::IsSubstring(), and ttmath::Parser< ValueType >::pstring.
Referenced by ttmath::Parser< ValueType >::ReadOperator().
ReadName()
template<class ValueType> virtual void ttmath::Parser< ValueType >::ReadName (std::string & result) protected virtual
this method read the name of a variable or a function 'result' will be the name of a variable or a function
Definition at line 1760 of file ttmathparser.h.
 {
     result.erase();
     while( IsValidNameCharacter(*pstring) )
     {
         result += *pstring;
         pstring += 1;
     }
 }
References ttmath::Parser< ValueType >::IsValidNameCharacter(), and ttmath::Parser< ValueType >::pstring.
Referenced by ttmath::Parser< ValueType >::ReadVariableOrFunction().
ReadOperator()
template<class ValueType> virtual bool ttmath::Parser< ValueType >::ReadOperator () protected virtual
this method reads a mathematic operators or the final bracket or the semicolon operator
return values: true - if next operator should be read
Definition at line 2114 of file ttmathparser.h.
 {
     bool read_next_operator = false;
     if( *pstring == '%' )
     {
         OperatorPercentage();
         ++pstring;
         // now we can read another operator
     }
     if( *pstring == ')' )
     {
         ++pstring;
         RollingUpFinalBracket();
         read_next_operator = true;
     }
     else
     if( *pstring == ';' || (param_sep!=0 && *pstring==param_sep) )
     {
         RollUPStack();
         ++pstring;
     }
     else
     if( (*pstring>='a' && *pstring<='z') || (*pstring>='A' && *pstring<='Z') )
     {
         // short mul (without any operators)
         // short mul is available only if the next item is a variable or a function
         AddToStack(MatOperator::shortmul);
     }
     else
     {
         ReadMathematicalOperator();
     }
     return read_next_operator;
 }
References ttmath::Parser< ValueType >::AddToStack(), ttmath::Parser< ValueType >::OperatorPercentage(), ttmath::Parser< ValueType >::param_sep, ttmath::Parser< ValueType >::pstring, ttmath::Parser< ValueType >::ReadMathematicalOperator(), ttmath::Parser< ValueType >::RollingUpFinalBracket(), and ttmath::Parser< ValueType >::RollUPStack().
Referenced by ttmath::Parser< ValueType >::ReadOperators().
ReadOperators()
template<class ValueType> virtual void ttmath::Parser< ValueType >::ReadOperators () protected virtual
this method is reading a operator and if it's a final bracket it's calling RollingUpFinalBracket() and reading an operator again
Definition at line 2158 of file ttmathparser.h.
 {
     bool continue_reading;
     do
     {
         continue_reading = false;
         SkipWhiteCharacters();
         if( *pstring )
             continue_reading = ReadOperator();
     }
     while( continue_reading );
 }
References ttmath::Parser< ValueType >::pstring, ttmath::Parser< ValueType >::ReadOperator(), and ttmath::Parser< ValueType >::SkipWhiteCharacters().
Referenced by ttmath::Parser< ValueType >::Parse().
ReadTokens()
template<class ValueType> virtual void ttmath::Parser< ValueType >::ReadTokens () protected virtual
we're reading the item
return values: 0 - all ok, the item is successfully read 1 - the end of the string (the item is not read) 2 - the final bracket ')'
Definition at line 1983 of file ttmathparser.h.
 {
     bool continue_reading;
     do
     {
         continue_reading = false;
         SkipWhiteCharacters();
         if( *pstring )
             continue_reading = ReadToken();
     } while( continue_reading );
 }
References ttmath::Parser< ValueType >::pstring, and ttmath::Parser< ValueType >::SkipWhiteCharacters().
Referenced by ttmath::Parser< ValueType >::Parse().
ReadValue()
template<class ValueType> virtual void ttmath::Parser< ValueType >::ReadValue (int reading_base, bool change_sign) protected virtual
we're reading a numerical value directly from the string
Definition at line 1839 of file ttmathparser.h.
 {
 const char * after_value_string;
 bool value_read;
 Conv conv;
     conv.base   = reading_base;
     conv.comma  = comma;
     conv.comma2 = comma2;
     conv.group  = group;
     ValueType value;
     uint carry = value.FromString(pstring, conv, &after_value_string, &value_read);
     pstring    = after_value_string;
     if( carry )
         Error( err_overflow );
     if( !value_read )
         Error( err_unknown_character );
     if( change_sign )
     {
         value.ChangeSign();
     }
     AddToStack(value);
 }
References ttmath::Parser< ValueType >::AddToStack(), ttmath::Conv::base, ttmath::Conv::comma, ttmath::Parser< ValueType >::comma, ttmath::Conv::comma2, ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::group, ttmath::Conv::group, and ttmath::Parser< ValueType >::pstring.
ReadVariableOrFunction()
template<class ValueType> virtual bool ttmath::Parser< ValueType >::ReadVariableOrFunction (bool was_sign, bool was_minus_sign) protected virtual
we're reading the name of a variable or a function if is there a function we'll return 'true' also we return true when we read the name of a variable with an assignment operator
Definition at line 1778 of file ttmathparser.h.
 {
     std::string name;
     bool read_next_token = false;
     ReadName(name);
     SkipWhiteCharacters();
     if( *pstring == '(' )
     {
         /*
             if there's a character '(' that means this name is a name of a function
         */
         ++pstring;
         AddToStack(Item::first_bracket, name, true, was_minus_sign);
         read_next_token = true;
     }
     else
     if( *pstring == '=' && *(pstring+1) != '=' )
     {
         /*
             if there's a character '=' that means this name is a name of a variable with an assigment operator
         */
         ++pstring;
         if( !was_sign )
         {
             AddToStack(Item::variable, name, false, false);
             AddToStack(MatOperator::assign);
             read_next_token = true;
         }
         else
         {
             // something like: '-a = 10' or '+a = 10'
             Error( err_assignment_requires_variable );
         }
     }
     else
     {
         /*
             we've read the name of a variable and we're getting its value now
         */
         ValueType value = GetValueOfVariable(name);
         if( was_minus_sign )
             value.ChangeSign();
         AddToStack(value);
     }
     return read_next_token;
 }
References ttmath::Parser< ValueType >::AddToStack(), ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::GetValueOfVariable(), ttmath::Parser< ValueType >::pstring, ttmath::Parser< ValueType >::ReadName(), and ttmath::Parser< ValueType >::SkipWhiteCharacters().
RecurrenceParsingVariablesOrFunction()
template<class ValueType> ValueType ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction (bool variable, const std::string & name, const char * new_string, FunctionLocalVariables * local_variables = 0) protected
this method returns the value of a variable or function by creating a new instance of the mathematical parser and making the standard parsing algorithm on the given string
this method is used only during parsing user defined variables or functions
(there can be a recurrence here therefore we're using 'visited_variables' and 'visited_functions' sets to make a stop condition)
Definition at line 652 of file ttmathparser.h.
 {
     RecurrenceParsingVariablesOrFunction_CheckStopCondition(variable, name);
     RecurrenceParsingVariablesOrFunction_AddName(variable, name);
     Parser<ValueType> NewParser(*this);
     ErrorCode err;
     NewParser.pfunction_local_variables = local_variables;
     try
     {
         err = NewParser.Parse(new_string);
     }
     catch(...)
     {
         RecurrenceParsingVariablesOrFunction_DeleteName(variable, name);
     throw;
     }
     RecurrenceParsingVariablesOrFunction_DeleteName(variable, name);
     if( err != err_ok )
         Error( err );
     if( NewParser.stack.size() != 1 )
         Error( err_must_be_only_one_value );
     if( NewParser.stack[0].type != Item::numerical_value )
         // I think there shouldn't be this error here
         Error( err_incorrect_value );
 return NewParser.stack[0].value;
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::pfunction_local_variables, ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_AddName(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_CheckStopCondition(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_DeleteName(), and ttmath::Parser< ValueType >::stack.
Referenced by ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction(), and ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable().
RecurrenceParsingVariablesOrFunction_AddName()
template<class ValueType> void ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_AddName (bool variable, const std::string & name) protected
an auxiliary method for RecurrenceParsingVariablesOrFunction(...)
Definition at line 621 of file ttmathparser.h.
 {
     if( variable )
         visited_variables.insert( name );
     else
         visited_functions.insert( name );
 }
References ttmath::Parser< ValueType >::visited_functions, and ttmath::Parser< ValueType >::visited_variables.
Referenced by ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
RecurrenceParsingVariablesOrFunction_CheckStopCondition()
template<class ValueType> void ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_CheckStopCondition (bool variable, const std::string & name) protected
an auxiliary method for RecurrenceParsingVariablesOrFunction(...)
Definition at line 603 of file ttmathparser.h.
 {
     if( variable )
     {
         if( visited_variables.find(name) != visited_variables.end() )
             Error( err_variable_loop );
     }
     else
     {
         if( visited_functions.find(name) != visited_functions.end() )
             Error( err_functions_loop );
     }
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::visited_functions, and ttmath::Parser< ValueType >::visited_variables.
Referenced by ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
RecurrenceParsingVariablesOrFunction_DeleteName()
template<class ValueType> void ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_DeleteName (bool variable, const std::string & name) protected
an auxiliary method for RecurrenceParsingVariablesOrFunction(...)
Definition at line 633 of file ttmathparser.h.
 {
     if( variable )
         visited_variables.erase( name );
     else
         visited_functions.erase( name );
 }
References ttmath::Parser< ValueType >::visited_functions, and ttmath::Parser< ValueType >::visited_variables.
Referenced by ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
RollingUpFinalBracket()
template<class ValueType> void ttmath::Parser< ValueType >::RollingUpFinalBracket () protected
this method is being called when the final bracket ')' is being found
this method's rolling the stack up, counting how many parameters there are on the stack and if there was a function it's calling the function
Definition at line 2376 of file ttmathparser.h.
 {
     unsigned int amount_of_parameters;
     unsigned int index;
     if( stack_index<1 ||
         (stack[stack_index-1].type != Item::numerical_value &&
          stack[stack_index-1].type != Item::first_bracket)
       )
     {
         Error( err_unexpected_final_bracket );
         return;
     }
     RollUPStack();
     HowManyParameters(amount_of_parameters, index);
     // 'index' will be greater than zero
     // 'amount_of_parameters' can be zero
     if( amount_of_parameters==0 && !stack[index-1].function )
         Error( err_unexpected_final_bracket );
     bool was_sign = stack[index-1].sign;
     if( stack[index-1].function )
     {
         // the result of a function will be on 'stack[index-1]'
         // and then at the end we'll set the correct type (numerical value) of this element
         CallFunction(stack[index-1].function_name, amount_of_parameters, index);
     }
     else
     {
         /*
             there was a normal bracket (not a funcion)
         */
         if( amount_of_parameters != 1 )
             Error( err_unexpected_semicolon_operator );
         /*
             in the place where is the bracket we put the result
         */
         stack[index-1] = stack[index];
     }
     /*
         if there was a '-' character before the first bracket
         we change the sign of the expression
     */
     stack[index-1].sign = false;
     if( was_sign )
         stack[index-1].value.ChangeSign();
     stack[index-1].type = Item::numerical_value;
     /*
         the pointer of the stack will be pointing on the next (non-existing now) element
     */
     stack_index = index;
 }
References ttmath::Parser< ValueType >::Error(), ttmath::Parser< ValueType >::HowManyParameters(), ttmath::Parser< ValueType >::RollUPStack(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::ReadOperator().
RollUPStack()
template<class ValueType> void ttmath::Parser< ValueType >::RollUPStack () protected
this method is trying to roll the stack up without testing any operators
for example if there are: "1 - 2" there'll be "-1" on our stack
Definition at line 2316 of file ttmathparser.h.
 {
     while(  stack_index >= 3 &&
             (stack[stack_index-3].type == Item::numerical_value || stack[stack_index-3].type == Item::variable) &&
             stack[stack_index-2].type == Item::mat_operator &&
             stack[stack_index-1].type == Item::numerical_value )
     {
         MakeStandardMathematicOperation(    stack[stack_index-3],
                                             stack[stack_index-2].moperator.GetType(),
                                             stack[stack_index-1] );
         stack_index -= 2;
     }
 }
References ttmath::Parser< ValueType >::MakeStandardMathematicOperation(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::ReadOperator(), and ttmath::Parser< ValueType >::RollingUpFinalBracket().
RollUpStackWithOperatorsPriority()
template<class ValueType> void ttmath::Parser< ValueType >::RollUpStackWithOperatorsPriority () protected
this method is trying to roll the stack up with the operator's priority
for example if there are: "1 - 2 +" we can subtract "1-2" and the result store on the place where is '1' and copy the last operator '+', that means there'll be '-1+' on our stack
but if there are: "1 - 2 *" we can't roll the stack up because the operator '*' has greater priority than '-'
Definition at line 2275 of file ttmathparser.h.
 {
     while(  stack_index>=4 &&
             (stack[stack_index-4].type == Item::numerical_value || stack[stack_index-4].type == Item::variable) &&
             stack[stack_index-3].type == Item::mat_operator    &&
             stack[stack_index-2].type == Item::numerical_value &&
             stack[stack_index-1].type == Item::mat_operator    &&
             (
                 (
                     // the first operator has greater priority
                     stack[stack_index-3].moperator.GetPriority() > stack[stack_index-1].moperator.GetPriority()
                 ) ||
                 (
                     // or both operators have the same priority and the first operator is not right associative
                     stack[stack_index-3].moperator.GetPriority() == stack[stack_index-1].moperator.GetPriority() &&
                     stack[stack_index-3].moperator.GetAssoc()    == MatOperator::non_right
                 )
             )
          )
     {
         MakeStandardMathematicOperation(stack[stack_index-4],
                                         stack[stack_index-3].moperator.GetType(),
                                         stack[stack_index-2]);
         /*
             copying the last operator and setting the stack pointer to the correct value
         */
         stack[stack_index-3] = stack[stack_index-1];
         stack_index -= 2;
     }
 }
References ttmath::Parser< ValueType >::MakeStandardMathematicOperation(), ttmath::Parser< ValueType >::stack, and ttmath::Parser< ValueType >::stack_index.
Referenced by ttmath::Parser< ValueType >::Parse().
SetBase()
template<class ValueType> void ttmath::Parser< ValueType >::SetBase (int b)
the new base of mathematic system default is 10
Definition at line 2598 of file ttmathparser.h.
 {
     if( b>=2 && b<=16 )
         base = b;
 }
References ttmath::Parser< ValueType >::base.
SetComma()
template<class ValueType> void ttmath::Parser< ValueType >::SetComma (int c, int c2 = 0)
setting the main comma operator and the additional comma operator the additional operator can be zero (which means it is not used) default are: '.' and ','
Definition at line 2666 of file ttmathparser.h.
 {
     comma  = c;
     comma2 = c2;
 }
References ttmath::Parser< ValueType >::comma.
SetDegRadGrad()
template<class ValueType> void ttmath::Parser< ValueType >::SetDegRadGrad (int angle)
the unit of angles used in: sin,cos,tan,cot,asin,acos,atan,acot 0 - deg 1 - rad (default) 2 - grad
Definition at line 2611 of file ttmathparser.h.
 {
     if( angle >= 0 && angle <= 2 )
         deg_rad_grad = angle;
 }
References ttmath::Parser< ValueType >::deg_rad_grad.
SetFunctions()
template<class ValueType> void ttmath::Parser< ValueType >::SetFunctions (const Objects * pf)
this method sets the new table of user-defined functions if you don't want any other functions just put zero value into the 'puser_functions' variable
(you can have only one table at the same time)
Definition at line 2645 of file ttmathparser.h.
 {
     puser_functions = pf;
 }
References ttmath::Parser< ValueType >::puser_functions.
SetGroup()
template<class ValueType> void ttmath::Parser< ValueType >::SetGroup (int g)
setting the group character default zero (not used)
Definition at line 2655 of file ttmathparser.h.
 {
     group = g;
 }
References ttmath::Parser< ValueType >::group.
SetParamSep()
template<class ValueType> void ttmath::Parser< ValueType >::SetParamSep (int s)
setting an additional character which is used as a parameters separator the main parameters separator is a semicolon (is used always)
this character is used also as a global separator
Definition at line 2679 of file ttmathparser.h.
 {
     param_sep = s;
 }
References ttmath::Parser< ValueType >::param_sep.
SetStopObject()
template<class ValueType> void ttmath::Parser< ValueType >::SetStopObject (const volatile StopCalculating * ps)
this method sets a pointer to the object which tell us whether we should stop calculations
Definition at line 2621 of file ttmathparser.h.
 {
     pstop_calculating = ps;
 }
References ttmath::Parser< ValueType >::pstop_calculating.
SetVariables()
template<class ValueType> void ttmath::Parser< ValueType >::SetVariables (const Objects * pv)
this method sets the new table of user-defined variables if you don't want any other variables just put zero value into the 'puser_variables' variable
(you can have only one table at the same time)
Definition at line 2633 of file ttmathparser.h.
 {
     puser_variables = pv;
 }
References ttmath::Parser< ValueType >::puser_variables.
SkipWhiteCharacters()
template<class ValueType> void ttmath::Parser< ValueType >::SkipWhiteCharacters () protected
this method skips the white character from the string
it's moving the 'pstring' to the first no-white character
Definition at line 517 of file ttmathparser.h.
 {
     while( (*pstring==' ' ) || (*pstring=='\t') )
         ++pstring;
 }
References ttmath::Parser< ValueType >::pstring.
Referenced by ttmath::Parser< ValueType >::ReadOperators(), ttmath::Parser< ValueType >::ReadTokens(), and ttmath::Parser< ValueType >::ReadVariableOrFunction().
Sprintf()
template<class ValueType> void ttmath::Parser< ValueType >::Sprintf (char * buffer, int par) protected
we use such a method because 'wvsprintf' is not everywhere defined
Definition at line 1516 of file ttmathparser.h.
 {
 char buf[30]; // char, not wchar_t
 int i;
     #ifdef _MSC_VER
     #pragma warning( disable: 4996 )
     //warning C4996: 'sprintf': This function or variable may be unsafe.
     #endif
     sprintf(buf, "%d", par);
     for(i=0 ; buf[i] != 0 ; ++i)
         buffer[i] = buf[i];
     buffer[i] = 0;
     #ifdef _MSC_VER
     #pragma warning( default: 4996 )
     #endif
 }
Referenced by ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction().
ToLowerCase()
template<class ValueType> int ttmath::Parser< ValueType >::ToLowerCase (int c) protected
converting from a big letter to a small one
Definition at line 1733 of file ttmathparser.h.
 {
     if( c>='A' && c<='Z' )
         return c - 'A' + 'a';
 return c;
 }
ValueStarts()
template<class ValueType> virtual bool ttmath::Parser< ValueType >::ValueStarts (int character, int character_base) protected virtual
this method returns true if 'character' is a proper first digit for the value (or a comma – can be first too)
Definition at line 1872 of file ttmathparser.h.
 {
     if( character == comma )
         return true;
     if( comma2!=0 && character==comma2 )
         return true;
     if( Misc::CharToDigit(character, character_base) != -1 )
         return true;
 return false;
 }
References ttmath::Misc::CharToDigit(), and ttmath::Parser< ValueType >::comma.
Field Documentation
base
template<class ValueType> int ttmath::Parser< ValueType >::base protected
the base (radix) of the mathematic system (for example it may be '10')
Definition at line 357 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::SetBase().
calculated
template<class ValueType> bool ttmath::Parser< ValueType >::calculated protected
true if something was calculated (at least one mathematical operator was used or a function or a variable)
Definition at line 499 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Calculated(), ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction(), ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable(), ttmath::Parser< ValueType >::GetValueOfVariable(), ttmath::Parser< ValueType >::MakeStandardMathematicOperation(), and ttmath::Parser< ValueType >::Parse().
cgamma
template<class ValueType> CGamma<ValueType> ttmath::Parser< ValueType >::cgamma protected
some coefficients used when calculating the gamma (or factorial) function
Definition at line 465 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Factorial(), and ttmath::Parser< ValueType >::InitCGamma().
comma
template<class ValueType> int ttmath::Parser< ValueType >::comma protected
characters used as a comma default: '.' and ',' comma2 can be zero (it means it is not used)
Definition at line 486 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), ttmath::Parser< ValueType >::ReadValue(), ttmath::Parser< ValueType >::SetComma(), and ttmath::Parser< ValueType >::ValueStarts().
default_stack_size
template<class ValueType> const int ttmath::Parser< ValueType >::default_stack_size protected
size of the stack when we're starting parsing of the string
if it's to small while parsing the stack will be automatically resized
Definition at line 329 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Parse().
deg_rad_grad
template<class ValueType> int ttmath::Parser< ValueType >::deg_rad_grad protected
the unit of angles used in: sin,cos,tan,cot,asin,acos,atan,acot 0 - deg 1 - rad (default) 2 - grad
Definition at line 366 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::ConvertAngleToRad(), ttmath::Parser< ValueType >::ConvertRadToAngle(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::SetDegRadGrad().
error
template<class ValueType> ErrorCode ttmath::Parser< ValueType >::error protected
code of the last error
Definition at line 344 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::NormalizeStack(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parse(), and ttmath::Parser< ValueType >::Parser().
group
template<class ValueType> int ttmath::Parser< ValueType >::group protected
group character (used when parsing) default zero (not used)
Definition at line 478 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), ttmath::Parser< ValueType >::ReadValue(), and ttmath::Parser< ValueType >::SetGroup().
param_sep
template<class ValueType> int ttmath::Parser< ValueType >::param_sep protected
an additional character used as a separator between function parameters (semicolon is used always)
Definition at line 493 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), ttmath::Parser< ValueType >::ReadOperator(), and ttmath::Parser< ValueType >::SetParamSep().
pfunction_local_variables
template<class ValueType> const FunctionLocalVariables* ttmath::Parser< ValueType >::pfunction_local_variables protected
a pointer to the local variables of a function
Definition at line 393 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::GetValueOfFunctionLocalVariable(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction().
pstop_calculating
template<class ValueType> const volatile StopCalculating* ttmath::Parser< ValueType >::pstop_calculating protected
a pointer to an object which tell us whether we should stop calculating or not
Definition at line 373 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Factorial(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::SetStopObject().
pstring
template<class ValueType> const char* ttmath::Parser< ValueType >::pstring protected
pointer to the currently reading char when an error has occured it may be used to count the index of the wrong character
Definition at line 351 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::ReadMathematicalOperator(), ttmath::Parser< ValueType >::ReadName(), ttmath::Parser< ValueType >::ReadOperator(), ttmath::Parser< ValueType >::ReadOperators(), ttmath::Parser< ValueType >::ReadTokens(), ttmath::Parser< ValueType >::ReadValue(), ttmath::Parser< ValueType >::ReadVariableOrFunction(), and ttmath::Parser< ValueType >::SkipWhiteCharacters().
puser_functions
template<class ValueType> const Objects* ttmath::Parser< ValueType >::puser_functions protected
a pointer to the user-defined functions' table
Definition at line 385 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::SetFunctions().
puser_variables
template<class ValueType> const Objects* ttmath::Parser< ValueType >::puser_variables protected
a pointer to the user-defined variables' table
Definition at line 380 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::GetValueOfUserDefinedVariable(), ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::Parser(), and ttmath::Parser< ValueType >::SetVariables().
stack
template<class ValueType> std::vector<Item> ttmath::Parser< ValueType >::stack
stack on which we're keeping the Items
at the end of parsing we'll have the result here the result don't have to be one value, it can be more than one if we have used a semicolon in the global space e.g. such input string "1+2;3+4" will generate a result: stack[0].value=3 stack[1].value=7
you should check if the stack is not empty, because if there was a syntax error in the input string then we do not have any results on the stack
Definition at line 318 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::AddToStack(), ttmath::Parser< ValueType >::CheckStackIntegrity(), ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::Factorial(), ttmath::Parser< ValueType >::GetValueOfUserDefinedFunction(), ttmath::Parser< ValueType >::HowManyParameters(), ttmath::Parser< ValueType >::NormalizeStack(), ttmath::Parser< ValueType >::OperatorPercentage(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction(), ttmath::Parser< ValueType >::RollingUpFinalBracket(), ttmath::Parser< ValueType >::RollUPStack(), and ttmath::Parser< ValueType >::RollUpStackWithOperatorsPriority().
stack_index
template<class ValueType> unsigned int ttmath::Parser< ValueType >::stack_index protected
index of an object in our stack it's pointing on the place behind the last element for example at the beginning of parsing its value is zero
Definition at line 338 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::AddToStack(), ttmath::Parser< ValueType >::CheckStackIntegrity(), ttmath::Parser< ValueType >::EnsurePlaceOnStack(), ttmath::Parser< ValueType >::HowManyParameters(), ttmath::Parser< ValueType >::NormalizeStack(), ttmath::Parser< ValueType >::OperatorPercentage(), ttmath::Parser< ValueType >::Parse(), ttmath::Parser< ValueType >::RollingUpFinalBracket(), ttmath::Parser< ValueType >::RollUPStack(), and ttmath::Parser< ValueType >::RollUpStackWithOperatorsPriority().
visited_functions
template<class ValueType> std::set<std::string> ttmath::Parser< ValueType >::visited_functions protected
a temporary set using during parsing user defined functions
Definition at line 405 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_AddName(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_CheckStopCondition(), and ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_DeleteName().
visited_variables
template<class ValueType> std::set<std::string> ttmath::Parser< ValueType >::visited_variables protected
a temporary set using during parsing user defined variables
Definition at line 399 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::operator=(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_AddName(), ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_CheckStopCondition(), and ttmath::Parser< ValueType >::RecurrenceParsingVariablesOrFunction_DeleteName().
wide_to_ansi
template<class ValueType> std::string ttmath::Parser< ValueType >::wide_to_ansi protected
temporary object for a whole string when Parse(std::wstring) is used
Definition at line 471 of file ttmathparser.h.
Referenced by ttmath::Parser< ValueType >::Parse().
The documentation for this class was generated from the following file:
ttmathparser.h