TTMath: ttmath::Int< value_size > Class Template Reference
ttmath::Int< value_size > Class Template Reference
Int implements a big integer value with a sign.
#include <ttmathint.h>
Public Member Functions
void SetMax ()
void SetMin ()
void SetSignOne ()
uint ChangeSign ()
void SetSign ()
bool IsSign () const
uint Abs ()
uint Add (const Int< value_size > &ss2)
uint AddInt (uint value, uint index=0)
uint AddTwoInts (uint x2, uint x1, uint index)
uint Sub (const Int< value_size > &ss2)
uint SubInt (uint value, uint index=0)
uint AddOne ()
uint SubOne ()
uint MulInt (sint ss2)
uint Mul (Int< value_size > ss2)
uint Div (Int< value_size > ss2, Int< value_size > *remainder=0)
uint Div (const Int< value_size > &ss2, Int< value_size > &remainder)
uint DivInt (sint ss2, sint *remainder=0)
uint DivInt (sint ss2, sint &remainder)
uint Pow (Int< value_size > pow)
template<uint argument_size>
uint FromInt (const Int< argument_size > &p)
uint FromInt (sint value)
template<uint argument_size>
uint FromUInt (const UInt< argument_size > &p)
template<uint argument_size>
uint FromInt (const UInt< argument_size > &p)
uint FromUInt (uint value)
uint FromInt (uint value)
Int< value_size > & operator= (const Int< value_size > &p)
template<uint argument_size>
Int< value_size > & operator= (const Int< argument_size > &p)
Int< value_size > & operator= (sint i)
Int (sint i)
Int (const Int< value_size > &u)
template<uint argument_size>
Int (const Int< argument_size > &u)
template<uint argument_size>
Int< value_size > & operator= (const UInt< argument_size > &p)
Int< value_size > & operator= (uint i)
Int (uint i)
template<uint argument_size>
Int (const UInt< argument_size > &u)
uint FromUInt (unsigned int i)
uint FromInt (unsigned int i)
uint FromInt (signed int i)
Int< value_size > & operator= (unsigned int i)
Int (unsigned int i)
Int< value_size > & operator= (signed int i)
Int (signed int i)
Int (const char *s)
Int (const std::string &s)
Int (const wchar_t *s)
Int (const std::wstring &s)
Int ()
~Int ()
sint ToInt () const
uint ToUInt (uint &result) const
uint ToInt (uint &result) const
uint ToInt (sint &result) const
uint ToUInt (unsigned int &result) const
uint ToInt (unsigned int &result) const
uint ToInt (int &result) const
void ToString (std::string &result, uint b=10) const
std::string ToString (uint b=10) const
void ToString (std::wstring &result, uint b=10) const
std::wstring ToWString (uint b=10) const
uint FromString (const char *s, uint b=10, const char **after_source=0, bool *value_read=0)
uint FromString (const wchar_t *s, uint b=10, const wchar_t **after_source=0, bool *value_read=0)
uint FromString (const std::string &s, uint b=10)
Int< value_size > & operator= (const char *s)
uint FromString (const std::wstring &s, uint b=10)
Int< value_size > & operator= (const wchar_t *s)
Int< value_size > & operator= (const std::wstring &s)
Int< value_size > & operator= (const std::string &s)
bool operator== (const Int< value_size > &l) const
bool operator!= (const Int< value_size > &l) const
bool operator< (const Int< value_size > &l) const
bool operator> (const Int< value_size > &l) const
bool operator<= (const Int< value_size > &l) const
bool operator>= (const Int< value_size > &l) const
Int< value_size > operator- () const
Int< value_size > operator- (const Int< value_size > &p2) const
Int< value_size > & operator-= (const Int< value_size > &p2)
Int< value_size > operator+ (const Int< value_size > &p2) const
Int< value_size > & operator+= (const Int< value_size > &p2)
Int< value_size > operator * (const Int< value_size > &p2) const
Int< value_size > & operator *= (const Int< value_size > &p2)
Int< value_size > operator/ (const Int< value_size > &p2) const
Int< value_size > & operator/= (const Int< value_size > &p2)
Int< value_size > operator% (const Int< value_size > &p2) const
Int< value_size > & operator%= (const Int< value_size > &p2)
UInt< value_size > & operator++ ()
UInt< value_size > operator++ (int)
UInt< value_size > & operator-- ()
UInt< value_size > operator-- (int)
template<class ostream_type >
void PrintTable (ostream_type &output) const
template<class char_type , class ostream_type >
void PrintLog (const char_type *msg, ostream_type &output) const
template<class char_type , class ostream_type >
void PrintLog (const char_type *msg, uint carry, ostream_type &output) const
uint Size () const
void SetZero ()
void SetOne ()
void Swap (UInt< value_size > &ss2)
void SetFromTable (const unsigned int *temp_table, uint temp_table_len)
uint Rcl (uint bits, uint c=0)
uint Rcr (uint bits, uint c=0)
uint CompensationToLeft ()
bool FindLeadingBit (uint &table_id, uint &index) const
bool FindLowestBit (uint &table_id, uint &index) const
uint GetBit (uint bit_index) const
uint SetBit (uint bit_index)
void BitAnd (const UInt< value_size > &ss2)
void BitOr (const UInt< value_size > &ss2)
void BitXor (const UInt< value_size > &ss2)
void BitNot ()
void BitNot2 ()
uint MulInt (uint ss2)
template<uint result_size>
void MulInt (uint ss2, UInt< result_size > &result) const
uint Mul (const UInt< value_size > &ss2, uint algorithm=100)
void MulBig (const UInt< value_size > &ss2, UInt< value_size *2 > &result, uint algorithm=100)
uint Mul1 (const UInt< value_size > &ss2)
void Mul1Big (const UInt< value_size > &ss2_, UInt< value_size *2 > &result)
uint Mul2 (const UInt< value_size > &ss2)
void Mul2Big (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint Mul3 (const UInt< value_size > &ss2)
void Mul3Big (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint MulFastest (const UInt< value_size > &ss2)
void MulFastestBig (const UInt< value_size > &ss2, UInt< value_size *2 > &result)
uint DivInt (uint divisor, uint *remainder=0)
uint DivInt (uint divisor, uint &remainder)
uint Div (const UInt< value_size > &divisor, UInt< value_size > *remainder=0, uint algorithm=3)
uint Div (const UInt< value_size > &divisor, UInt< value_size > &remainder, uint algorithm=3)
uint Div1 (const UInt< value_size > &divisor, UInt< value_size > *remainder=0)
uint Div1 (const UInt< value_size > &divisor, UInt< value_size > &remainder)
uint Div2 (const UInt< value_size > &divisor, UInt< value_size > *remainder=0)
uint Div2 (const UInt< value_size > &divisor, UInt< value_size > &remainder)
uint Div3 (const UInt< value_size > &ss2, UInt< value_size > *remainder=0)
uint Div3 (const UInt< value_size > &ss2, UInt< value_size > &remainder)
uint Pow (UInt< value_size > pow)
void Sqrt ()
void ClearFirstBits (uint n)
bool IsTheHighestBitSet () const
bool IsTheLowestBitSet () const
bool IsOnlyTheHighestBitSet () const
bool IsOnlyTheLowestBitSet () const
bool IsZero () const
bool AreFirstBitsZero (uint bits) const
uint ToUInt () const
template<class string_type >
void ToStringBase (string_type &result, uint b=10, bool negative=false) const
bool CmpSmaller (const UInt< value_size > &l, sint index=-1) const
bool CmpBigger (const UInt< value_size > &l, sint index=-1) const
bool CmpEqual (const UInt< value_size > &l, sint index=-1) const
bool CmpSmallerEqual (const UInt< value_size > &l, sint index=-1) const
bool CmpBiggerEqual (const UInt< value_size > &l, sint index=-1) const
bool operator< (const UInt< value_size > &l) const
bool operator> (const UInt< value_size > &l) const
bool operator== (const UInt< value_size > &l) const
bool operator!= (const UInt< value_size > &l) const
bool operator<= (const UInt< value_size > &l) const
bool operator>= (const UInt< value_size > &l) const
UInt< value_size > operator- (const UInt< value_size > &p2) const
UInt< value_size > & operator-= (const UInt< value_size > &p2)
UInt< value_size > operator+ (const UInt< value_size > &p2) const
UInt< value_size > & operator+= (const UInt< value_size > &p2)
UInt< value_size > operator * (const UInt< value_size > &p2) const
UInt< value_size > & operator *= (const UInt< value_size > &p2)
UInt< value_size > operator/ (const UInt< value_size > &p2) const
UInt< value_size > & operator/= (const UInt< value_size > &p2)
UInt< value_size > operator% (const UInt< value_size > &p2) const
UInt< value_size > & operator%= (const UInt< value_size > &p2)
UInt< value_size > operator~ () const
UInt< value_size > operator & (const UInt< value_size > &p2) const
UInt< value_size > & operator&= (const UInt< value_size > &p2)
UInt< value_size > operator| (const UInt< value_size > &p2) const
UInt< value_size > & operator|= (const UInt< value_size > &p2)
UInt< value_size > operator^ (const UInt< value_size > &p2) const
UInt< value_size > & operator^= (const UInt< value_size > &p2)
UInt< value_size > operator>> (int move) const
UInt< value_size > & operator>>= (int move)
UInt< value_size > operator<< (int move) const
UInt< value_size > & operator<<= (int move)
uint Add (const UInt< value_size > &ss2, uint c=0)
uint Sub (const UInt< value_size > &ss2, uint c=0)
Static Public Member Functions
template<class char_type , class ostream_type >
static void PrintVectorLog (const char_type *msg, ostream_type &output, const uint *vector, uint vector_len)
template<class char_type , class ostream_type >
static void PrintVectorLog (const char_type *msg, uint carry, ostream_type &output, const uint *vector, uint vector_len)
static uint AddTwoWords (uint a, uint b, uint carry, uint *result)
static uint SubTwoWords (uint a, uint b, uint carry, uint *result)
static void DivTwoWords2 (uint a, uint b, uint c, uint *r, uint *rest)
static uint DivTwoWordsNormalize (uint_ &a_, uint_ &b_, uint_ &c_)
static uint DivTwoWordsUnnormalize (uint u, uint d)
static unsigned int DivTwoWordsCalculate (uint_ u_, unsigned int u3, uint_ v_)
static void MultiplySubtract (uint_ &u_, unsigned int &u3, unsigned int &q, uint_ v_)
static const char * LibTypeStr ()
static LibTypeCode LibType ()
static uint AddVector (const uint *ss1, const uint *ss2, uint ss1_size, uint ss2_size, uint *result)
static uint SubVector (const uint *ss1, const uint *ss2, uint ss1_size, uint ss2_size, uint *result)
static sint FindLeadingBitInWord (uint x)
static sint FindLowestBitInWord (uint x)
static uint SetBitInWord (uint &value, uint bit)
static void MulTwoWords (uint a, uint b, uint *result_high, uint *result_low)
static void DivTwoWords (uint a, uint b, uint c, uint *r, uint *rest)
Data Fields
uint table [value_size]
Protected Member Functions
double ToStringLog2 (uint x) const
Friends
std::ostream & operator<< (std::ostream &s, const Int< value_size > &l)
std::wostream & operator<< (std::wostream &s, const Int< value_size > &l)
std::istream & operator>> (std::istream &s, Int< value_size > &l)
std::wistream & operator>> (std::wistream &s, Int< value_size > &l)
Detailed Description
template<uint value_size>
class ttmath::Int< value_size >
Int implements a big integer value with a sign.
value_size - how many bytes specify our value
on 32bit platforms: value_size=1 -> 4 bytes -> 32 bits
on 64bit platforms: value_size=1 -> 8 bytes -> 64 bits value_size = 1,2,3,4,5,6....
Definition at line 63 of file ttmathint.h.
Constructor & Destructor Documentation
Int() [1/12]
template<uint value_size> ttmath::Int< value_size >::Int (sint i)
a constructor for converting the uint to this class
Definition at line 807 of file ttmathint.h.
     {
         FromInt(i);
     }
Int() [2/12]
template<uint value_size> ttmath::Int< value_size >::Int (const Int< value_size > & u)
a copy constructor
Definition at line 816 of file ttmathint.h.
                                    : UInt<value_size>()
     {
         FromInt(u);
     }
Int() [3/12]
template<uint value_size> template<uint argument_size> ttmath::Int< value_size >::Int (const Int< argument_size > & u)
a constructor for copying from another types
Definition at line 826 of file ttmathint.h.
     {
         // look that 'size' we still set as 'value_size' and not as u.value_size
         FromInt(u);
     }
Int() [4/12]
template<uint value_size> ttmath::Int< value_size >::Int (uint i)
a constructor for converting the uint to this class
Definition at line 862 of file ttmathint.h.
     {
         FromUInt(i);
     }
Int() [5/12]
template<uint value_size> template<uint argument_size> ttmath::Int< value_size >::Int (const UInt< argument_size > & u)
a constructor for copying from another types
Definition at line 872 of file ttmathint.h.
     {
         // look that 'size' we still set as 'value_size' and not as u.value_size
         FromUInt(u);
     }
Int() [6/12]
template<uint value_size> ttmath::Int< value_size >::Int (unsigned int i)
a constructor for converting 32 bit unsigned int to this class this constructor is created only on a 64bit platform***
Definition at line 1037 of file ttmathint.h.
     {
         FromUInt(i);
     }
Int() [7/12]
template<uint value_size> ttmath::Int< value_size >::Int (signed int i)
a constructor for converting 32 bit signed int to this class this constructor is created only on a 64bit platform***
Definition at line 1059 of file ttmathint.h.
     {
         FromInt(i);
     }
Int() [8/12]
template<uint value_size> ttmath::Int< value_size >::Int (const char * s)
a constructor for converting string to this class (with the base=10)
Definition at line 1071 of file ttmathint.h.
     {
         FromString(s);
     }
Int() [9/12]
template<uint value_size> ttmath::Int< value_size >::Int (const std::string & s)
a constructor for converting a string to this class (with the base=10)
Definition at line 1080 of file ttmathint.h.
     {
         FromString( s.c_str() );
     }
Int() [10/12]
template<uint value_size> ttmath::Int< value_size >::Int (const wchar_t * s)
a constructor for converting string to this class (with the base=10)
Definition at line 1091 of file ttmathint.h.
     {
         FromString(s);
     }
Int() [11/12]
template<uint value_size> ttmath::Int< value_size >::Int (const std::wstring & s)
a constructor for converting a string to this class (with the base=10)
Definition at line 1100 of file ttmathint.h.
     {
         FromString( s.c_str() );
     }
Int() [12/12]
template<uint value_size> ttmath::Int< value_size >::Int ()
a default constructor
we don't clear table etc.
Definition at line 1113 of file ttmathint.h.
     {
     }
~Int()
template<uint value_size> ttmath::Int< value_size >::~Int ()
the destructor
Definition at line 1121 of file ttmathint.h.
     {
     }
Member Function Documentation
Abs()
template<uint value_size> uint ttmath::Int< value_size >::Abs ()
it sets an absolute value
it can return carry (1) (look on ChangeSign() for details)
Definition at line 168 of file ttmathint.h.
     {
         if( !IsSign() )
             return 0;
     return ChangeSign();
     }
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Int< exp >::Div(), ttmath::Int< exp >::DivInt(), ttmath::Int< exp >::Mul(), and ttmath::Int< exp >::MulInt().
Add() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::Add (const Int< value_size > & ss2)
this method adds two value with a sign and returns a carry
we're using methods from the base class because values are stored with U2 we must only make the carry correction
this = p1(=this) + p2
when p1>=0 i p2>=0 carry is set when the highest bit of value is set when p1<0 i p2<0 carry is set when the highest bit of value is clear when p1>=0 i p2<0 carry will never be set when p1<0 i p2>=0 carry will never be set
Definition at line 220 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         bool p2_is_sign = ss2.IsSign();
         UInt<value_size>::Add(ss2);
     return CorrectCarryAfterAdding(p1_is_sign, p2_is_sign);
     }
Referenced by ttmath::Big< exp, man >::Exp(), and ttmath::Big< exp, man >::MulUInt().
Add() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Add (const UInt< value_size > & ss2, uint c = 0) inherited
basic mathematic functions
this method adding ss2 to the this and adding carry if it's defined (this = this + ss2 + c)
this method is created only on a 64bit platform***
c must be zero or one (might be a bigger value than 1) function returns carry (1) (if it was)
Definition at line 158 of file ttmathuint_x86_64.h.
     {
     uint b = value_size;
     uint * p1 = table;
     const uint * p2 = ss2.table;
         // we don't have to use TTMATH_REFERENCE_ASSERT here
         // this algorithm doesn't require it
         #ifndef __GNUC__
             c = ttmath_adc_x64(p1,p2,b,c);
         #endif
         #ifdef __GNUC__
         uint dummy, dummy2;
             /*
                 this part should be compiled with gcc
             */
             __asm__ __volatile__(
                 "xorq %%rdx, %%rdx              \n"
                 "negq %%rax                     \n"     // CF=1 if rax!=0 , CF=0 if rax==0
             "1:                                 \n"
                 "movq (%%rsi,%%rdx,8), %%rax    \n"
                 "adcq %%rax, (%%rbx,%%rdx,8)    \n"
                 "incq %%rdx                     \n"
                 "decq %%rcx                     \n"
             "jnz 1b                             \n"
                 "adcq %%rcx, %%rcx              \n"
                 : "=c" (c), "=a" (dummy), "=d" (dummy2)
                 : "0" (b),  "1" (c), "b" (p1), "S" (p2)
                 : "cc", "memory" );
         #endif
         TTMATH_LOGC("UInt::Add", c)
     return c;
     }
Referenced by ttmath::Int< exp >::Add(), and ttmath::UInt< man >::Sqrt().
AddInt()
template<uint value_size> uint ttmath::Int< value_size >::AddInt (uint value, uint index = 0)
this method adds one unsigned word (at a specific position) and returns a carry (if it was)
look at a description in UInt<>::AddInt(...)
Definition at line 237 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         UInt<value_size>::AddInt(value, index);
     return CorrectCarryAfterAdding(p1_is_sign, false);
     }
Referenced by ttmath::Big< exp, man >::FromBig().
AddOne()
template<uint value_size> uint ttmath::Int< value_size >::AddOne ()
this method adds one to the value and returns carry
Definition at line 327 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         UInt<value_size>::AddOne();
     return CorrectCarryAfterAdding(p1_is_sign, false);
     }
Referenced by ttmath::Int< exp >::operator++().
AddTwoInts()
template<uint value_size> uint ttmath::Int< value_size >::AddTwoInts (uint x2, uint x1, uint index)
this method adds two unsigned words to the existing value and these words begin on the 'index' position
index should be equal or smaller than value_size-2 (index <= value_size-2) x1 - lower word, x2 - higher word
look at a description in UInt<>::AddTwoInts(...)
Definition at line 256 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         UInt<value_size>::AddTwoInts(x2, x1, index);
     return CorrectCarryAfterAdding(p1_is_sign, false);
     }
AddVector()
template<uint value_size> uint ttmath::UInt< value_size >::AddVector (const uint * ss1, const uint * ss2, uint ss1_size, uint ss2_size, uint * result) static inherited
this static method addes one vector to the other 'ss1' is larger in size or equal to 'ss2'
ss1 points to the first (larger) vector
ss2 points to the second vector
ss1_size - size of the ss1 (and size of the result too)
ss2_size - size of the ss2
result - is the result vector (which has size the same as ss1: ss1_size)
Example: ss1_size is 5, ss2_size is 3 ss1: ss2: result (output): 5 1 5+1 4 3 4+3 2 7 2+7 6 6 9 9 of course the carry is propagated and will be returned from the last item (this method is used by the Karatsuba multiplication algorithm)
Definition at line 387 of file ttmathuint_x86_64.h.
     {
         TTMATH_ASSERT( ss1_size >= ss2_size )
         uint c;
         #ifndef __GNUC__
              c = ttmath_addvector_x64(ss1, ss2, ss1_size, ss2_size, result);
         #endif
         #ifdef __GNUC__
         uint dummy1, dummy2, dummy3;
         uint rest = ss1_size - ss2_size;
             //  this part should be compiled with gcc
             __asm__ __volatile__(
                 "mov %%rdx, %%r8                    \n"
                 "xor %%rdx, %%rdx                   \n"   // rdx = 0, cf = 0
             "1:                                     \n"
                 "mov (%%rsi,%%rdx,8), %%rax         \n"
                 "adc (%%rbx,%%rdx,8), %%rax         \n"
                 "mov %%rax, (%%rdi,%%rdx,8)         \n"
                 "inc %%rdx                          \n"
                 "dec %%rcx                          \n"
             "jnz 1b                                 \n"
                 "adc %%rcx, %%rcx                   \n"   // rcx has the cf state
                 "or %%r8, %%r8                      \n"
                 "jz 3f                              \n"
                 "xor %%rbx, %%rbx                   \n"   // ebx = 0
                 "neg %%rcx                          \n"   // setting cf from rcx
                 "mov %%r8, %%rcx                    \n"   // rcx=rest and is != 0
             "2:                                     \n"
                 "mov (%%rsi, %%rdx, 8), %%rax       \n"
                 "adc %%rbx, %%rax                   \n"
                 "mov %%rax, (%%rdi, %%rdx, 8)       \n"
                 "inc %%rdx                          \n"
                 "dec %%rcx                          \n"
             "jnz 2b                                 \n"
                 "adc %%rcx, %%rcx                   \n"
             "3:                                     \n"
                 : "=a" (dummy1), "=b" (dummy2), "=c" (c),       "=d" (dummy3)
                 :                "1" (ss2),     "2" (ss2_size), "3" (rest),   "S" (ss1),  "D" (result)
                 : "%r8", "cc", "memory" );
         #endif
         TTMATH_VECTOR_LOGC("UInt::AddVector", c, result, ss1_size)
     return c;
     }
AreFirstBitsZero()
template<uint value_size> bool ttmath::UInt< value_size >::AreFirstBitsZero (uint bits) const inherited
returning true if first 'bits' bits are equal zero
Definition at line 2618 of file ttmathuint.h.
     {
         TTMATH_ASSERT( bits <= value_size * TTMATH_BITS_PER_UINT )
         uint index = bits / TTMATH_BITS_PER_UINT;
         uint rest  = bits % TTMATH_BITS_PER_UINT;
         uint i;
         for(i=0 ; i<index ; ++i)
             if(table[i] != 0 )
                 return false;
         if( rest == 0 )
             return true;
         uint mask = TTMATH_UINT_MAX_VALUE >> (TTMATH_BITS_PER_UINT - rest);
     return (table[i] & mask) == 0;
     }
BitAnd()
template<uint value_size> void ttmath::UInt< value_size >::BitAnd (const UInt< value_size > & ss2) inherited
this method performs a bitwise operation AND
Definition at line 743 of file ttmathuint.h.
     {
         for(uint x=0 ; x<value_size ; ++x)
             table[x] &= ss2.table[x];
         TTMATH_LOG("UInt::BitAnd")
     }
Referenced by ttmath::Big< exp, man >::BitAnd().
BitNot()
template<uint value_size> void ttmath::UInt< value_size >::BitNot () inherited
this method performs a bitwise operation NOT
Definition at line 779 of file ttmathuint.h.
     {
         for(uint x=0 ; x<value_size ; ++x)
             table[x] = ~table[x];
         TTMATH_LOG("UInt::BitNot")
     }
Referenced by ttmath::UInt< man >::operator~().
BitNot2()
template<uint value_size> void ttmath::UInt< value_size >::BitNot2 () inherited
this method performs a bitwise operation NOT but only on the range of <0, leading_bit>
for example: BitNot2(8) = BitNot2(1000(bin)) = 111(bin) = 7
Definition at line 795 of file ttmathuint.h.
     {
     uint table_id, index;
         if( FindLeadingBit(table_id, index) )
         {
             for(uint x=0 ; x<table_id ; ++x)
                 table[x] = ~table[x];
             uint mask  = TTMATH_UINT_MAX_VALUE;
             uint shift = TTMATH_BITS_PER_UINT - index - 1;
             if(shift)
                 mask >>= shift;
             table[table_id] ^= mask;
         }
         else
             table[0] = 1;
         TTMATH_LOG("UInt::BitNot2")
     }
BitOr()
template<uint value_size> void ttmath::UInt< value_size >::BitOr (const UInt< value_size > & ss2) inherited
this method performs a bitwise operation OR
Definition at line 755 of file ttmathuint.h.
     {
         for(uint x=0 ; x<value_size ; ++x)
             table[x] |= ss2.table[x];
         TTMATH_LOG("UInt::BitOr")
     }
Referenced by ttmath::Big< exp, man >::BitOr().
BitXor()
template<uint value_size> void ttmath::UInt< value_size >::BitXor (const UInt< value_size > & ss2) inherited
this method performs a bitwise operation XOR
Definition at line 767 of file ttmathuint.h.
     {
         for(uint x=0 ; x<value_size ; ++x)
             table[x] ^= ss2.table[x];
         TTMATH_LOG("UInt::BitXor")
     }
Referenced by ttmath::Big< exp, man >::BitXor().
ChangeSign()
template<uint value_size> uint ttmath::Int< value_size >::ChangeSign ()
we change the sign of the value
if it isn't possible to change the sign this method returns 1 else return 0 and changing the sign
Definition at line 105 of file ttmathint.h.
     {
         /*
             if the value is equal that one which has been returned from SetMin
             (only the highest bit is set) that means we can't change sign
             because the value is too big (bigger about one)
             e.g. when value_size = 1 and value is -2147483648 we can't change it to the
             2147483648 because the max value which can be held is 2147483647
             we don't change the value and we're using this fact somewhere in some methods
             (if we look on our value without the sign we get the correct value
             eg. -2147483648 in Int<1> will be 2147483648 on the UInt<1> type)
         */
         if( UInt<value_size>::IsOnlyTheHighestBitSet() )
             return 1;
         UInt<value_size> temp(*this);
         UInt<value_size>::SetZero();
         UInt<value_size>::Sub(temp);
     return 0;
     }
Referenced by ttmath::Int< exp >::Abs(), ttmath::Big< exp, man >::FromInt(), ttmath::Int< exp >::operator-(), ttmath::Int< exp >::Pow(), ttmath::Big< exp, man >::Pow(), ttmath::Int< exp >::SetSign(), and ttmath::Big< exp, man >::ToInt().
ClearFirstBits()
template<uint value_size> void ttmath::UInt< value_size >::ClearFirstBits (uint n) inherited
this method sets n first bits to value zero
For example: let n=2 then if there's a value 111 (bin) there'll be '100' (bin)
Definition at line 2508 of file ttmathuint.h.
     {
         if( n >= value_size*TTMATH_BITS_PER_UINT )
         {
             SetZero();
             TTMATH_LOG("UInt::ClearFirstBits")
             return;
         }
         uint * p = table;
         // first we're clearing the whole words
         while( n >= TTMATH_BITS_PER_UINT )
         {
             *p++ = 0;
             n   -= TTMATH_BITS_PER_UINT;
         }
         if( n == 0 )
         {
             TTMATH_LOG("UInt::ClearFirstBits")
             return;
         }
         // and then we're clearing one word which has left
         // mask -- all bits are set to one
         uint mask = TTMATH_UINT_MAX_VALUE;
         mask = mask << n;
         (*p) &= mask;
         TTMATH_LOG("UInt::ClearFirstBits")
     }
Referenced by ttmath::Big< exp, man >::SkipFraction().
CmpBigger()
template<uint value_size> bool ttmath::UInt< value_size >::CmpBigger (const UInt< value_size > & l, sint index = -1) const inherited
this method returns true if 'this' is bigger than 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
I introduced it for some kind of optimization made in the second division algorithm (Div2)
Definition at line 3606 of file ttmathuint.h.
     {
     sint i;
         if( index==-1 || index>=sint(value_size) )
             i = value_size - 1;
         else
             i = index;
         for( ; i>=0 ; --i)
         {
             if( table[i] != l.table[i] )
                 return table[i] > l.table[i];
         }
     // they're equal
     return false;
     }
CmpBiggerEqual()
template<uint value_size> bool ttmath::UInt< value_size >::CmpBiggerEqual (const UInt< value_size > & l, sint index = -1) const inherited
this method returns true if 'this' is bigger than or equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
Definition at line 3689 of file ttmathuint.h.
     {
     sint i;
         if( index==-1 || index>=sint(value_size) )
             i = value_size - 1;
         else
             i = index;
         for( ; i>=0 ; --i)
         {
             if( table[i] != l.table[i] )
                 return table[i] > l.table[i];
         }
     // they're equal
     return true;
     }
CmpEqual()
template<uint value_size> bool ttmath::UInt< value_size >::CmpEqual (const UInt< value_size > & l, sint index = -1) const inherited
this method returns true if 'this' is equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
Definition at line 3634 of file ttmathuint.h.
     {
     sint i;
         if( index==-1 || index>=sint(value_size) )
             i = value_size - 1;
         else
             i = index;
         for( ; i>=0 ; --i)
             if( table[i] != l.table[i] )
                 return false;
     return true;
     }
CmpSmaller()
template<uint value_size> bool ttmath::UInt< value_size >::CmpSmaller (const UInt< value_size > & l, sint index = -1) const inherited
methods for comparing
this method returns true if 'this' is smaller than 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word) I introduced it for some kind of optimization made in the second division algorithm (Div2)
Definition at line 3575 of file ttmathuint.h.
     {
     sint i;
         if( index==-1 || index>=sint(value_size) )
             i = value_size - 1;
         else
             i = index;
         for( ; i>=0 ; --i)
         {
             if( table[i] != l.table[i] )
                 return table[i] < l.table[i];
         }
     // they're equal
     return false;
     }
CmpSmallerEqual()
template<uint value_size> bool ttmath::UInt< value_size >::CmpSmallerEqual (const UInt< value_size > & l, sint index = -1) const inherited
this method returns true if 'this' is smaller than or equal 'l'
'index' is an index of the first word from will be the comparison performed (note: we start the comparison from back - from the last word, when index is -1 /default/ it is automatically set into the last word)
Definition at line 3660 of file ttmathuint.h.
     {
     sint i;
         if( index==-1 || index>=sint(value_size) )
             i = value_size - 1;
         else
             i = index;
         for( ; i>=0 ; --i)
         {
             if( table[i] != l.table[i] )
                 return table[i] < l.table[i];
         }
     // they're equal
     return true;
     }
CompensationToLeft()
template<uint value_size> uint ttmath::UInt< value_size >::CompensationToLeft () inherited
this method moves all bits into the left side (it returns value how many bits have been moved)
Definition at line 598 of file ttmathuint.h.
     {
         uint moving = 0;
         // a - index a last word which is different from zero
         sint a;
         for(a=value_size-1 ; a>=0 && table[a]==0 ; --a);
         if( a < 0 )
             return moving; // all words in table have zero
         if( a != value_size-1 )
         {
             moving += ( value_size-1 - a ) * TTMATH_BITS_PER_UINT;
             // moving all words
             sint i;
             for(i=value_size-1 ; a>=0 ; --i, --a)
                 table[i] = table[a];
             // setting the rest word to zero
             for(; i>=0 ; --i)
                 table[i] = 0;
         }
         uint moving2 = FindLeadingBitInWord( table[value_size-1] );
         // moving2 is different from -1 because the value table[value_size-1]
         // is not zero
         moving2 = TTMATH_BITS_PER_UINT - moving2 - 1;
         Rcl(moving2);
         TTMATH_LOG("UInt::CompensationToLeft")
     return moving + moving2;
     }
Referenced by ttmath::Big< exp, man >::FromInt(), ttmath::Big< exp, man >::FromUInt(), ttmath::Big< exp, man >::MulUInt(), and ttmath::Big< exp, man >::Standardizing().
Div() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::Div (Int< value_size > ss2, Int< value_size > * remainder = 0)
division this = this / ss2 returned values:
0 - ok
1 - division by zero
for example: (result means 'this')
20 / 3 --> result: 6 remainder: 2
-20 / 3 --> result: -6 remainder: -2
20 / -3 --> result: -6 remainder: 2
-20 / -3 --> result: 6 remainder: -2
in other words: this(old) = ss2 * this(new)(result) + remainder
Definition at line 480 of file ttmathint.h.
     {
     bool ss1_is_sign, ss2_is_sign;
         ss1_is_sign = IsSign();
         ss2_is_sign = ss2.IsSign();
         /*
             we don't have to test the carry from Abs as well as in Mul
         */
         Abs();
         ss2.Abs();
         uint c = UInt<value_size>::Div(ss2, remainder);
         if( ss1_is_sign != ss2_is_sign )
             SetSign();
         if( ss1_is_sign && remainder )
             remainder->SetSign();
     return c;
     }
Referenced by ttmath::Int< exp >::Pow().
Div() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0, uint algorithm = 3) inherited
division this = this / ss2
return values:
0 - ok
1 - division by zero
'this' will be the quotient
'remainder' - remainder
Definition at line 1626 of file ttmathuint.h.
     {
         switch( algorithm )
         {
         case 1:
             return Div1(divisor, remainder);
         case 2:
             return Div2(divisor, remainder);
         case 3:
         default:
             return Div3(divisor, remainder);
         }
     }
Referenced by ttmath::Int< exp >::Div().
Div1() [1/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div1 (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0) inherited
the first division algorithm (radix 2)
Definition at line 1752 of file ttmathuint.h.
     {
     uint m,n, test;
         test = Div_StandardTest(divisor, m, n, remainder);
         if( test < 2 )
             return test;
         if( !remainder )
         {
             UInt<value_size> rem;
         return Div1_Calculate(divisor, rem);
         }
     return Div1_Calculate(divisor, *remainder);
     }
Referenced by ttmath::UInt< man >::Div(), and ttmath::UInt< man >::Div1().
Div1() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div1 (const UInt< value_size > & divisor, UInt< value_size > & remainder) inherited
the first division algorithm (radix 2)
Definition at line 1775 of file ttmathuint.h.
     {
         return Div1(divisor, &remainder);
     }
Div2() [1/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div2 (const UInt< value_size > & divisor, UInt< value_size > * remainder = 0) inherited
the second division algorithm
return values:
0 - ok
1 - division by zero
Definition at line 1862 of file ttmathuint.h.
     {
         if( this == &divisor )
         {
             UInt<value_size> divisor_copy(divisor);
             return Div2Ref(divisor_copy, remainder);
         }
         else
         {
             return Div2Ref(divisor, remainder);
         }
     }
Referenced by ttmath::UInt< man >::Div(), and ttmath::UInt< man >::Div2().
Div2() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div2 (const UInt< value_size > & divisor, UInt< value_size > & remainder) inherited
the second division algorithm
return values:
0 - ok
1 - division by zero
Definition at line 1883 of file ttmathuint.h.
     {
         return Div2(divisor, &remainder);
     }
Div3() [1/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div3 (const UInt< value_size > & ss2, UInt< value_size > * remainder = 0) inherited
the third division algorithm
Definition at line 2108 of file ttmathuint.h.
     {
         if( this == &ss2 )
         {
             UInt<value_size> copy_ss2(ss2);
             return Div3Ref(copy_ss2, remainder);
         }
         else
         {
             return Div3Ref(ss2, remainder);
         }
     }
Referenced by ttmath::UInt< man >::Div(), and ttmath::UInt< man >::Div3().
Div3() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Div3 (const UInt< value_size > & ss2, UInt< value_size > & remainder) inherited
the third division algorithm
Definition at line 2125 of file ttmathuint.h.
     {
         return Div3(ss2, &remainder);
     }
DivInt() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::DivInt (sint ss2, sint * remainder = 0)
division this = this / ss2 (ss2 is int) returned values:
0 - ok
1 - division by zero
for example: (result means 'this')
20 / 3 --> result: 6 remainder: 2
-20 / 3 --> result: -6 remainder: -2
20 / -3 --> result: -6 remainder: 2
-20 / -3 --> result: 6 remainder: -2
in other words: this(old) = ss2 * this(new)(result) + remainder
Definition at line 524 of file ttmathint.h.
     {
     bool ss1_is_sign, ss2_is_sign;
         ss1_is_sign = IsSign();
         /*
             we don't have to test the carry from Abs as well as in Mul
         */
         Abs();
         if( ss2 < 0 )
         {
             ss2 = -ss2;
             ss2_is_sign = true;
         }
         else
         {
             ss2_is_sign = false;
         }
         uint rem;
         uint c = UInt<value_size>::DivInt((uint)ss2, &rem);
         if( ss1_is_sign != ss2_is_sign )
             SetSign();
         if( remainder )
         {
             if( ss1_is_sign )
                 *remainder = -sint(rem);
             else
                 *remainder = sint(rem);
         }
     return c;
     }
DivInt() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::DivInt (uint divisor, uint * remainder = 0) inherited
Division
division by one unsigned word
returns 1 when divisor is zero
Definition at line 1568 of file ttmathuint.h.
     {
         if( divisor == 0 )
         {
             if( remainder )
                 *remainder = 0; // this is for convenience, without it the compiler can report that 'remainder' is uninitialized
             TTMATH_LOG("UInt::DivInt")
         return 1;
         }
         if( divisor == 1 )
         {
             if( remainder )
                 *remainder = 0;
             TTMATH_LOG("UInt::DivInt")
         return 0;
         }
         UInt<value_size> dividend(*this);
         SetZero();
         sint i;  // i must be with a sign
         uint r = 0;
         // we're looking for the last word in ss1
         for(i=value_size-1 ; i>0 && dividend.table[i]==0 ; --i);
         for( ; i>=0 ; --i)
             DivTwoWords(r, dividend.table[i], divisor, &table[i], &r);
         if( remainder )
             *remainder = r;
         TTMATH_LOG("UInt::DivInt")
     return 0;
     }
Referenced by ttmath::Int< exp >::DivInt(), and ttmath::UInt< man >::ToStringBase().
DivTwoWords()
template<uint value_size> void ttmath::UInt< value_size >::DivTwoWords (uint a, uint b, uint c, uint * r, uint * rest) static inherited
Division
this method calculates 64bits word a:b / 32bits c (a higher, b lower word) r = a:b / c and rest - remainder
this method is created only on a 64bit platform***
WARNING: if r (one word) is too small for the result or c is equal zero there'll be a hardware interruption (0) and probably the end of your program
Definition at line 1132 of file ttmathuint_x86_64.h.
     {
         uint r_;
         uint rest_;
         /*
             these variables have similar meaning like those in
             the multiplication algorithm MulTwoWords
         */
         TTMATH_ASSERT( c != 0 )
         #ifndef __GNUC__
             ttmath_div_x64(&a,&b,c);
             r_    = a;
             rest_ = b;
         #endif
         #ifdef __GNUC__
             __asm__ (
             "divq %%rcx             \n"
             : "=a" (r_), "=d" (rest_)
             : "d" (a), "a" (b), "c" (c)
             : "cc" );
         #endif
         *r = r_;
         *rest = rest_;
     }
FindLeadingBit()
template<uint value_size> bool ttmath::UInt< value_size >::FindLeadingBit (uint & table_id, uint & index) const inherited
this method looks for the highest set bit
result:
if 'this' is not zero: return value - true, 'table_id' - the index of a word <0..value_size-1>, 'index' - the index of this set bit in the word <0..TTMATH_BITS_PER_UINT)
if 'this' is zero: return value - false, both 'table_id' and 'index' are zero
Definition at line 649 of file ttmathuint.h.
     {
         for(table_id=value_size-1 ; table_id!=0 && table[table_id]==0 ; --table_id);
         if( table_id==0 && table[table_id]==0 )
         {
             // is zero
             index = 0;
         return false;
         }
         // table[table_id] is different from 0
         index = FindLeadingBitInWord( table[table_id] );
     return true;
     }
Referenced by ttmath::UInt< man >::BitNot2(), and ttmath::UInt< man >::ToStringBase().
FindLowestBit()
template<uint value_size> bool ttmath::UInt< value_size >::FindLowestBit (uint & table_id, uint & index) const inherited
this method looks for the smallest set bit
result:
if 'this' is not zero: return value - true, 'table_id' - the index of a word <0..value_size-1>, 'index' - the index of this set bit in the word <0..TTMATH_BITS_PER_UINT)
if 'this' is zero: return value - false, both 'table_id' and 'index' are zero
Definition at line 681 of file ttmathuint.h.
     {
         for(table_id=0 ; table_id<value_size && table[table_id]==0 ; ++table_id);
         if( table_id >= value_size )
         {
             // is zero
             index    = 0;
             table_id = 0;
         return false;
         }
         // table[table_id] is different from 0
         index = FindLowestBitInWord( table[table_id] );
     return true;
     }
FromInt() [1/6]
template<uint value_size> template<uint argument_size> uint ttmath::Int< value_size >::FromInt (const Int< argument_size > & p)
this method converts an Int<another_size> type into this class
this operation has mainly sense if the value from p can be held in this type
it returns a carry if the value 'p' is too big
Definition at line 697 of file ttmathint.h.
     {
         return FromUIntOrInt(p, false);
     }
Referenced by ttmath::Big< exp, man >::FromBig(), ttmath::Int< exp >::FromInt(), ttmath::Int< exp >::Int(), and ttmath::Int< exp >::operator=().
FromInt() [2/6]
template<uint value_size> uint ttmath::Int< value_size >::FromInt (sint value)
this method converts the sint type into this class
Definition at line 706 of file ttmathint.h.
     {
     uint fill = ( value<0 ) ? TTMATH_UINT_MAX_VALUE : 0;
         for(uint i=1 ; i<value_size ; ++i)
             UInt<value_size>::table[i] = fill;
         UInt<value_size>::table[0] = uint(value);
         // there'll never be a carry here
     return 0;
     }
FromInt() [3/6]
template<uint value_size> template<uint argument_size> uint ttmath::Int< value_size >::FromInt (const UInt< argument_size > & p)
this method converts UInt<another_size> into this class
Definition at line 734 of file ttmathint.h.
     {
         return FromUIntOrInt(p, true);
     }
FromInt() [4/6]
template<uint value_size> uint ttmath::Int< value_size >::FromInt (uint value)
this method converts the uint type into this class
Definition at line 762 of file ttmathint.h.
     {
         return FromUInt(value);
     }
FromInt() [5/6]
template<uint value_size> uint ttmath::Int< value_size >::FromInt (unsigned int i)
this method converts 32 bit unsigned int type to this class this operator is created only on a 64bit platform***
Definition at line 1005 of file ttmathint.h.
     {
         return FromUInt(i);
     }
FromInt() [6/6]
template<uint value_size> uint ttmath::Int< value_size >::FromInt (signed int i)
this method converts 32 bit signed int type to this class this operator is created only on a 64bit platform***
Definition at line 1015 of file ttmathint.h.
     {
         return FromInt(sint(i));
     }
FromString() [1/4]
template<uint value_size> uint ttmath::Int< value_size >::FromString (const char * s, uint b = 10, const char ** after_source = 0, bool * value_read = 0)
this method converts a string into its value it returns carry=1 if the value will be too big or an incorrect base 'b' is given
string is ended with a non-digit value, for example: "-12" will be translated to -12 as well as: "- 12foo" will be translated to -12 too
existing first white characters will be ommited (between '-' and a first digit can be white characters too)
after_source (if exists) is pointing at the end of the parsed string
value_read (if exists) tells whether something has actually been read (at least one digit)
Definition at line 1453 of file ttmathint.h.
     {
         return FromStringBase(s, b, after_source, value_read);
     }
Referenced by ttmath::Int< exp >::FromString(), ttmath::Int< exp >::Int(), and ttmath::Int< exp >::operator=().
FromString() [2/4]
template<uint value_size> uint ttmath::Int< value_size >::FromString (const wchar_t * s, uint b = 10, const wchar_t ** after_source = 0, bool * value_read = 0)
this method converts a string into its value
Definition at line 1462 of file ttmathint.h.
     {
         return FromStringBase(s, b, after_source, value_read);
     }
FromString() [3/4]
template<uint value_size> uint ttmath::Int< value_size >::FromString (const std::string & s, uint b = 10)
this method converts a string into its value it returns carry=1 if the value will be too big or an incorrect base 'b' is given
Definition at line 1472 of file ttmathint.h.
     {
         return FromString( s.c_str(), b );
     }
FromString() [4/4]
template<uint value_size> uint ttmath::Int< value_size >::FromString (const std::wstring & s, uint b = 10)
this method converts a string into its value it returns carry=1 if the value will be too big or an incorrect base 'b' is given
Definition at line 1496 of file ttmathint.h.
     {
         return FromString( s.c_str(), b );
     }
FromUInt() [1/3]
template<uint value_size> template<uint argument_size> uint ttmath::Int< value_size >::FromUInt (const UInt< argument_size > & p)
this method converts UInt<another_size> into this class
Definition at line 724 of file ttmathint.h.
     {
         return FromUIntOrInt(p, true);
     }
Referenced by ttmath::Int< exp >::FromInt(), ttmath::Int< exp >::FromUInt(), ttmath::Int< exp >::Int(), and ttmath::Int< exp >::operator=().
FromUInt() [2/3]
template<uint value_size> uint ttmath::Int< value_size >::FromUInt (uint value)
this method converts the uint type into this class
Definition at line 743 of file ttmathint.h.
     {
         for(uint i=1 ; i<value_size ; ++i)
             UInt<value_size>::table[i] = 0;
         UInt<value_size>::table[0] = value;
         // there can be a carry here when the size of this value is equal one word
         // and the 'value' has the highest bit set
         if( value_size==1 && (value & TTMATH_UINT_HIGHEST_BIT)!=0 )
             return 1;
     return 0;
     }
FromUInt() [3/3]
template<uint value_size> uint ttmath::Int< value_size >::FromUInt (unsigned int i)
this method converts 32 bit unsigned int type to this class this operator is created only on a 64bit platform***
Definition at line 995 of file ttmathint.h.
     {
         return FromUInt(uint(i));
     }
GetBit()
template<uint value_size> uint ttmath::UInt< value_size >::GetBit (uint bit_index) const inherited
getting the 'bit_index' bit
bit_index bigger or equal zero
Definition at line 706 of file ttmathuint.h.
     {
         TTMATH_ASSERT( bit_index < value_size * TTMATH_BITS_PER_UINT )
         uint index = bit_index / TTMATH_BITS_PER_UINT;
         uint bit   = bit_index % TTMATH_BITS_PER_UINT;
         uint temp = table[index];
         uint res  = SetBitInWord(temp, bit);
     return res;
     }
Referenced by ttmath::Big< exp, man >::Mod2().
IsOnlyTheHighestBitSet()
template<uint value_size> bool ttmath::UInt< value_size >::IsOnlyTheHighestBitSet () const inherited
returning true if only the highest bit is set
Definition at line 2565 of file ttmathuint.h.
     {
 #ifdef __clang__
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wtautological-compare"
 #endif
         for(uint i=0 ; i<value_size-1 ; ++i)
             if( table[i] != 0 )
                 return false;
 #ifdef __clang__
 #pragma clang diagnostic pop
 #endif
         if( table[value_size-1] != TTMATH_UINT_HIGHEST_BIT )
             return false;
     return true;
     }
IsOnlyTheLowestBitSet()
template<uint value_size> bool ttmath::UInt< value_size >::IsOnlyTheLowestBitSet () const inherited
returning true if only the lowest bit is set
Definition at line 2589 of file ttmathuint.h.
     {
         if( table[0] != 1 )
             return false;
         for(uint i=1 ; i<value_size ; ++i)
             if( table[i] != 0 )
                 return false;
     return true;
     }
IsSign()
template<uint value_size> bool ttmath::Int< value_size >::IsSign () const
this method returns true if there's the sign
(the highest bit will be converted to the bool)
Definition at line 156 of file ttmathint.h.
     {
         return UInt<value_size>::IsTheHighestBitSet();
     }
Referenced by ttmath::Int< exp >::Abs(), ttmath::Int< exp >::Add(), ttmath::Int< exp >::AddInt(), ttmath::Int< exp >::AddOne(), ttmath::Int< exp >::AddTwoInts(), ttmath::Int< exp >::Div(), ttmath::Int< exp >::DivInt(), ttmath::Big< exp, man >::FromInt(), ttmath::Big< exp, man >::IsInteger(), ttmath::Int< exp >::Mul(), ttmath::Int< exp >::MulInt(), ttmath::Int< exp >::Pow(), ttmath::Big< exp, man >::Pow(), ttmath::Big< exp, man >::RemainFraction(), ttmath::Int< exp >::SetSign(), ttmath::Big< exp, man >::SkipFraction(), ttmath::Int< exp >::Sub(), ttmath::Int< exp >::SubInt(), ttmath::Int< exp >::SubOne(), ttmath::Int< exp >::ToInt(), and ttmath::Int< exp >::ToUInt().
IsTheHighestBitSet()
template<uint value_size> bool ttmath::UInt< value_size >::IsTheHighestBitSet () const inherited
this method returns true if the highest bit of the value is set
Definition at line 2547 of file ttmathuint.h.
     {
         return (table[value_size-1] & TTMATH_UINT_HIGHEST_BIT) != 0;
     }
Referenced by ttmath::Int< exp >::IsSign(), and ttmath::Big< exp, man >::Standardizing().
IsTheLowestBitSet()
template<uint value_size> bool ttmath::UInt< value_size >::IsTheLowestBitSet () const inherited
this method returns true if the lowest bit of the value is set
Definition at line 2556 of file ttmathuint.h.
     {
         return (*table & 1) != 0;
     }
IsZero()
template<uint value_size> bool ttmath::UInt< value_size >::IsZero () const inherited
this method returns true if the value is equal zero
Definition at line 2605 of file ttmathuint.h.
     {
         for(uint i=0 ; i<value_size ; ++i)
             if(table[i] != 0)
                 return false;
     return true;
     }
Referenced by ttmath::Big< exp, man >::Pow(), ttmath::UInt< man >::Pow(), ttmath::UInt< man >::Sqrt(), and ttmath::UInt< man >::ToStringBase().
LibType()
template<uint value_size> LibTypeCode ttmath::UInt< value_size >::LibType () static inherited
returning the currect type of the library
Definition at line 126 of file ttmathuint_x86_64.h.
     {
         #ifndef __GNUC__
             LibTypeCode info = asm_vc_64;
         #endif
         #ifdef __GNUC__
             LibTypeCode info = asm_gcc_64;
         #endif
     return info;
     }
Referenced by ttmath::Big< exp, man >::LibType().
LibTypeStr()
template<uint value_size> const char * ttmath::UInt< value_size >::LibTypeStr () static inherited
returning the string represents the currect type of the library we have following types: asm_vc_32 - with asm code designed for Microsoft Visual C++ (32 bits) asm_gcc_32 - with asm code designed for GCC (32 bits) asm_vc_64 - with asm for VC (64 bit) asm_gcc_64 - with asm for GCC (64 bit) no_asm_32 - pure C++ version (32 bit) - without any asm code no_asm_64 - pure C++ version (64 bit) - without any asm code
Definition at line 108 of file ttmathuint_x86_64.h.
     {
         #ifndef __GNUC__
             static const char info[] = "asm_vc_64";
         #endif
         #ifdef __GNUC__
             static const char info[] = "asm_gcc_64";
         #endif
     return info;
     }
Referenced by ttmath::Big< exp, man >::LibTypeStr().
Mul() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::Mul (Int< value_size > ss2)
multiplication this = this * ss2
it returns carry if the result is too big (we're using the method from the base class but we have to make one correction in account of signs)
Definition at line 440 of file ttmathint.h.
     {
     bool ss1_is_sign, ss2_is_sign;
     uint c;
         ss1_is_sign = IsSign();
         ss2_is_sign = ss2.IsSign();
         /*
             we don't have to check the carry from Abs (values will be correct
             because next we're using the method Mul from the base class UInt
             which is without a sign)
         */
         Abs();
         ss2.Abs();
         c  = UInt<value_size>::Mul(ss2);
         c += CheckMinCarry(ss1_is_sign, ss2_is_sign);
         if( ss1_is_sign != ss2_is_sign )
             SetSign();
     return c;
     }
Mul() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Mul (const UInt< value_size > & ss2, uint algorithm = 100) inherited
the multiplication 'this' = 'this' * ss2
algorithm: 100 - means automatically choose the fastest algorithm
Definition at line 923 of file ttmathuint.h.
     {
         switch( algorithm )
         {
         case 1:
             return Mul1(ss2);
         case 2:
             return Mul2(ss2);
         case 3:
             return Mul3(ss2);
         case 100:
         default:
             return MulFastest(ss2);
         }
     }
Referenced by ttmath::Int< exp >::Mul(), and ttmath::UInt< man >::Pow().
Mul1()
template<uint value_size> uint ttmath::UInt< value_size >::Mul1 (const UInt< value_size > & ss2) inherited
multiplication: this = this * ss2 can return carry
Definition at line 1023 of file ttmathuint.h.
     {
         if( this == &ss2 )
         {
             UInt<value_size> copy_ss2(ss2);
             return Mul1Ref(copy_ss2);
         }
         else
         {
             return Mul1Ref(ss2);
         }
     }
Referenced by ttmath::UInt< man >::Mul(), and ttmath::UInt< man >::Mul1Big().
Mul1Big()
template<uint value_size> void ttmath::UInt< value_size >::Mul1Big (const UInt< value_size > & ss2_, UInt< value_size *2 > & result) inherited
multiplication: result = this * ss2
result is twice bigger than 'this' and 'ss2' this method never returns carry
Definition at line 1043 of file ttmathuint.h.
     {
     UInt<value_size*2> ss2;
     uint i;
         // copying *this into result and ss2_ into ss2
         for(i=0 ; i<value_size ; ++i)
         {
             result.table[i] = table[i];
             ss2.table[i]    = ss2_.table[i];
         }
         // cleaning the highest bytes in result and ss2
         for( ; i < value_size*2 ; ++i)
         {
             result.table[i] = 0;
             ss2.table[i]    = 0;
         }
         // multiply
         // (there will not be a carry)
         result.Mul1( ss2 );
         TTMATH_LOG("UInt::Mul1Big")
     }
Referenced by ttmath::UInt< man >::MulBig().
Mul2()
template<uint value_size> uint ttmath::UInt< value_size >::Mul2 (const UInt< value_size > & ss2) inherited
the second version of the multiplication algorithm
this algorithm is similar to the 'schoolbook method' which is done by hand
multiplication: this = this * ss2
it returns carry if it has been
Definition at line 1082 of file ttmathuint.h.
     {
     UInt<value_size*2> result;
     uint i, c = 0;
         Mul2Big(ss2, result);
         // copying result
         for(i=0 ; i<value_size ; ++i)
             table[i] = result.table[i];
         // testing carry
         for( ; i<value_size*2 ; ++i)
             if( result.table[i] != 0 )
             {
                 c = 1;
                 break;
             }
         TTMATH_LOGC("UInt::Mul2", c)
     return c;
     }
Referenced by ttmath::UInt< man >::Mul().
Mul2Big()
template<uint value_size> void ttmath::UInt< value_size >::Mul2Big (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inherited
multiplication: result = this * ss2
result is twice bigger than this and ss2 this method never returns carry
Definition at line 1113 of file ttmathuint.h.
     {
         Mul2Big2<value_size>(table, ss2.table, result);
         TTMATH_LOG("UInt::Mul2Big")
     }
Referenced by ttmath::UInt< man >::Mul2(), ttmath::UInt< man >::MulBig(), and ttmath::UInt< man >::MulFastestBig().
Mul3()
template<uint value_size> uint ttmath::UInt< value_size >::Mul3 (const UInt< value_size > & ss2) inherited
multiplication: this = this * ss2
This is Karatsuba Multiplication algorithm, we're using it when value_size is greater than or equal to TTMATH_USE_KARATSUBA_MULTIPLICATION_FROM_SIZE macro (defined in ttmathuint.h). If value_size is smaller then we're using Mul2Big() instead.
Karatsuba multiplication: Assume we have:
this = x = x1*B^m + x0
ss2  = y = y1*B^m + y0
where x0 and y0 are less than B^m the product from multiplication we can show as: x*y = (x1*B^m + x0)(y1*B^m + y0) = z2*B^(2m) + z1*B^m + z0 where
z2 = x1*y1
z1 = x1*y0 + x0*y1
z0 = x0*y0
this is standard schoolbook algorithm with O(n^2), Karatsuba observed that z1 can be given in other form:
z1 = (x1 + x0)*(y1 + y0) - z2 - z0    / z1 = (x1*y1 + x1*y0 + x0*y1 + x0*y0) - x1*y1 - x0*y0 = x1*y0 + x0*y1 /
and to calculate the multiplication we need only three multiplications (with some additions and subtractions)
Our objects 'this' and 'ss2' we divide into two parts and by using recurrence we calculate the multiplication. Karatsuba multiplication has O(n^(ln(3)/ln(2)))
Definition at line 1212 of file ttmathuint.h.
     {
     UInt<value_size*2> result;
     uint i, c = 0;
         Mul3Big(ss2, result);
         // copying result
         for(i=0 ; i<value_size ; ++i)
             table[i] = result.table[i];
         // testing carry
         for( ; i<value_size*2 ; ++i)
             if( result.table[i] != 0 )
             {
                 c = 1;
                 break;
             }
         TTMATH_LOGC("UInt::Mul3", c)
     return c;
     }
Referenced by ttmath::UInt< man >::Mul().
Mul3Big()
template<uint value_size> void ttmath::UInt< value_size >::Mul3Big (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inherited
multiplication: result = this * ss2
result is twice bigger than this and ss2, this method never returns carry, (Karatsuba multiplication)
Definition at line 1245 of file ttmathuint.h.
     {
         Mul3Big2<value_size>(table, ss2.table, result.table);
         TTMATH_LOG("UInt::Mul3Big")
     }
Referenced by ttmath::UInt< man >::Mul3(), ttmath::UInt< man >::MulBig(), and ttmath::UInt< man >::MulFastestBig().
MulBig()
template<uint value_size> void ttmath::UInt< value_size >::MulBig (const UInt< value_size > & ss2, UInt< value_size *2 > & result, uint algorithm = 100) inherited
the multiplication 'result' = 'this' * ss2
since the 'result' is twice bigger than 'this' and 'ss2' this method never returns a carry
algorithm: 100 - means automatically choose the fastest algorithm
Definition at line 951 of file ttmathuint.h.
     {
         switch( algorithm )
         {
         case 1:
             Mul1Big(ss2, result);
             break;
         case 2:
             Mul2Big(ss2, result);
             break;
         case 3:
             Mul3Big(ss2, result);
             break;
         case 100:
         default:
             MulFastestBig(ss2, result);
         }
     }
MulFastest()
template<uint value_size> uint ttmath::UInt< value_size >::MulFastest (const UInt< value_size > & ss2) inherited
multiplication this = this * ss2
Definition at line 1479 of file ttmathuint.h.
     {
     UInt<value_size*2> result;
     uint i, c = 0;
         MulFastestBig(ss2, result);
         // copying result
         for(i=0 ; i<value_size ; ++i)
             table[i] = result.table[i];
         // testing carry
         for( ; i<value_size*2 ; ++i)
             if( result.table[i] != 0 )
             {
                 c = 1;
                 break;
             }
         TTMATH_LOGC("UInt::MulFastest", c)
     return c;
     }
Referenced by ttmath::UInt< man >::Mul().
MulFastestBig()
template<uint value_size> void ttmath::UInt< value_size >::MulFastestBig (const UInt< value_size > & ss2, UInt< value_size *2 > & result) inherited
multiplication result = this * ss2
this method is trying to select the fastest algorithm (in the future this method can be improved)
Definition at line 1510 of file ttmathuint.h.
     {
         if( value_size < TTMATH_USE_KARATSUBA_MULTIPLICATION_FROM_SIZE )
         {
             Mul2Big(ss2, result);
             return;
         }
         uint x1size  = value_size, x2size  = value_size;
         uint x1start = 0,          x2start = 0;
         for(x1size=value_size ; x1size>0 && table[x1size-1]==0 ; --x1size);
         for(x2size=value_size ; x2size>0 && ss2.table[x2size-1]==0 ; --x2size);
         if( x1size==0 || x2size==0 )
         {
             // either 'this' or 'ss2' is equal zero - the result is zero too
             result.SetZero();
             return;
         }
         for(x1start=0 ; x1start<x1size && table[x1start]==0 ; ++x1start);
         for(x2start=0 ; x2start<x2size && ss2.table[x2start]==0 ; ++x2start);
         uint distancex1 = x1size - x1start;
         uint distancex2 = x2size - x2start;
         if( distancex1 < 3 || distancex2 < 3 )
         {
             // either 'this' or 'ss2' have only 2 (or 1) items different from zero (side by side)
             // (this condition in the future can be improved)
             Mul2Big3<value_size>(table, ss2.table, result, x1start, x1size, x2start, x2size);
             return;
         }
         // Karatsuba multiplication
         Mul3Big(ss2, result);
         TTMATH_LOG("UInt::MulFastestBig")
     }
Referenced by ttmath::UInt< man >::MulBig(), and ttmath::UInt< man >::MulFastest().
MulInt() [1/3]
template<uint value_size> uint ttmath::Int< value_size >::MulInt (sint ss2)
multiplication: this = this * ss2
it can return a carry
Definition at line 398 of file ttmathint.h.
     {
     bool ss1_is_sign, ss2_is_sign;
     uint c;
         ss1_is_sign = IsSign();
         /*
             we don't have to check the carry from Abs (values will be correct
             because next we're using the method MulInt from the base class UInt
             which is without a sign)
         */
         Abs();
         if( ss2 < 0 )
         {
             ss2 = -ss2;
             ss2_is_sign = true;
         }
         else
         {
             ss2_is_sign = false;
         }
         c  = UInt<value_size>::MulInt((uint)ss2);
         c += CheckMinCarry(ss1_is_sign, ss2_is_sign);
         if( ss1_is_sign != ss2_is_sign )
             SetSign();
     return c;
     }
MulInt() [2/3]
template<uint value_size> uint ttmath::UInt< value_size >::MulInt (uint ss2) inherited
Multiplication
multiplication: this = this * ss2
it can return a carry
Definition at line 835 of file ttmathuint.h.
     {
     uint r1, r2, x1;
     uint c = 0;
         UInt<value_size> u(*this);
         SetZero();
         if( ss2 == 0 )
         {
             TTMATH_LOGC("UInt::MulInt(uint)", 0)
             return 0;
         }
         for(x1=0 ; x1<value_size-1 ; ++x1)
         {
             MulTwoWords(u.table[x1], ss2, &r2, &r1);
             c += AddTwoInts(r2,r1,x1);
         }
         // x1 = value_size-1  (last word)
         MulTwoWords(u.table[x1], ss2, &r2, &r1);
         c += (r2!=0) ? 1 : 0;
         c += AddInt(r1, x1);
         TTMATH_LOGC("UInt::MulInt(uint)", c)
     return (c==0)? 0 : 1;
     }
Referenced by ttmath::Int< exp >::MulInt(), and ttmath::Big< exp, man >::MulUInt().
MulInt() [3/3]
template<uint value_size> template<uint result_size> void ttmath::UInt< value_size >::MulInt (uint ss2, UInt< result_size > & result) const inherited
multiplication: result = this * ss2
we're using this method only when result_size is greater than value_size if so there will not be a carry
Definition at line 873 of file ttmathuint.h.
     {
     TTMATH_ASSERT( result_size > value_size )
     uint r2,r1;
     uint x1size=value_size;
     uint x1start=0;
         result.SetZero();
         if( ss2 == 0 )
         {
             TTMATH_VECTOR_LOG("UInt::MulInt(uint, UInt<>)", result.table, result_size)
             return;
         }
         if( value_size > 2 )
         {
             // if the value_size is smaller than or equal to 2
             // there is no sense to set x1size and x1start to another values
             for(x1size=value_size ; x1size>0 && table[x1size-1]==0 ; --x1size);
             if( x1size == 0 )
             {
                 TTMATH_VECTOR_LOG("UInt::MulInt(uint, UInt<>)", result.table, result_size)
                 return;
             }
             for(x1start=0 ; x1start<x1size && table[x1start]==0 ; ++x1start);
         }
         for(uint x1=x1start ; x1<x1size ; ++x1)
         {
             MulTwoWords(table[x1], ss2, &r2, &r1 );
             result.AddTwoInts(r2,r1,x1);
         }
         TTMATH_VECTOR_LOG("UInt::MulInt(uint, UInt<>)", result.table, result_size)
     return;
     }
MulTwoWords()
template<uint value_size> void ttmath::UInt< value_size >::MulTwoWords (uint a, uint b, uint * result_high, uint * result_low) static inherited
Multiplication
multiplication: result_high:result_low = a * b
result_high - higher word of the result
result_low - lower word of the result
this methos never returns a carry this method is used in the second version of the multiplication algorithms
this method is created only on a 64bit platform***
Definition at line 1072 of file ttmathuint_x86_64.h.
     {
     /*
         we must use these temporary variables in order to inform the compilator
         that value pointed with result1 and result2 has changed
         this has no effect in visual studio but it's usefull when
         using gcc and options like -O
     */
     uint result1_;
     uint result2_;
         #ifndef __GNUC__
             result1_ = _umul128(a,b,&result2_);
         #endif
         #ifdef __GNUC__
         __asm__ (
             "mulq %%rdx         \n"
             : "=a" (result1_), "=d" (result2_)
             : "0" (a),         "1" (b)
             : "cc" );
         #endif
         *result_low  = result1_;
         *result_high = result2_;
     }
operator++() [1/2]
template<uint value_size> UInt<value_size>& ttmath::Int< value_size >::operator++ ()
Prefix operator e.g. ++variable
Definition at line 1767 of file ttmathint.h.
     {
         AddOne();
     return *this;
     }
operator++() [2/2]
template<uint value_size> UInt<value_size> ttmath::Int< value_size >::operator++ (int)
Postfix operator e.g. variable++
Definition at line 1778 of file ttmathint.h.
     {
     UInt<value_size> temp( *this );
         AddOne();
     return temp;
     }
operator-() [1/2]
template<uint value_size> Int<value_size> ttmath::Int< value_size >::operator- () const
standard mathematical operators
an operator for changing the sign
it's not changing 'this' but the changed value will be returned
Definition at line 1660 of file ttmathint.h.
     {
     Int<value_size> temp(*this);
         temp.ChangeSign();
     return temp;
     }
operator-() [2/2]
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator- (const UInt< value_size > & p2) const inherited
standard mathematical operators
Definition at line 3755 of file ttmathuint.h.
     {
     UInt<value_size> temp(*this);
         temp.Sub(p2);
     return temp;
     }
operator=() [1/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (const Int< value_size > & p)
the default assignment operator
Definition at line 771 of file ttmathint.h.
     {
         FromInt(p);
     return *this;
     }
operator=() [2/11]
template<uint value_size> template<uint argument_size> Int<value_size>& ttmath::Int< value_size >::operator= (const Int< argument_size > & p)
this operator converts an Int<another_size> type to this class
it doesn't return a carry
Definition at line 785 of file ttmathint.h.
     {
         FromInt(p);
     return *this;
     }
operator=() [3/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (sint i)
this method converts the sint type to this class
Definition at line 796 of file ttmathint.h.
     {
         FromInt(i);
     return *this;
     }
operator=() [4/11]
template<uint value_size> template<uint argument_size> Int<value_size>& ttmath::Int< value_size >::operator= (const UInt< argument_size > & p)
this operator converts an UInt<another_size> type to this class
it doesn't return a carry
Definition at line 840 of file ttmathint.h.
     {
         FromUInt(p);
     return *this;
     }
operator=() [5/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (uint i)
this method converts the Uint type to this class
Definition at line 851 of file ttmathint.h.
     {
         FromUInt(i);
     return *this;
     }
operator=() [6/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (unsigned int i)
this method converts 32 bit unsigned int type to this class this operator is created only on a 64bit platform***
Definition at line 1025 of file ttmathint.h.
     {
         FromUInt(i);
     return *this;
     }
operator=() [7/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (signed int i)
this operator converts 32 bit signed int type to this class this operator is created only on a 64bit platform***
Definition at line 1047 of file ttmathint.h.
     {
         FromInt(i);
     return *this;
     }
operator=() [8/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (const char * s)
this operator converts a string into its value (with base = 10)
Definition at line 1481 of file ttmathint.h.
     {
         FromString(s);
     return *this;
     }
operator=() [9/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (const wchar_t * s)
this operator converts a string into its value (with base = 10)
Definition at line 1505 of file ttmathint.h.
     {
         FromString(s);
     return *this;
     }
operator=() [10/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (const std::wstring & s)
this operator converts a string into its value (with base = 10)
Definition at line 1516 of file ttmathint.h.
     {
         FromString( s.c_str() );
     return *this;
     }
operator=() [11/11]
template<uint value_size> Int<value_size>& ttmath::Int< value_size >::operator= (const std::string & s)
this operator converts a string into its value (with base = 10)
Definition at line 1529 of file ttmathint.h.
     {
         FromString( s.c_str() );
     return *this;
     }
operator==()
template<uint value_size> bool ttmath::Int< value_size >::operator== (const Int< value_size > & l) const
methods for comparing
Definition at line 1545 of file ttmathint.h.
     {
         return UInt<value_size>::operator==(l);
     }
operator~()
template<uint value_size> UInt<value_size> ttmath::UInt< value_size >::operator~ () const inherited
bitwise operators
Definition at line 3895 of file ttmathuint.h.
     {
         UInt<value_size> temp( *this );
         temp.BitNot();
     return temp;
     }
Pow() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::Pow (Int< value_size > pow)
power this = this ^ pow
return values:
0 - ok
1 - carry
2 - incorrect arguments 0^0 or 0^(-something)
Definition at line 608 of file ttmathint.h.
     {
         if( !pow.IsSign() )
             return Pow2(pow);
         if( UInt<value_size>::IsZero() )
             // if 'pow' is negative then
             // 'this' must be different from zero
             return 2;
         if( pow.ChangeSign() )
             return 1;
         Int<value_size> t(*this);
         uint c_temp = t.Pow2(pow);
         if( c_temp > 0 )
             return c_temp;
         UInt<value_size>::SetOne();
         if( Div(t) )
             return 1;
     return 0;
     }
Pow() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Pow (UInt< value_size > pow) inherited
power this = this ^ pow binary algorithm (r-to-l)
return values:
0 - ok
1 - carry
2 - incorrect argument (0^0)
Definition at line 2425 of file ttmathuint.h.
     {
         if(pow.IsZero() && IsZero())
             // we don't define zero^zero
             return 2;
         UInt<value_size> start(*this);
         UInt<value_size> result;
         result.SetOne();
         uint c = 0;
         while( !c )
         {
             if( pow.table[0] & 1 )
                 c += result.Mul(start);
             pow.Rcr2_one(0);
             if( pow.IsZero() )
                 break;
             c += start.Mul(start);
         }
         *this = result;
         TTMATH_LOGC("UInt::Pow(UInt<>)", c)
     return (c==0)? 0 : 1;
     }
PrintLog() [1/2]
template<uint value_size> template<class char_type , class ostream_type > void ttmath::UInt< value_size >::PrintLog (const char_type * msg, ostream_type & output) const inherited
this method is used when macro TTMATH_DEBUG_LOG is defined
Definition at line 159 of file ttmathuint.h.
     {
         PrintVectorLog(msg, output, table, value_size);
     }
PrintLog() [2/2]
template<uint value_size> template<class char_type , class ostream_type > void ttmath::UInt< value_size >::PrintLog (const char_type * msg, uint carry, ostream_type & output) const inherited
this method is used when macro TTMATH_DEBUG_LOG is defined
Definition at line 169 of file ttmathuint.h.
     {
         PrintVectorLog(msg, output, table, value_size);
         output << " carry: " << carry << std::endl;
     }
PrintTable()
template<uint value_size> template<class ostream_type > void ttmath::UInt< value_size >::PrintTable (ostream_type & output) const inherited
some methods used for debugging purposes
this method is only for debugging purposes or when we want to make a table of a variable (constant) in ttmathbig.h
it prints the table in a nice form of several columns
Definition at line 97 of file ttmathuint.h.
     {
         // how many columns there'll be
         const int columns = 8;
         int c = 1;
         for(int i=value_size-1 ; i>=0 ; --i)
         {
             output << "0x" << std::setfill('0');
             #ifdef TTMATH_PLATFORM32
                 output << std::setw(8);
             #else
                 output << std::setw(16);
             #endif
             output << std::hex << table[i];
             if( i>0 )
             {
                 output << ", ";
                 if( ++c > columns )
                 {
                     output << std::endl;
                     c = 1;
                 }
             }
         }
         output << std::dec << std::endl;
     }
PrintVectorLog() [1/2]
template<uint value_size> template<class char_type , class ostream_type > static void ttmath::UInt< value_size >::PrintVectorLog (const char_type * msg, ostream_type & output, const uint * vector, uint vector_len) static inherited
this method is used when macro TTMATH_DEBUG_LOG is defined
Definition at line 135 of file ttmathuint.h.
     {
         output << msg << std::endl;
         for(uint i=0 ; i<vector_len ; ++i)
             output << " table[" << i << "]: " << vector[i] << std::endl;
     }
Referenced by ttmath::UInt< man >::PrintLog(), and ttmath::UInt< man >::PrintVectorLog().
PrintVectorLog() [2/2]
template<uint value_size> template<class char_type , class ostream_type > static void ttmath::UInt< value_size >::PrintVectorLog (const char_type * msg, uint carry, ostream_type & output, const uint * vector, uint vector_len) static inherited
this method is used when macro TTMATH_DEBUG_LOG is defined
Definition at line 148 of file ttmathuint.h.
     {
         PrintVectorLog(msg, output, vector, vector_len);
         output << " carry: " << carry << std::endl;
     }
Rcl()
template<uint value_size> uint ttmath::UInt< value_size >::Rcl (uint bits, uint c = 0) inherited
moving all bits into the left side 'bits' times return value <- this <- C
bits is from a range of <0, man * TTMATH_BITS_PER_UINT> or it can be even bigger then all bits will be set to 'c'
the value c will be set into the lowest bits and the method returns state of the last moved bit
Definition at line 460 of file ttmathuint.h.
     {
     uint last_c    = 0;
     uint rest_bits = bits;
         if( bits == 0 )
             return 0;
         if( bits >= TTMATH_BITS_PER_UINT )
             RclMoveAllWords(rest_bits, last_c, bits, c);
         if( rest_bits == 0 )
         {
             TTMATH_LOG("UInt::Rcl")
             return last_c;
         }
         // rest_bits is from 1 to TTMATH_BITS_PER_UINT-1 now
         if( rest_bits == 1 )
         {
             last_c = Rcl2_one(c);
         }
         else if( rest_bits == 2 )
         {
             // performance tests showed that for rest_bits==2 it's better to use Rcl2_one twice instead of Rcl2(2,c)
             Rcl2_one(c);
             last_c = Rcl2_one(c);
         }
         else
         {
             last_c = Rcl2(rest_bits, c);
         }
         TTMATH_LOGC("UInt::Rcl", last_c)
     return last_c;
     }
Referenced by ttmath::UInt< man >::CompensationToLeft(), and ttmath::Big< exp, man >::RemainFraction().
Rcr()
template<uint value_size> uint ttmath::UInt< value_size >::Rcr (uint bits, uint c = 0) inherited
moving all bits into the right side 'bits' times c -> this -> return value
bits is from a range of <0, man * TTMATH_BITS_PER_UINT> or it can be even bigger then all bits will be set to 'c'
the value c will be set into the highest bits and the method returns state of the last moved bit
Definition at line 555 of file ttmathuint.h.
     {
     uint last_c    = 0;
     uint rest_bits = bits;
         if( bits == 0 )
             return 0;
         if( bits >= TTMATH_BITS_PER_UINT )
             RcrMoveAllWords(rest_bits, last_c, bits, c);
         if( rest_bits == 0 )
         {
             TTMATH_LOG("UInt::Rcr")
             return last_c;
         }
         // rest_bits is from 1 to TTMATH_BITS_PER_UINT-1 now
         if( rest_bits == 1 )
         {
             last_c = Rcr2_one(c);
         }
         else if( rest_bits == 2 )
         {
             // performance tests showed that for rest_bits==2 it's better to use Rcr2_one twice instead of Rcr2(2,c)
             Rcr2_one(c);
             last_c = Rcr2_one(c);
         }
         else
         {
             last_c = Rcr2(rest_bits, c);
         }
         TTMATH_LOGC("UInt::Rcr", last_c)
     return last_c;
     }
Referenced by ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::MulUInt(), ttmath::Big< exp, man >::Pow(), and ttmath::UInt< man >::Sqrt().
SetBit()
template<uint value_size> uint ttmath::UInt< value_size >::SetBit (uint bit_index) inherited
setting the 'bit_index' bit and returning the last state of the bit
bit_index bigger or equal zero
Definition at line 726 of file ttmathuint.h.
     {
         TTMATH_ASSERT( bit_index < value_size * TTMATH_BITS_PER_UINT )
         uint index = bit_index / TTMATH_BITS_PER_UINT;
         uint bit   = bit_index % TTMATH_BITS_PER_UINT;
         uint res   = SetBitInWord(table[index], bit);
         TTMATH_LOG("UInt::SetBit")
     return res;
     }
SetBitInWord()
template<uint value_size> uint ttmath::UInt< value_size >::SetBitInWord (uint & value, uint bit) static inherited
this method sets a special bit in the 'value' and returns the last state of the bit (zero or one)
this method is created only on a 64bit platform***
bit is from <0,63>
e.g. uint x = 100; uint bit = SetBitInWord(x, 3); now: x = 108 and bit = 0
Definition at line 1020 of file ttmathuint_x86_64.h.
     {
         TTMATH_ASSERT( bit < TTMATH_BITS_PER_UINT )
         uint old_bit;
         uint v = value;
         #ifndef __GNUC__
             old_bit = _bittestandset64((__int64*)&value,bit) != 0;
         #endif
         #ifdef __GNUC__
             __asm__ (
             "btsq %%rbx, %%rax      \n"
             "setc %%bl              \n"
             "movzx %%bl, %%rbx      \n"
             : "=a" (v), "=b" (old_bit)
             : "0" (v),  "1" (bit)
             : "cc" );
         #endif
         value = v;
     return old_bit;
     }
SetFromTable()
template<uint value_size> void ttmath::UInt< value_size >::SetFromTable (const unsigned int * temp_table, uint temp_table_len) inherited
this method copies the value stored in an another table (warning: first values in temp_table are the highest words – it's different from our table)
this method is created only on a 64bit platform***
we copy as many words as it is possible
if temp_table_len is bigger than value_size we'll try to round the lowest word from table depending on the last not used bit in temp_table (this rounding isn't a perfect rounding – look at the description below)
and if temp_table_len is smaller than value_size we'll clear the rest words in the table
warning: we're using 'temp_table' as a pointer at 32bit words
Definition at line 325 of file ttmathuint.h.
     {
         uint temp_table_index = 0;
         sint i; // 'i' with a sign
         for(i=value_size-1 ; i>=0 && temp_table_index<temp_table_len; --i, ++temp_table_index)
         {
             table[i] = uint(temp_table[ temp_table_index ]) << 32;
             ++temp_table_index;
             if( temp_table_index<temp_table_len )
                 table[i] |= temp_table[ temp_table_index ];
         }
         // rounding mantissa
         if( temp_table_index < temp_table_len )
         {
             if( (temp_table[temp_table_index] & TTMATH_UINT_HIGHEST_BIT) != 0 )
             {
                 /*
                     very simply rounding
                     if the bit from not used last word from temp_table is set to one
                     we're rouding the lowest word in the table
                     in fact there should be a normal addition but
                     we don't use Add() or AddTwoInts() because these methods
                     can set a carry and then there'll be a small problem
                     for optimization
                 */
                 if( table[0] != TTMATH_UINT_MAX_VALUE )
                     ++table[0];
             }
         }
         // cleaning the rest of the mantissa
         for( ; i >= 0 ; --i)
             table[i] = 0;
         TTMATH_LOG("UInt::SetFromTable")
     }
Referenced by ttmath::Big< exp, man >::SetE(), ttmath::Big< exp, man >::SetLn10(), and ttmath::Big< exp, man >::SetLn2().
SetMax()
template<uint value_size> void ttmath::Int< value_size >::SetMax ()
this method sets the max value which this class can hold (all bits will be one besides the last one)
Definition at line 71 of file ttmathint.h.
     {
         UInt<value_size>::SetMax();
         UInt<value_size>::table[value_size-1] = ~ TTMATH_UINT_HIGHEST_BIT;
     }
Referenced by ttmath::Big< exp, man >::SetMax(), and ttmath::Big< exp, man >::SetMin().
SetMin()
template<uint value_size> void ttmath::Int< value_size >::SetMin ()
this method sets the min value which this class can hold (all bits will be zero besides the last one which is one)
Definition at line 82 of file ttmathint.h.
     {
         UInt<value_size>::SetZero();
         UInt<value_size>::table[value_size-1] = TTMATH_UINT_HIGHEST_BIT;
     }
SetOne()
template<uint value_size> void ttmath::UInt< value_size >::SetOne () inherited
this method sets one
Definition at line 202 of file ttmathuint.h.
     {
         SetZero();
         table[0] = 1;
         TTMATH_LOG("UInt::SetOne")
     }
Referenced by ttmath::Int< exp >::Pow(), and ttmath::UInt< man >::Pow().
SetSign()
template<uint value_size> void ttmath::Int< value_size >::SetSign ()
this method sets the sign
samples
1 -> -1
-2 -> -2
from a positive value we make a negative value, if the value is negative we do nothing
Definition at line 141 of file ttmathint.h.
     {
         if( IsSign() )
             return;
         ChangeSign();
     }
Referenced by ttmath::Int< exp >::Div(), ttmath::Int< exp >::DivInt(), ttmath::Int< exp >::Mul(), and ttmath::Int< exp >::MulInt().
SetSignOne()
template<uint value_size> void ttmath::Int< value_size >::SetSignOne ()
this method sets -1 as the value (-1 is equal the max value in an unsigned type)
Definition at line 93 of file ttmathint.h.
     {
         UInt<value_size>::SetMax();
     }
SetZero()
template<uint value_size> void ttmath::UInt< value_size >::SetZero () inherited
this method sets zero
Definition at line 188 of file ttmathuint.h.
     {
         // in the future here can be 'memset'
         for(uint i=0 ; i<value_size ; ++i)
             table[i] = 0;
         TTMATH_LOG("UInt::SetZero")
     }
Referenced by ttmath::Int< exp >::ChangeSign(), ttmath::UInt< man >::ClearFirstBits(), ttmath::Big< exp, man >::Exp(), ttmath::UInt< man >::MulFastestBig(), ttmath::UInt< man >::MulInt(), ttmath::Int< exp >::SetMin(), ttmath::UInt< man >::SetMin(), ttmath::UInt< man >::SetOne(), ttmath::Big< exp, man >::SetOne(), ttmath::Big< exp, man >::SetZero(), and ttmath::UInt< man >::Sqrt().
Size()
template<uint value_size> uint ttmath::UInt< value_size >::Size () const inherited
this method returns the size of the table
Definition at line 179 of file ttmathuint.h.
     {
         return value_size;
     }
Sqrt()
template<uint value_size> void ttmath::UInt< value_size >::Sqrt () inherited
square root e.g. Sqrt(9) = 3 ('digit-by-digit' algorithm)
Definition at line 2461 of file ttmathuint.h.
     {
     UInt<value_size> bit, temp;
         if( IsZero() )
             return;
         UInt<value_size> value(*this);
         SetZero();
         bit.SetZero();
         bit.table[value_size-1] = (TTMATH_UINT_HIGHEST_BIT >> 1);
         while( bit > value )
             bit.Rcr(2);
         while( !bit.IsZero() )
         {
             temp = *this;
             temp.Add(bit);
             if( value >= temp )
             {
                 value.Sub(temp);
                 Rcr(1);
                 Add(bit);
             }
             else
             {
                 Rcr(1);
             }
             bit.Rcr(2);
         }
         TTMATH_LOG("UInt::Sqrt")
     }
Sub() [1/2]
template<uint value_size> uint ttmath::Int< value_size >::Sub (const Int< value_size > & ss2)
this method subtracts two values with a sign
we don't use the previous Add because the method ChangeSign can sometimes return carry
this = p1(=this) - p2
when p1>=0 i p2>=0 carry will never be set
when p1<0 i p2<0 carry will never be set
when p1>=0 i p2<0 carry is set when the highest bit of value is set
when p1<0 i p2>=0 carry is set when the highest bit of value is clear
Definition at line 299 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         bool p2_is_sign = ss2.IsSign();
         UInt<value_size>::Sub(ss2);
     return CorrectCarryAfterSubtracting(p1_is_sign, p2_is_sign);
     }
Referenced by ttmath::Big< exp, man >::Add(), ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::RemainFraction(), and ttmath::Big< exp, man >::Standardizing().
Sub() [2/2]
template<uint value_size> uint ttmath::UInt< value_size >::Sub (const UInt< value_size > & ss2, uint c = 0) inherited
this method's subtracting ss2 from the 'this' and subtracting carry if it has been defined (this = this - ss2 - c)
this method is created only on a 64bit platform***
c must be zero or one (might be a bigger value than 1) function returns carry (1) (if it was)
Definition at line 460 of file ttmathuint_x86_64.h.
     {
     uint b = value_size;
     uint * p1 = table;
     const uint * p2 = ss2.table;
         // we don't have to use TTMATH_REFERENCE_ASSERT here
         // this algorithm doesn't require it
         #ifndef __GNUC__
             c = ttmath_sbb_x64(p1,p2,b,c);
         #endif
         #ifdef __GNUC__
         uint dummy, dummy2;
             __asm__  __volatile__(
                 "xorq %%rdx, %%rdx              \n"
                 "negq %%rax                     \n"     // CF=1 if rax!=0 , CF=0 if rax==0
             "1:                                 \n"
                 "movq (%%rsi,%%rdx,8), %%rax    \n"
                 "sbbq %%rax, (%%rbx,%%rdx,8)    \n"
                 "incq %%rdx                     \n"
                 "decq %%rcx                     \n"
             "jnz 1b                             \n"
                 "adcq %%rcx, %%rcx              \n"
                 : "=c" (c), "=a" (dummy), "=d" (dummy2)
                 : "0" (b),  "1" (c), "b" (p1), "S" (p2)
                 : "cc", "memory" );
         #endif
         TTMATH_LOGC("UInt::Sub", c)
     return c;
     }
Referenced by ttmath::Int< exp >::ChangeSign(), ttmath::UInt< man >::operator-(), ttmath::UInt< man >::Sqrt(), and ttmath::Int< exp >::Sub().
SubInt()
template<uint value_size> uint ttmath::Int< value_size >::SubInt (uint value, uint index = 0)
this method subtracts one unsigned word (at a specific position) and returns a carry (if it was)
Definition at line 314 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         UInt<value_size>::SubInt(value, index);
     return CorrectCarryAfterSubtracting(p1_is_sign, false);
     }
Referenced by ttmath::Big< exp, man >::FromBig().
SubOne()
template<uint value_size> uint ttmath::Int< value_size >::SubOne ()
this method subtracts one from the value and returns carry
Definition at line 340 of file ttmathint.h.
     {
         bool p1_is_sign = IsSign();
         UInt<value_size>::SubOne();
     return CorrectCarryAfterSubtracting(p1_is_sign, false);
     }
Referenced by ttmath::Big< exp, man >::PowUInt(), ttmath::Big< exp, man >::Set05(), and ttmath::Big< exp, man >::Sqrt().
SubVector()
template<uint value_size> uint ttmath::UInt< value_size >::SubVector (const uint * ss1, const uint * ss2, uint ss1_size, uint ss2_size, uint * result) static inherited
this static method subtractes one vector from the other 'ss1' is larger in size or equal to 'ss2'
ss1 points to the first (larger) vector
ss2 points to the second vector
ss1_size - size of the ss1 (and size of the result too)
ss2_size - size of the ss2
result - is the result vector (which has size the same as ss1: ss1_size)
Example: ss1_size is 5, ss2_size is 3 ss1: ss2: result (output): 5 1 5-1 4 3 4-3 2 7 2-7 6 6-1 (the borrow from previous item) 9 9 return (carry): 0 of course the carry (borrow) is propagated and will be returned from the last item (this method is used by the Karatsuba multiplication algorithm)
Definition at line 597 of file ttmathuint_x86_64.h.
     {
         TTMATH_ASSERT( ss1_size >= ss2_size )
         uint c;
         #ifndef __GNUC__
             c = ttmath_subvector_x64(ss1, ss2, ss1_size, ss2_size, result);
         #endif
         #ifdef __GNUC__
         //  the asm code is nearly the same as in AddVector
         //  only two instructions 'adc' are changed to 'sbb'
         uint dummy1, dummy2, dummy3;
         uint rest = ss1_size - ss2_size;
             __asm__ __volatile__(
                 "mov %%rdx, %%r8                    \n"
                 "xor %%rdx, %%rdx                   \n"   // rdx = 0, cf = 0
             "1:                                     \n"
                 "mov (%%rsi,%%rdx,8), %%rax         \n"
                 "sbb (%%rbx,%%rdx,8), %%rax         \n"
                 "mov %%rax, (%%rdi,%%rdx,8)         \n"
                 "inc %%rdx                          \n"
                 "dec %%rcx                          \n"
             "jnz 1b                                 \n"
                 "adc %%rcx, %%rcx                   \n"   // rcx has the cf state
                 "or %%r8, %%r8                      \n"
                 "jz 3f                              \n"
                 "xor %%rbx, %%rbx                   \n"   // ebx = 0
                 "neg %%rcx                          \n"   // setting cf from rcx
                 "mov %%r8, %%rcx                    \n"   // rcx=rest and is != 0
             "2:                                     \n"
                 "mov (%%rsi, %%rdx, 8), %%rax       \n"
                 "sbb %%rbx, %%rax                   \n"
                 "mov %%rax, (%%rdi, %%rdx, 8)       \n"
                 "inc %%rdx                          \n"
                 "dec %%rcx                          \n"
             "jnz 2b                                 \n"
                 "adc %%rcx, %%rcx                   \n"
             "3:                                     \n"
                 : "=a" (dummy1), "=b" (dummy2), "=c" (c),       "=d" (dummy3)
                 :                "1" (ss2),     "2" (ss2_size), "3" (rest),   "S" (ss1),  "D" (result)
                 : "%r8", "cc", "memory" );
         #endif
         TTMATH_VECTOR_LOGC("UInt::SubVector", c, result, ss1_size)
     return c;
     }
Swap()
template<uint value_size> void ttmath::UInt< value_size >::Swap (UInt< value_size > & ss2) inherited
this method swappes this for an argument
Definition at line 239 of file ttmathuint.h.
     {
         for(uint i=0 ; i<value_size ; ++i)
         {
             uint temp = table[i];
             table[i] = ss2.table[i];
             ss2.table[i] = temp;
         }
     }
Referenced by ttmath::Big< exp, man >::Swap().
ToInt() [1/5]
template<uint value_size> sint ttmath::Int< value_size >::ToInt () const
this method returns the lowest value from table with a sign
we must be sure when we using this method whether the value will hold in an sint type or not (the rest value from table must be zero or -1)
Definition at line 1132 of file ttmathint.h.
     {
         return sint( UInt<value_size>::table[0] );
     }
Referenced by ttmath::Big< exp, man >::BitAnd(), ttmath::Big< exp, man >::BitOr(), ttmath::Big< exp, man >::BitXor(), ttmath::Big< exp, man >::IsInteger(), ttmath::Big< exp, man >::Mod2(), ttmath::Big< exp, man >::RemainFraction(), ttmath::Big< exp, man >::SkipFraction(), and ttmath::Big< exp, man >::ToDouble().
ToInt() [2/5]
template<uint value_size> uint ttmath::Int< value_size >::ToInt (uint & result) const
this method converts the value to uint type can return a carry if the value is too long to store it in uint type
Definition at line 1157 of file ttmathint.h.
     {
         return ToUInt(result);
     }
ToInt() [3/5]
template<uint value_size> uint ttmath::Int< value_size >::ToInt (sint & result) const
this method converts the value to sint type can return a carry if the value is too long to store it in sint type
Definition at line 1167 of file ttmathint.h.
     {
         result = sint( UInt<value_size>::table[0] );
         uint mask = IsSign() ? TTMATH_UINT_MAX_VALUE : 0;
         if( (result & TTMATH_UINT_HIGHEST_BIT) != (mask & TTMATH_UINT_HIGHEST_BIT) )
             return 1;
         for(uint i=1 ; i<value_size ; ++i)
             if( UInt<value_size>::table[i] != mask )
                 return 1;
     return 0;
     }
ToInt() [4/5]
template<uint value_size> uint ttmath::Int< value_size >::ToInt (unsigned int & result) const
this method converts the value to a 32 bit unsigned integer can return a carry if the value is too long to store it in this type this method is created only on a 64 bit platform ***
Definition at line 1274 of file ttmathint.h.
     {
         return ToUInt(result);
     }
ToInt() [5/5]
template<uint value_size> uint ttmath::Int< value_size >::ToInt (int & result) const
this method converts the value to a 32 bit signed integer can return a carry if the value is too long to store it in this type this method is created only on a 64 bit platform ***
Definition at line 1285 of file ttmathint.h.
     {
         uint first = UInt<value_size>::table[0];
         result = int(first);
         uint mask = IsSign() ? TTMATH_UINT_MAX_VALUE : 0;
         if( (first >> 31) != (mask >> 31) )
             return 1;
         for(uint i=1 ; i<value_size ; ++i)
             if( UInt<value_size>::table[i] != mask )
                 return 1;
     return 0;
     }
ToString() [1/3]
template<uint value_size> void ttmath::Int< value_size >::ToString (std::string & result, uint b = 10) const
this method converts the value to a string with a base equal 'b'
Definition at line 1332 of file ttmathint.h.
     {
         return ToStringBase(result, b);
     }
ToString() [2/3]
template<uint value_size> std::string ttmath::Int< value_size >::ToString (uint b = 10) const
this method converts the value to a string with a base equal 'b'
Definition at line 1341 of file ttmathint.h.
     {
         std::string result;
         ToStringBase(result, b);
     return result;
     }
ToString() [3/3]
template<uint value_size> void ttmath::Int< value_size >::ToString (std::wstring & result, uint b = 10) const
this method converts the value to a string with a base equal 'b'
Definition at line 1355 of file ttmathint.h.
     {
         return ToStringBase(result, b);
     }
ToStringBase()
template<uint value_size> template<class string_type > void ttmath::UInt< value_size >::ToStringBase (string_type & result, uint b = 10, bool negative = false) const inherited
an auxiliary method for converting to a string it's used from Int::ToString() too (negative is set true then)
Definition at line 3316 of file ttmathuint.h.
     {
     UInt<value_size> temp(*this);
     uint rest, table_id, index, digits;
     double digits_d;
     char character;
         result.clear();
         if( b<2 || b>16 )
             return;
         if( !FindLeadingBit(table_id, index) )
         {
             result = '0';
             return;
         }
         if( negative )
             result = '-';
         digits_d  = static_cast<double>(table_id); // for not making an overflow in uint type
         digits_d *= TTMATH_BITS_PER_UINT;
         digits_d += index + 1;
         digits_d *= ToStringLog2(b);
         digits = static_cast<uint>(digits_d) + 3; // plus some epsilon
         if( result.capacity() < digits )
             result.reserve(digits);
         do
         {
             temp.DivInt(b, &rest);
             character = static_cast<char>(Misc::DigitToChar(rest));
             result.insert(result.end(), character);
         }
         while( !temp.IsZero() );
         size_t i1 = negative ? 1 : 0; // the first is a hyphen (when negative is true)
         size_t i2 = result.size() - 1;
         for( ; i1 < i2 ; ++i1, --i2 )
         {
             char tempc = static_cast<char>(result[i1]);
             result[i1] = result[i2];
             result[i2] = tempc;
         }
     }
Referenced by ttmath::UInt< man >::ToString().
ToStringLog2()
template<uint value_size> double ttmath::UInt< value_size >::ToStringLog2 (uint x) const protected inherited
an auxiliary method for converting into the string it returns the log (with the base 2) from x where x is in <2;16>
Definition at line 3281 of file ttmathuint.h.
     {
         static double log_tab[] = {
             1.000000000000000000,
             0.630929753571457437,
             0.500000000000000000,
             0.430676558073393050,
             0.386852807234541586,
             0.356207187108022176,
             0.333333333333333333,
             0.315464876785728718,
             0.301029995663981195,
             0.289064826317887859,
             0.278942945651129843,
             0.270238154427319741,
             0.262649535037193547,
             0.255958024809815489,
             0.250000000000000000
         };
         if( x<2 || x>16 )
             return 0;
     return log_tab[x-2];
     }
Referenced by ttmath::UInt< man >::ToStringBase().
ToUInt() [1/3]
template<uint value_size> uint ttmath::Int< value_size >::ToUInt (uint & result) const
this method converts the value to uint type can return a carry if the value is too long to store it in uint type
Definition at line 1142 of file ttmathint.h.
     {
         uint c = UInt<value_size>::ToUInt(result);
         if( value_size == 1 )
             return (result & TTMATH_UINT_HIGHEST_BIT) == 0 ? 0 : 1;
     return c;
     }
ToUInt() [2/3]
template<uint value_size> uint ttmath::Int< value_size >::ToUInt (unsigned int & result) const
this method converts the value to a 32 bit unsigned integer can return a carry if the value is too long to store it in this type this method is created only on a 64 bit platform ***
Definition at line 1258 of file ttmathint.h.
     {
         uint c = UInt<value_size>::ToUInt(result);
         if( c || IsSign() )
             return 1;
     return 0;
     }
ToUInt() [3/3]
template<uint value_size> uint ttmath::UInt< value_size >::ToUInt () const inherited
this method returns the lowest value from table
we must be sure when we using this method whether the value will hold in an uint type or not (the rest value from the table must be zero)
Definition at line 3103 of file ttmathuint.h.
     {
         return table[0];
     }
Referenced by ttmath::Int< exp >::ToInt(), ttmath::UInt< man >::ToInt(), and ttmath::Int< exp >::ToUInt().
ToWString()
template<uint value_size> std::wstring ttmath::Int< value_size >::ToWString (uint b = 10) const
this method converts the value to a string with a base equal 'b'
Definition at line 1364 of file ttmathint.h.
     {
         std::wstring result;
         ToStringBase(result, b);
     return result;
     }
Friends And Related Function Documentation
operator<< [1/2]
template<uint value_size> std::ostream& operator<< (std::ostream & s, const Int< value_size > & l) friend
output to standard streams
Definition at line 1837 of file ttmathint.h.
     {
         return OutputToStream<std::ostream, std::string>(s, l);
     }
operator<< [2/2]
template<uint value_size> std::wostream& operator<< (std::wostream & s, const Int< value_size > & l) friend
output to standard streams
Definition at line 1848 of file ttmathint.h.
     {
         return OutputToStream<std::wostream, std::wstring>(s, l);
     }
operator>> [1/2]
template<uint value_size> std::istream& operator>> (std::istream & s, Int< value_size > & l) friend
input from standard streams
Definition at line 1901 of file ttmathint.h.
     {
         return InputFromStream<std::istream, std::string, char>(s, l);
     }
operator>> [2/2]
template<uint value_size> std::wistream& operator>> (std::wistream & s, Int< value_size > & l) friend
input from standard streams
Definition at line 1912 of file ttmathint.h.
     {
         return InputFromStream<std::wistream, std::wstring, wchar_t>(s, l);
     }
Field Documentation
table
template<uint value_size> uint ttmath::UInt< value_size >::table[value_size] inherited
buffer for the integer value table[0] - the lowest word of the value
Definition at line 81 of file ttmathuint.h.
Referenced by ttmath::UInt< man >::Add(), ttmath::UInt< man >::BitAnd(), ttmath::UInt< man >::BitNot(), ttmath::UInt< man >::BitNot2(), ttmath::UInt< man >::BitOr(), ttmath::UInt< man >::BitXor(), ttmath::UInt< man >::CmpBigger(), ttmath::UInt< man >::CmpBiggerEqual(), ttmath::UInt< man >::CmpEqual(), ttmath::UInt< man >::CmpSmaller(), ttmath::UInt< man >::CmpSmallerEqual(), ttmath::UInt< man >::CompensationToLeft(), ttmath::Big< exp, man >::Exp(), ttmath::UInt< man >::FindLeadingBit(), ttmath::UInt< man >::FindLowestBit(), ttmath::Big< exp, man >::FromBig(), ttmath::Big< exp, man >::FromUInt(), ttmath::UInt< man >::FromUInt(), ttmath::Big< exp, man >::IsInteger(), ttmath::UInt< man >::IsOnlyTheHighestBitSet(), ttmath::UInt< man >::IsOnlyTheLowestBitSet(), ttmath::UInt< man >::IsTheHighestBitSet(), ttmath::UInt< man >::IsTheLowestBitSet(), ttmath::UInt< man >::IsZero(), ttmath::UInt< man >::Mul1Big(), ttmath::UInt< man >::Mul2(), ttmath::UInt< man >::Mul2Big(), ttmath::UInt< man >::Mul3(), ttmath::UInt< man >::Mul3Big(), ttmath::UInt< man >::MulFastest(), ttmath::UInt< man >::MulFastestBig(), ttmath::Big< exp, man >::MulUInt(), ttmath::UInt< man >::operator=(), ttmath::Big< exp, man >::Pow(), ttmath::UInt< man >::Pow(), ttmath::UInt< man >::PrintLog(), ttmath::UInt< man >::PrintTable(), ttmath::UInt< man >::SetFromTable(), ttmath::UInt< man >::SetMax(), ttmath::UInt< man >::SetOne(), ttmath::Big< exp, man >::SetOne(), ttmath::UInt< man >::SetZero(), ttmath::UInt< man >::Sqrt(), ttmath::UInt< man >::Sub(), ttmath::UInt< man >::Swap(), ttmath::Big< exp, man >::ToInt(), ttmath::UInt< man >::ToInt(), ttmath::UInt< man >::ToUInt(), and ttmath::UInt< man >::UInt().
The documentation for this class was generated from the following file:
ttmathint.h