TTMath: ttmath Namespace Reference
ttmath Namespace Reference
a namespace for the TTMath library
Data Structures
class Big
Big implements the floating point numbers.
struct CGamma
struct Conv
class ExceptionInfo
class History
class Int
Int implements a big integer value with a sign.
class Misc
class Objects
class Parser
Mathematical parser.
class ReferenceError
class RuntimeError
class StopCalculating
class ThreadLock
objects of this class are used to synchronize
class UInt
UInt implements a big integer value without a sign.
class UInt< 0 >
Typedefs
typedef uint64_t uint
typedef int64_t sint
Enumerations
enum LibTypeCode {
asm_vc_32 = 0, asm_gcc_32, asm_vc_64, asm_gcc_64,
no_asm_32, no_asm_64
}
enum ErrorCode {
err_ok = 0, err_nothing_has_read, err_unknown_character, err_unexpected_final_bracket,
err_stack_not_clear, err_unknown_variable, err_division_by_zero, err_interrupt,
err_overflow, err_unknown_function, err_unknown_operator, err_unexpected_semicolon_operator,
err_improper_amount_of_arguments, err_improper_argument, err_unexpected_end, err_internal_error,
err_incorrect_name, err_incorrect_value, err_variable_exists, err_variable_loop,
err_functions_loop, err_must_be_only_one_value, err_object_exists, err_unknown_object,
err_still_calculating, err_in_short_form_used_function, err_percent_from, err_assignment_requires_variable
}
Functions
template<class ValueType >
ValueType SkipFraction (const ValueType &x)
template<class ValueType >
ValueType Round (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Ceil (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Floor (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Ln (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Log (const ValueType &x, const ValueType &base, ErrorCode *err=0)
template<class ValueType >
ValueType Exp (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Sin (ValueType x, ErrorCode *err=0)
template<class ValueType >
ValueType Cos (ValueType x, ErrorCode *err=0)
template<class ValueType >
ValueType Tan (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Tg (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Cot (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Ctg (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ASin (ValueType x, ErrorCode *err=0)
template<class ValueType >
ValueType ACos (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ATan (ValueType x)
template<class ValueType >
ValueType ATg (const ValueType &x)
template<class ValueType >
ValueType ACot (const ValueType &x)
template<class ValueType >
ValueType ACtg (const ValueType &x)
template<class ValueType >
ValueType Sinh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Cosh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Tanh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Tgh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Coth (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Ctgh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ASinh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ACosh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ATanh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ATgh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ACoth (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType ACtgh (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType DegToRad (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType RadToDeg (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType DegToDeg (const ValueType &d, const ValueType &m, const ValueType &s, ErrorCode *err=0)
template<class ValueType >
ValueType DegToRad (const ValueType &d, const ValueType &m, const ValueType &s, ErrorCode *err=0)
template<class ValueType >
ValueType GradToRad (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType RadToGrad (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType DegToGrad (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType DegToGrad (const ValueType &d, const ValueType &m, const ValueType &s, ErrorCode *err=0)
template<class ValueType >
ValueType GradToDeg (const ValueType &x, ErrorCode *err=0)
template<class ValueType >
ValueType Sqrt (ValueType x, ErrorCode *err=0)
template<class ValueType >
ValueType Root (ValueType x, const ValueType &index, ErrorCode *err=0)
template<class ValueType >
ValueType Abs (const ValueType &x)
template<class ValueType >
ValueType Sgn (ValueType x)
template<class ValueType >
ValueType Mod (ValueType a, const ValueType &b, ErrorCode *err=0)
template<class ValueType >
ValueType Gamma (const ValueType &n, CGamma< ValueType > &cgamma, ErrorCode *err=0, const volatile StopCalculating *stop=0)
template<class ValueType >
ValueType Gamma (const ValueType &n, ErrorCode *err=0)
template<class ValueType >
ValueType Factorial (const ValueType &x, CGamma< ValueType > &cgamma, ErrorCode *err=0, const volatile StopCalculating *stop=0)
template<class ValueType >
ValueType Factorial (const ValueType &x, ErrorCode *err=0)
Variables
pthread_mutex_t ttmath_mutex
Detailed Description
a namespace for the TTMath library
Typedef Documentation
sint
typedef int64_t ttmath::sint
on 64bit platforms one word (uint, sint) will be equal 64bits
Definition at line 243 of file ttmathtypes.h.
uint
typedef uint64_t ttmath::uint
on 64bit platforms one word (uint, sint) will be equal 64bits
Definition at line 238 of file ttmathtypes.h.
Enumeration Type Documentation
ErrorCode
enum ttmath::ErrorCode
error codes
Definition at line 370 of file ttmathtypes.h.
     {
         err_ok = 0,
         err_nothing_has_read,
         err_unknown_character,
         err_unexpected_final_bracket,
         err_stack_not_clear,
         err_unknown_variable,
         err_division_by_zero,
         err_interrupt,
         err_overflow,
         err_unknown_function,
         err_unknown_operator,
         err_unexpected_semicolon_operator,
         err_improper_amount_of_arguments,
         err_improper_argument,
         err_unexpected_end,
         err_internal_error,
         err_incorrect_name,
         err_incorrect_value,
         err_variable_exists,
         err_variable_loop,
         err_functions_loop,
         err_must_be_only_one_value,
         err_object_exists,
         err_unknown_object,
         err_still_calculating,
         err_in_short_form_used_function,
         err_percent_from,
         err_assignment_requires_variable
     };
LibTypeCode
enum ttmath::LibTypeCode
lib type codes:
asm_vc_32 - with asm code designed for Microsoft Visual C++ (32 bits)
asm_gcc_32 - with asm code designed for GCC (32 bits)
asm_vc_64 - with asm for VC (64 bit)
asm_gcc_64 - with asm for GCC (64 bit)
no_asm_32 - pure C++ version (32 bit) - without any asm code
no_asm_64 - pure C++ version (64 bit) - without any asm code
Definition at line 356 of file ttmathtypes.h.
     {
       asm_vc_32 = 0,
       asm_gcc_32,
       asm_vc_64,
       asm_gcc_64,
       no_asm_32,
       no_asm_64
     };
Function Documentation
Abs()
template<class ValueType > ValueType ttmath::Abs (const ValueType & x)
absolute value of x
samples:
-2 = 2
2 = 2
Definition at line 2137 of file ttmath.h.
     {
         ValueType result( x );
         result.Abs();
     return result;
     }
ACos()
template<class ValueType > ValueType ttmath::ACos (const ValueType & x, ErrorCode * err = 0)
this function calculates the Arc Cosine
we're using the formula: acos(x) = pi/2 - asin(x)
Definition at line 910 of file ttmath.h.
     {
     ValueType temp;
         temp.Set05Pi();
         temp.Sub(ASin(x, err));
     return temp;
     }
References ASin().
ACosh()
template<class ValueType > ValueType ttmath::ACosh (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic cosine
acosh(x) = ln(x + sqrt(x^2 - 1)) x in <1, infinity)
Definition at line 1387 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType xx(x), one, result;
         uint c = 0;
         one.SetOne();
         if( x < one )
         {
             if( err )
                 *err = err_improper_argument;
         return result; // NaN is set by default
         }
         c += xx.Mul(x);
         c += xx.Sub(one);
         // xx is >= 0
         // we can't call a PowFrac when the 'x' is zero
         // if x is 0 the sqrt(0) is 0
         if( !xx.IsZero() )
         {
             one.exponent.SubOne(); // one=0.5
             c += xx.PowFrac(one); // xx=sqrt(xx)
         }
         c += xx.Add(x);
         c += result.Ln(xx); // xx >= 1
         // here can only be a carry
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
ACot()
template<class ValueType > ValueType ttmath::ACot (const ValueType & x)
this function calculates the Arc Cotangent
we're using the formula: actan(x) = pi/2 - atan(x)
Definition at line 1136 of file ttmath.h.
     {
     ValueType result;
         result.Set05Pi();
         result.Sub(ATan(x));
     return result;
     }
References ATan().
Referenced by ACtg().
ACoth()
template<class ValueType > ValueType ttmath::ACoth (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic cotangent
acoth(x) = 0.5 * ln((x+1) / (x-1)) x in (-infinity, -1) or (1, infinity)
Definition at line 1489 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType nominator(x), denominator(x), one, result;
         uint c = 0;
         one.SetOne();
         if( !x.GreaterWithoutSignThan(one) )
         {
             if( err )
                 *err = err_improper_argument;
         return result; // NaN is set by default
         }
         c += nominator.Add(one);
         c += denominator.Sub(one);
         c += nominator.Div(denominator);
         c += result.Ln(nominator);
         c += result.exponent.SubOne();
         // here can only be a carry
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ACtgh().
ACtg()
template<class ValueType > ValueType ttmath::ACtg (const ValueType & x)
this function calculates the Arc Cotangent look at the description of ACot(...)
(the abbreviation of Arc Cotangent can be 'actg' as well)
Definition at line 1154 of file ttmath.h.
     {
         return ACot(x);
     }
References ACot().
ACtgh()
template<class ValueType > ValueType ttmath::ACtgh (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic cotantent
Definition at line 1529 of file ttmath.h.
     {
         return ACoth(x, err);
     }
References ACoth().
ASin()
template<class ValueType > ValueType ttmath::ASin (ValueType x, ErrorCode * err = 0)
this function calculates the Arc Sine x is from <-1,1>
Definition at line 855 of file ttmath.h.
     {
     using namespace auxiliaryfunctions;
         ValueType result, one;
         one.SetOne();
         bool change_sign = false;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         if( x.GreaterWithoutSignThan(one) )
         {
             if( err )
                 *err = err_improper_argument;
             return result; // NaN is set by default
         }
         if( x.IsSign() )
         {
             change_sign = true;
             x.Abs();
         }
         one.exponent.SubOne(); // =0.5
         // asin(-x) = -asin(x)
         if( x.GreaterWithoutSignThan(one) )
             result = ASin_1(x);
         else
             result = ASin_0(x);
         if( change_sign )
             result.ChangeSign();
         if( err )
             *err = err_ok;
     return result;
     }
Referenced by ACos().
ASinh()
template<class ValueType > ValueType ttmath::ASinh (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic sine
asinh(x) = ln(x + sqrt(x^2 + 1))
Definition at line 1351 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType xx(x), one, result;
         uint c = 0;
         one.SetOne();
         c += xx.Mul(x);
         c += xx.Add(one);
         one.exponent.SubOne(); // one=0.5
         // xx is >= 1
         c += xx.PowFrac(one); // xx=sqrt(xx)
         c += xx.Add(x);
         c += result.Ln(xx); // xx > 0
         // here can only be a carry
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
ATan()
template<class ValueType > ValueType ttmath::ATan (ValueType x)
this function calculates the Arc Tangent
Definition at line 1085 of file ttmath.h.
     {
     using namespace auxiliaryfunctions;
         ValueType one, result;
         one.SetOne();
         bool change_sign = false;
         if( x.IsNan() )
             return x;
         // if x is negative we're using the formula:
         // atan(-x) = -atan(x)
         if( x.IsSign() )
         {
             change_sign = true;
             x.Abs();
         }
         if( x.GreaterWithoutSignThan(one) )
             result = ATanGreaterThanPlusOne(x);
         else
             result = ATan01(x);
         if( change_sign )
             result.ChangeSign();
     return result;
     }
Referenced by ACot(), and ATg().
ATanh()
template<class ValueType > ValueType ttmath::ATanh (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic tangent
atanh(x) = 0.5 * ln((1+x) / (1-x)) x in (-1, 1)
Definition at line 1436 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType nominator(x), denominator, one, result;
         uint c = 0;
         one.SetOne();
         if( !x.SmallerWithoutSignThan(one) )
         {
             if( err )
                 *err = err_improper_argument;
         return result; // NaN is set by default
         }
         c += nominator.Add(one);
         denominator = one;
         c += denominator.Sub(x);
         c += nominator.Div(denominator);
         c += result.Ln(nominator);
         c += result.exponent.SubOne();
         // here can only be a carry
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ATgh().
ATg()
template<class ValueType > ValueType ttmath::ATg (const ValueType & x)
this function calculates the Arc Tangent look at the description of ATan(...)
(the abbreviation of Arc Tangent can be 'atg' as well)
Definition at line 1123 of file ttmath.h.
     {
         return ATan(x);
     }
References ATan().
ATgh()
template<class ValueType > ValueType ttmath::ATgh (const ValueType & x, ErrorCode * err = 0)
inverse hyperbolic tantent
Definition at line 1477 of file ttmath.h.
     {
         return ATanh(x, err);
     }
References ATanh().
Ceil()
template<class ValueType > ValueType ttmath::Ceil (const ValueType & x, ErrorCode * err = 0)
this function returns a value representing the smallest integer that is greater than or equal to x
Ceil(-3.7) = -3
Ceil(-3.1) = -3
Ceil(-3.0) = -3
Ceil(4.0) = 4
Ceil(4.2) = 5
Ceil(4.8) = 5
Definition at line 142 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType result(x);
         uint c = 0;
         result.SkipFraction();
         if( result != x )
         {
             // x is with fraction
             // if x is negative we don't have to do anything
             if( !x.IsSign() )
             {
                 ValueType one;
                 one.SetOne();
                 c += result.Add(one);
             }
         }
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Cos()
template<class ValueType > ValueType ttmath::Cos (ValueType x, ErrorCode * err = 0)
this function calulates the Cosine we're using the formula cos(x) = sin(x + PI/2)
Definition at line 581 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType pi05;
         pi05.Set05Pi();
         uint c = x.Add( pi05 );
         if( c )
         {
             if( err )
                 *err = err_overflow;
         return ValueType(); // result is undefined (NaN is set by default)
         }
     return Sin(x, err);
     }
References Sin().
Referenced by Cot(), and Tan().
Cosh()
template<class ValueType > ValueType ttmath::Cosh (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Cosine
we're using the formula cosh(x)= (e^x + e^(-x)) / 2
Definition at line 1206 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType ex, emx;
         uint c = 0;
         c += ex.Exp(x);
         c += emx.Exp(-x);
         c += ex.Add(emx);
         c += ex.exponent.SubOne();
         if( err )
             *err = c ? err_overflow : err_ok;
     return ex;
     }
Cot()
template<class ValueType > ValueType ttmath::Cot (const ValueType & x, ErrorCode * err = 0)
this function calulates the Cotangent we're using the formula tan(x) = cos(x) / sin(x)
(why do we make it in this way? look at information in Tan() function)
Definition at line 661 of file ttmath.h.
     {
         ValueType result = Sin(x, err);
         if( err && *err != err_ok )
             return result;
         if( result.IsZero() )
         {
             if( err )
                 *err = err_improper_argument;
             result.SetNan();
         return result;
         }
     return Cos(x, err) / result;
     }
References Cos(), and Sin().
Referenced by Ctg().
Coth()
template<class ValueType > ValueType ttmath::Coth (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Cotangent
we're using the formula coth(x)= (e^x + e^(-x)) / (e^x - e^(-x))
Definition at line 1286 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         if( x.IsZero() )
         {
             if( err )
                 *err = err_improper_argument;
             return ValueType(); // NaN is set by default
         }
         ValueType ex, emx, nominator, denominator;
         uint c = 0;
         c += ex.Exp(x);
         c += emx.Exp(-x);
         nominator = ex;
         c += nominator.Add(emx);
         denominator = ex;
         c += denominator.Sub(emx);
         c += nominator.Div(denominator);
         if( err )
             *err = c ? err_overflow : err_ok;
     return nominator;
     }
Referenced by Ctgh().
Ctg()
template<class ValueType > ValueType ttmath::Ctg (const ValueType & x, ErrorCode * err = 0)
this function calulates the Cotangent look at the description of Cot(...)
(the abbreviation of Cotangent can be 'ctg' as well)
Definition at line 689 of file ttmath.h.
     {
         return Cot(x, err);
     }
References Cot().
Ctgh()
template<class ValueType > ValueType ttmath::Ctgh (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Cotangent look at the description of Coth(...)
(the abbreviation of Hyperbolic Cotangent can be 'ctgh' as well)
Definition at line 1331 of file ttmath.h.
     {
         return Coth(x, err);
     }
References Coth().
DegToDeg()
template<class ValueType > ValueType ttmath::DegToDeg (const ValueType & d, const ValueType & m, const ValueType & s, ErrorCode * err = 0)
this function converts degrees in the long format into one value
long format: (degrees, minutes, seconds) minutes and seconds must be greater than or equal zero
result:
if d>=0 : result= d + ((s/60)+m)/60
if d<0 : result= d - ((s/60)+m)/60
((s/60)+m)/60 = (s+60*m)/3600 (second version is faster because there's only one division)
samples:
DegToDeg(10, 30, 0) = 10.5
DegToDeg(10, 24, 35.6)=10.4098(8)
Definition at line 1633 of file ttmath.h.
     {
     ValueType delimiter, multipler;
     uint c = 0;
         if( d.IsNan() || m.IsNan() || s.IsNan() || m.IsSign() || s.IsSign() )
         {
             if( err )
                 *err = err_improper_argument;
             delimiter.SetZeroNan(); // not needed, only to get rid of GCC warning about an uninitialized variable
         return delimiter;
         }
         multipler = 60;
         delimiter = 3600;
         c += multipler.Mul(m);
         c += multipler.Add(s);
         c += multipler.Div(delimiter);
         if( d.IsSign() )
             multipler.ChangeSign();
         c += multipler.Add(d);
         if( err )
             *err = c ? err_overflow : err_ok;
     return multipler;
     }
Referenced by DegToGrad(), and DegToRad().
DegToGrad() [1/2]
template<class ValueType > ValueType ttmath::DegToGrad (const ValueType & x, ErrorCode * err = 0)
this function converts degrees to gradians
it returns: x * 200 / 180
Definition at line 1758 of file ttmath.h.
     {
     ValueType result, temp;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = x;
         temp = 200;
         c += result.Mul(temp);
         temp = 180;
         c += result.Div(temp);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by DegToGrad().
DegToGrad() [2/2]
template<class ValueType > ValueType ttmath::DegToGrad (const ValueType & d, const ValueType & m, const ValueType & s, ErrorCode * err = 0)
this function converts degrees in the long format to gradians
Definition at line 1790 of file ttmath.h.
     {
         ValueType temp_deg = DegToDeg(d,m,s,err);
         if( err && *err!=err_ok )
             return temp_deg;
     return DegToGrad(temp_deg, err);
     }
References DegToDeg(), and DegToGrad().
DegToRad() [1/2]
template<class ValueType > ValueType ttmath::DegToRad (const ValueType & x, ErrorCode * err = 0)
this function converts degrees to radians
it returns: x * pi / 180
Definition at line 1552 of file ttmath.h.
     {
     ValueType result, temp;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = x;
         // it is better to make division first and then multiplication
         // the result is more accurate especially when x is: 90,180,270 or 360
         temp = 180;
         c += result.Div(temp);
         temp.SetPi();
         c += result.Mul(temp);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ttmath::Parser< ValueType >::ConvertAngleToRad(), and DegToRad().
DegToRad() [2/2]
template<class ValueType > ValueType ttmath::DegToRad (const ValueType & d, const ValueType & m, const ValueType & s, ErrorCode * err = 0)
this function converts degrees in the long format to radians
Definition at line 1672 of file ttmath.h.
     {
         ValueType temp_deg = DegToDeg(d,m,s,err);
         if( err && *err!=err_ok )
             return temp_deg;
     return DegToRad(temp_deg, err);
     }
References DegToDeg(), and DegToRad().
Exp()
template<class ValueType > ValueType ttmath::Exp (const ValueType & x, ErrorCode * err = 0)
this function calculates the expression e^x
Definition at line 323 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType result;
         uint c = result.Exp(x);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Factorial() [1/2]
template<class ValueType > ValueType ttmath::Factorial (const ValueType & x, CGamma< ValueType > & cgamma, ErrorCode * err = 0, const volatile StopCalculating * stop = 0)
the factorial from given 'x' e.g. Factorial(4) = 4! = 1*2*3*4
it's multithread safe, you should create a CGamma<> object and use it whenever you call the Factorial() e.g.
typedef Big<1,2> MyBig;
MyBig x=234, y=54345;
CGamma<MyBig> cgamma;
std::cout << Factorial(x, cgamma) << std::endl;
std::cout << Factorial(y, cgamma) << std::endl;
in the CGamma<> object the function stores some coefficients (factorials, Bernoulli numbers), and they will be reused in next calls to the function
each thread should have its own CGamma<> object, and you can use these objects with Gamma() function too
Definition at line 2809 of file ttmath.h.
     {
         return auxiliaryfunctions::Factorial2(x, &cgamma, err, stop);
     }
Referenced by ttmath::Parser< ValueType >::Factorial().
Factorial() [2/2]
template<class ValueType > ValueType ttmath::Factorial (const ValueType & x, ErrorCode * err = 0)
the factorial from given 'x' e.g. Factorial(4) = 4! = 1*2*3*4
note: this function should be used only in a single-thread environment
Definition at line 2824 of file ttmath.h.
     {
         return auxiliaryfunctions::Factorial2(x, (CGamma<ValueType>*)0, err, 0);
     }
Floor()
template<class ValueType > ValueType ttmath::Floor (const ValueType & x, ErrorCode * err = 0)
this function returns a value representing the largest integer that is less than or equal to x
Floor(-3.6) = -4
Floor(-3.1) = -4
Floor(-3) = -3
Floor(2) = 2
Floor(2.3) = 2
Floor(2.8) = 2
Definition at line 189 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType result(x);
         uint c = 0;
         result.SkipFraction();
         if( result != x )
         {
             // x is with fraction
             // if x is positive we don't have to do anything
             if( x.IsSign() )
             {
                 ValueType one;
                 one.SetOne();
                 c += result.Sub(one);
             }
         }
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Gamma() [1/2]
template<class ValueType > ValueType ttmath::Gamma (const ValueType & n, CGamma< ValueType > & cgamma, ErrorCode * err = 0, const volatile StopCalculating * stop = 0)
this function calculates the Gamma function
it's multithread safe, you should create a CGamma<> object and use it whenever you call the Gamma() e.g.
typedef Big<1,2> MyBig;
MyBig x=234, y=345.53;
CGamma<MyBig> cgamma;
std::cout << Gamma(x, cgamma) << std::endl;
std::cout << Gamma(y, cgamma) << std::endl;
in the CGamma<> object the function stores some coefficients (factorials, Bernoulli numbers), and they will be reused in next calls to the function
each thread should have its own CGamma<> object, and you can use these objects with Factorial() function too
Definition at line 2679 of file ttmath.h.
     {
     using namespace auxiliaryfunctions;
     ValueType result;
     ErrorCode err_tmp;
         if( n.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return n;
         }
         if( cgamma.history.Get(n, result, err_tmp) )
         {
             if( err )
                 *err = err_tmp;
             return result;
         }
         err_tmp = err_ok;
         if( n.IsSign() )
         {
             result = GammaMinus(n, cgamma, err_tmp, stop);
         }
         else
         if( n.IsZero() )
         {
             err_tmp = err_improper_argument;
             result.SetNan();
         }
         else
         {
             result = GammaPlus(n, cgamma, err_tmp, stop);
         }
         if( result.IsNan() && err_tmp==err_ok )
             err_tmp = err_overflow;
         if( err )
             *err = err_tmp;
         if( stop && !stop->WasStopSignal() )
             cgamma.history.Add(n, result, err_tmp);
     return result;
     }
References ttmath::CGamma< ValueType >::history.
Referenced by Gamma(), and ttmath::CGamma< ValueType >::InitAll().
Gamma() [2/2]
template<class ValueType > ValueType ttmath::Gamma (const ValueType & n, ErrorCode * err = 0)
this function calculates the Gamma function
note: this function should be used only in a single-thread environment
Definition at line 2739 of file ttmath.h.
     {
     // warning: this static object is not thread safe
     static CGamma<ValueType> cgamma;
     return Gamma(n, cgamma, err);
     }
References Gamma().
GradToDeg()
template<class ValueType > ValueType ttmath::GradToDeg (const ValueType & x, ErrorCode * err = 0)
this function converts degrees to gradians
it returns: x * 180 / 200
Definition at line 1808 of file ttmath.h.
     {
     ValueType result, temp;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = x;
         temp = 180;
         c += result.Mul(temp);
         temp = 200;
         c += result.Div(temp);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
GradToRad()
template<class ValueType > ValueType ttmath::GradToRad (const ValueType & x, ErrorCode * err = 0)
this function converts gradians to radians
it returns: x * pi / 200
Definition at line 1690 of file ttmath.h.
     {
     ValueType result, temp;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = x;
         // it is better to make division first and then multiplication
         // the result is more accurate especially when x is: 100,200,300 or 400
         temp = 200;
         c += result.Div(temp);
         temp.SetPi();
         c += result.Mul(temp);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ttmath::Parser< ValueType >::ConvertAngleToRad().
Ln()
template<class ValueType > ValueType ttmath::Ln (const ValueType & x, ErrorCode * err = 0)
this function calculates the natural logarithm (logarithm with the base 'e')
Definition at line 237 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType result;
         uint state = result.Ln(x);
         if( err )
         {
             switch( state )
             {
             case 0:
                 *err = err_ok;
                 break;
             case 1:
                 *err = err_overflow;
                 break;
             case 2:
                 *err = err_improper_argument;
                 break;
             default:
                 *err = err_internal_error;
                 break;
             }
         }
     return result;
     }
Log()
template<class ValueType > ValueType ttmath::Log (const ValueType & x, const ValueType & base, ErrorCode * err = 0)
this function calculates the logarithm
Definition at line 278 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err ) *err = err_improper_argument;
             return x;
         }
         if( base.IsNan() )
         {
             if( err ) *err = err_improper_argument;
             return base;
         }
         ValueType result;
         uint state = result.Log(x, base);
         if( err )
         {
             switch( state )
             {
             case 0:
                 *err = err_ok;
                 break;
             case 1:
                 *err = err_overflow;
                 break;
             case 2:
             case 3:
                 *err = err_improper_argument;
                 break;
             default:
                 *err = err_internal_error;
                 break;
             }
         }
     return result;
     }
Mod()
template<class ValueType > ValueType ttmath::Mod (ValueType a, const ValueType & b, ErrorCode * err = 0)
the remainder from a division
samples:
mod(12.6 ; 3) = 0.6 because 12.6 = 3*4 + 0.6
mod(-12.6 ; 3) = -0.6 bacause -12.6 = 3*(-4) + (-0.6)
mod(12.6 ; -3) = 0.6
mod(-12.6 ; -3) = -0.6
Definition at line 2173 of file ttmath.h.
     {
         if( a.IsNan() || b.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
             a.SetNan();
         return a;
         }
         uint c = a.Mod(b);
         if( err )
             *err = c ? err_overflow : err_ok;
     return a;
     }
RadToDeg()
template<class ValueType > ValueType ttmath::RadToDeg (const ValueType & x, ErrorCode * err = 0)
this function converts radians to degrees
it returns: x * 180 / pi
Definition at line 1588 of file ttmath.h.
     {
     ValueType result, delimiter;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = 180;
         c += result.Mul(x);
         delimiter.SetPi();
         c += result.Div(delimiter);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ttmath::Parser< ValueType >::ConvertRadToAngle().
RadToGrad()
template<class ValueType > ValueType ttmath::RadToGrad (const ValueType & x, ErrorCode * err = 0)
this function converts radians to gradians
it returns: x * 200 / pi
Definition at line 1726 of file ttmath.h.
     {
     ValueType result, delimiter;
     uint c = 0;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         result = 200;
         c += result.Mul(x);
         delimiter.SetPi();
         c += result.Div(delimiter);
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Referenced by ttmath::Parser< ValueType >::ConvertRadToAngle().
Root()
template<class ValueType > ValueType ttmath::Root (ValueType x, const ValueType & index, ErrorCode * err = 0)
caltulate the index'th Root of x
index must be integer and not negative <0;1;2;3....)
if index==0 the result is one
if x==0 the result is zero and we assume root(0;0) is not defined
if index is even (2;4;6...) the result is x^(1/index) and x>0
if index is odd (1;2;3;...) the result is either
-(abs(x)^(1/index)) if x<0, or
x^(1/index)) if x>0
for index==1 the result is equal x
Definition at line 2076 of file ttmath.h.
     {
         using namespace auxiliaryfunctions;
         if( x.IsNan() || index.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
             x.SetNan();
         return x;
         }
         if( RootCheckIndexSign(x, index, err) ) return x;
         if( RootCheckIndexZero(x, index, err) ) return x;
         if( RootCheckIndexOne (   index, err) ) return x;
         if( RootCheckIndexTwo (x, index, err) ) return x;
         if( RootCheckIndexFrac(x, index, err) ) return x;
         if( RootCheckXZero    (x,        err) ) return x;
         // index integer and index!=0
         // x!=0
         ValueType old_x(x);
         bool change_sign;
         if( RootCheckIndex(x, index, err, &change_sign ) ) return x;
         ValueType temp;
         uint c = 0;
         // we're using the formula: root(x ; n) = exp( ln(x) / n )
         c += temp.Ln(x);
         c += temp.Div(index);
         c += x.Exp(temp);
         if( change_sign )
         {
             // x is different from zero
             x.SetSign();
         }
         c += RootCorrectInteger(old_x, x, index);
         if( err )
             *err = c ? err_overflow : err_ok;
     return x;
     }
Round()
template<class ValueType > ValueType ttmath::Round (const ValueType & x, ErrorCode * err = 0)
this function rounds to the nearest integer value
samples
2.2 = 2
2.7 = 3
-2.2 = -2
-2.7 = -3
Definition at line 109 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType result( x );
         uint c = result.Round();
         if( err )
             *err = c ? err_overflow : err_ok;
     return result;
     }
Sgn()
template<class ValueType > ValueType ttmath::Sgn (ValueType x)
it returns the sign of the value
samples:
-2 = -1
0 = 0
10 = 1
Definition at line 2155 of file ttmath.h.
     {
         x.Sgn();
     return x;
     }
Sin()
template<class ValueType > ValueType ttmath::Sin (ValueType x, ErrorCode * err = 0)
this function calculates the Sine
Definition at line 525 of file ttmath.h.
     {
     using namespace auxiliaryfunctions;
     ValueType one, result;
     bool change_sign;
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x;
         }
         if( err )
             *err = err_ok;
         if( PrepareSin( x, change_sign ) )
         {
             // x is too big, we cannnot reduce the 2*PI period
             // prior to version 0.8.5 the result was zero
             // result has NaN flag set by default
             if( err )
                 *err = err_overflow; // maybe another error code? err_improper_argument?
         return result; // NaN is set by default
         }
         result = Sin0pi05( x );
         one.SetOne();
         // after calculations there can be small distortions in the result
         if( result > one )
             result = one;
         else
         if( result.IsSign() )
             // we've calculated the sin from <0, pi/2> and the result
             // should be positive
             result.SetZero();
         if( change_sign )
             result.ChangeSign();
     return result;
     }
Referenced by Cos(), Cot(), and Tan().
Sinh()
template<class ValueType > ValueType ttmath::Sinh (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Sine
we're using the formula sinh(x)= (e^x - e^(-x)) / 2
Definition at line 1174 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType ex, emx;
         uint c = 0;
         c += ex.Exp(x);
         c += emx.Exp(-x);
         c += ex.Sub(emx);
         c += ex.exponent.SubOne();
         if( err )
             *err = c ? err_overflow : err_ok;
     return ex;
     }
SkipFraction()
template<class ValueType > ValueType ttmath::SkipFraction (const ValueType & x)
this function skips the fraction from x
samples
2.2 = 2
2.7 = 2
-2.2 = 2
-2.7 = 2
Definition at line 90 of file ttmath.h.
     {
         ValueType result( x );
         result.SkipFraction();
     return result;
     }
Sqrt()
template<class ValueType > ValueType ttmath::Sqrt (ValueType x, ErrorCode * err = 0)
this function calculates the square root
Sqrt(9) = 3
Definition at line 1852 of file ttmath.h.
     {
         if( x.IsNan() || x.IsSign() )
         {
             if( err )
                 *err = err_improper_argument;
             x.SetNan();
         return x;
         }
         uint c = x.Sqrt();
         if( err )
             *err = c ? err_overflow : err_ok;
     return x;
     }
Tan()
template<class ValueType > ValueType ttmath::Tan (const ValueType & x, ErrorCode * err = 0)
this function calulates the Tangent we're using the formula tan(x) = sin(x) / cos(x)
it takes more time than calculating the Tan directly from for example Taylor series but should be a bit preciser because Tan receives its values from -infinity to +infinity and when we calculate it from any series then we can make a greater mistake than calculating 'sin/cos'
Definition at line 619 of file ttmath.h.
     {
         ValueType result = Cos(x, err);
         if( err && *err != err_ok )
             return result;
         if( result.IsZero() )
         {
             if( err )
                 *err = err_improper_argument;
             result.SetNan();
         return result;
         }
     return Sin(x, err) / result;
     }
References Cos(), and Sin().
Referenced by Tg().
Tanh()
template<class ValueType > ValueType ttmath::Tanh (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Tangent
we're using the formula tanh(x)= (e^x - e^(-x)) / (e^x + e^(-x))
Definition at line 1238 of file ttmath.h.
     {
         if( x.IsNan() )
         {
             if( err )
                 *err = err_improper_argument;
         return x; // NaN
         }
         ValueType ex, emx, nominator, denominator;
         uint c = 0;
         c += ex.Exp(x);
         c += emx.Exp(-x);
         nominator = ex;
         c += nominator.Sub(emx);
         denominator = ex;
         c += denominator.Add(emx);
         c += nominator.Div(denominator);
         if( err )
             *err = c ? err_overflow : err_ok;
     return nominator;
     }
Referenced by Tgh().
Tg()
template<class ValueType > ValueType ttmath::Tg (const ValueType & x, ErrorCode * err = 0)
this function calulates the Tangent look at the description of Tan(...)
(the abbreviation of Tangent can be 'tg' as well)
Definition at line 647 of file ttmath.h.
     {
         return Tan(x, err);
     }
References Tan().
Tgh()
template<class ValueType > ValueType ttmath::Tgh (const ValueType & x, ErrorCode * err = 0)
this function calculates the Hyperbolic Tangent look at the description of Tanh(...)
(the abbreviation of Hyperbolic Tangent can be 'tgh' as well)
Definition at line 1275 of file ttmath.h.
     {
         return Tanh(x, err);
     }
References Tanh().
Variable Documentation
ttmath_mutex
pthread_mutex_t ttmath::ttmath_mutex
ttmath_mutex will be defined by TTMATH_MULTITHREADS_HELPER macro
Referenced by ttmath::ThreadLock::Lock().