# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _risefl_interface
else:
    import _risefl_interface

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _risefl_interface.delete_SwigPyIterator

    def value(self):
        return _risefl_interface.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _risefl_interface.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _risefl_interface.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _risefl_interface.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _risefl_interface.SwigPyIterator_equal(self, x)

    def copy(self):
        return _risefl_interface.SwigPyIterator_copy(self)

    def next(self):
        return _risefl_interface.SwigPyIterator_next(self)

    def __next__(self):
        return _risefl_interface.SwigPyIterator___next__(self)

    def previous(self):
        return _risefl_interface.SwigPyIterator_previous(self)

    def advance(self, n):
        return _risefl_interface.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _risefl_interface.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _risefl_interface.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _risefl_interface.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _risefl_interface.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _risefl_interface.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _risefl_interface.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _risefl_interface:
_risefl_interface.SwigPyIterator_swigregister(SwigPyIterator)

class PublicKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pub = property(_risefl_interface.PublicKey_pub_get, _risefl_interface.PublicKey_pub_set)

    def __eq__(self, other):
        return _risefl_interface.PublicKey___eq__(self, other)

    def export_to_bytestream(self, it):
        return _risefl_interface.PublicKey_export_to_bytestream(self, it)

    def import_from_bytestream(self, it_bytes):
        return _risefl_interface.PublicKey_import_from_bytestream(self, it_bytes)

    def __init__(self):
        _risefl_interface.PublicKey_swiginit(self, _risefl_interface.new_PublicKey())
    __swig_destroy__ = _risefl_interface.delete_PublicKey

# Register PublicKey in _risefl_interface:
_risefl_interface.PublicKey_swigregister(PublicKey)
cvar = _risefl_interface.cvar
ENCRISTSCALBYTES = cvar.ENCRISTSCALBYTES
NUM_THREADS = cvar.NUM_THREADS

class PrivateKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    prv = property(_risefl_interface.PrivateKey_prv_get, _risefl_interface.PrivateKey_prv_set)

    def __eq__(self, other):
        return _risefl_interface.PrivateKey___eq__(self, other)

    def __init__(self):
        _risefl_interface.PrivateKey_swiginit(self, _risefl_interface.new_PrivateKey())
    __swig_destroy__ = _risefl_interface.delete_PrivateKey

# Register PrivateKey in _risefl_interface:
_risefl_interface.PrivateKey_swigregister(PrivateKey)

class Nonce(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    non = property(_risefl_interface.Nonce_non_get, _risefl_interface.Nonce_non_set)

    def __eq__(self, other):
        return _risefl_interface.Nonce___eq__(self, other)

    def __init__(self):
        _risefl_interface.Nonce_swiginit(self, _risefl_interface.new_Nonce())
    __swig_destroy__ = _risefl_interface.delete_Nonce

# Register Nonce in _risefl_interface:
_risefl_interface.Nonce_swigregister(Nonce)

class CipherWithNonce(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cip = property(_risefl_interface.CipherWithNonce_cip_get, _risefl_interface.CipherWithNonce_cip_set)
    non = property(_risefl_interface.CipherWithNonce_non_get, _risefl_interface.CipherWithNonce_non_set)

    def __init__(self, clear_text_length):
        _risefl_interface.CipherWithNonce_swiginit(self, _risefl_interface.new_CipherWithNonce(clear_text_length))

    def __eq__(self, other):
        return _risefl_interface.CipherWithNonce___eq__(self, other)

    def export_to_bytestream(self, it):
        return _risefl_interface.CipherWithNonce_export_to_bytestream(self, it)

    def import_from_bytestream(self, it_bytes):
        return _risefl_interface.CipherWithNonce_import_from_bytestream(self, it_bytes)
    __swig_destroy__ = _risefl_interface.delete_CipherWithNonce

# Register CipherWithNonce in _risefl_interface:
_risefl_interface.CipherWithNonce_swigregister(CipherWithNonce)


def generate_dh_key_pair():
    return _risefl_interface.generate_dh_key_pair()

def generate_random_nonce():
    return _risefl_interface.generate_random_nonce()

def encrypt(*args):
    return _risefl_interface.encrypt(*args)

def decrypt(*args):
    return _risefl_interface.decrypt(*args)
CHECK_TYPE_L2NORM = _risefl_interface.CHECK_TYPE_L2NORM
CHECK_TYPE_SPHERE = _risefl_interface.CHECK_TYPE_SPHERE
CHECK_TYPE_COSINE_SIM = _risefl_interface.CHECK_TYPE_COSINE_SIM
class L2NormCheckParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound_sq = property(_risefl_interface.L2NormCheckParam_bound_sq_get, _risefl_interface.L2NormCheckParam_bound_sq_set)

    def __init__(self):
        _risefl_interface.L2NormCheckParam_swiginit(self, _risefl_interface.new_L2NormCheckParam())
    __swig_destroy__ = _risefl_interface.delete_L2NormCheckParam

# Register L2NormCheckParam in _risefl_interface:
_risefl_interface.L2NormCheckParam_swigregister(L2NormCheckParam)

class SphereCheckParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound_sq = property(_risefl_interface.SphereCheckParam_bound_sq_get, _risefl_interface.SphereCheckParam_bound_sq_set)
    center = property(_risefl_interface.SphereCheckParam_center_get, _risefl_interface.SphereCheckParam_center_set)

    def __init__(self):
        _risefl_interface.SphereCheckParam_swiginit(self, _risefl_interface.new_SphereCheckParam())
    __swig_destroy__ = _risefl_interface.delete_SphereCheckParam

# Register SphereCheckParam in _risefl_interface:
_risefl_interface.SphereCheckParam_swigregister(SphereCheckParam)

class CosineSimCheckParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound_sq = property(_risefl_interface.CosineSimCheckParam_bound_sq_get, _risefl_interface.CosineSimCheckParam_bound_sq_set)
    pivot = property(_risefl_interface.CosineSimCheckParam_pivot_get, _risefl_interface.CosineSimCheckParam_pivot_set)
    l2_sq_multiplier = property(_risefl_interface.CosineSimCheckParam_l2_sq_multiplier_get, _risefl_interface.CosineSimCheckParam_l2_sq_multiplier_set)
    inner_prod_sq_multiplier = property(_risefl_interface.CosineSimCheckParam_inner_prod_sq_multiplier_get, _risefl_interface.CosineSimCheckParam_inner_prod_sq_multiplier_set)

    def __init__(self):
        _risefl_interface.CosineSimCheckParam_swiginit(self, _risefl_interface.new_CosineSimCheckParam())
    __swig_destroy__ = _risefl_interface.delete_CosineSimCheckParam

# Register CosineSimCheckParam in _risefl_interface:
_risefl_interface.CosineSimCheckParam_swigregister(CosineSimCheckParam)

class CheckParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    check_type = property(_risefl_interface.CheckParam_check_type_get, _risefl_interface.CheckParam_check_type_set)
    l2_param = property(_risefl_interface.CheckParam_l2_param_get, _risefl_interface.CheckParam_l2_param_set)
    sphere_param = property(_risefl_interface.CheckParam_sphere_param_get, _risefl_interface.CheckParam_sphere_param_set)
    cosine_param = property(_risefl_interface.CheckParam_cosine_param_get, _risefl_interface.CheckParam_cosine_param_set)

    def __init__(self, check_type):
        _risefl_interface.CheckParam_swiginit(self, _risefl_interface.new_CheckParam(check_type))
    __swig_destroy__ = _risefl_interface.delete_CheckParam

# Register CheckParam in _risefl_interface:
_risefl_interface.CheckParam_swigregister(CheckParam)


def extra_inner_prod(c):
    return _risefl_interface.extra_inner_prod(c)

def extra_square(c):
    return _risefl_interface.extra_square(c)
class Predicate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    dim = property(_risefl_interface.Predicate_dim_get, _risefl_interface.Predicate_dim_set)
    num_weight_keys = property(_risefl_interface.Predicate_num_weight_keys_get, _risefl_interface.Predicate_num_weight_keys_set)
    num_blinds_per_group_element = property(_risefl_interface.Predicate_num_blinds_per_group_element_get, _risefl_interface.Predicate_num_blinds_per_group_element_set)
    num_samples = property(_risefl_interface.Predicate_num_samples_get, _risefl_interface.Predicate_num_samples_set)
    random_normal_bit_shifter = property(_risefl_interface.Predicate_random_normal_bit_shifter_get, _risefl_interface.Predicate_random_normal_bit_shifter_set)
    inner_prod_bound_bits = property(_risefl_interface.Predicate_inner_prod_bound_bits_get, _risefl_interface.Predicate_inner_prod_bound_bits_set)
    check_param = property(_risefl_interface.Predicate_check_param_get, _risefl_interface.Predicate_check_param_set)
    max_bound_sq_bits = property(_risefl_interface.Predicate_max_bound_sq_bits_get, _risefl_interface.Predicate_max_bound_sq_bits_set)
    bound_elem_keys_1 = property(_risefl_interface.Predicate_bound_elem_keys_1_get, _risefl_interface.Predicate_bound_elem_keys_1_set)
    bound_elem_keys_2 = property(_risefl_interface.Predicate_bound_elem_keys_2_get, _risefl_interface.Predicate_bound_elem_keys_2_set)
    aa_seed = property(_risefl_interface.Predicate_aa_seed_get, _risefl_interface.Predicate_aa_seed_set)
    hh = property(_risefl_interface.Predicate_hh_get, _risefl_interface.Predicate_hh_set)
    b_precomp = property(_risefl_interface.Predicate_b_precomp_get, _risefl_interface.Predicate_b_precomp_set)
    hh_precomp = property(_risefl_interface.Predicate_hh_precomp_get, _risefl_interface.Predicate_hh_precomp_set)
    hh_comb = property(_risefl_interface.Predicate_hh_comb_get, _risefl_interface.Predicate_hh_comb_set)
    square_key = property(_risefl_interface.Predicate_square_key_get, _risefl_interface.Predicate_square_key_set)

    def __init__(self, dim, num_blinds_per_group_element, num_samples, random_normal_bit_shifter, check_type, inner_prod_bound_bits, max_bound_sq_bits, b_precomp=True):
        _risefl_interface.Predicate_swiginit(self, _risefl_interface.new_Predicate(dim, num_blinds_per_group_element, num_samples, random_normal_bit_shifter, check_type, inner_prod_bound_bits, max_bound_sq_bits, b_precomp))

    def initialize_from_seed(self, seed):
        return _risefl_interface.Predicate_initialize_from_seed(self, seed)
    __swig_destroy__ = _risefl_interface.delete_Predicate

# Register Predicate in _risefl_interface:
_risefl_interface.Predicate_swigregister(Predicate)

class Proof(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    check_type = property(_risefl_interface.Proof_check_type_get, _risefl_interface.Proof_check_type_set)
    linear_comb_batch_commitments = property(_risefl_interface.Proof_linear_comb_batch_commitments_get, _risefl_interface.Proof_linear_comb_batch_commitments_set)
    linear_comb_single_commitments = property(_risefl_interface.Proof_linear_comb_single_commitments_get, _risefl_interface.Proof_linear_comb_single_commitments_set)
    proof_well_formed = property(_risefl_interface.Proof_proof_well_formed_get, _risefl_interface.Proof_proof_well_formed_set)
    proof_linear_comb_bound = property(_risefl_interface.Proof_proof_linear_comb_bound_get, _risefl_interface.Proof_proof_linear_comb_bound_set)
    square_commitments = property(_risefl_interface.Proof_square_commitments_get, _risefl_interface.Proof_square_commitments_set)
    proof_squares = property(_risefl_interface.Proof_proof_squares_get, _risefl_interface.Proof_proof_squares_set)
    proof_sum_range = property(_risefl_interface.Proof_proof_sum_range_get, _risefl_interface.Proof_proof_sum_range_set)
    proof_sum_range_for_cosine = property(_risefl_interface.Proof_proof_sum_range_for_cosine_get, _risefl_interface.Proof_proof_sum_range_for_cosine_set)

    def __init__(self, check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sum_bound_bits):
        _risefl_interface.Proof_swiginit(self, _risefl_interface.new_Proof(check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sum_bound_bits))

    @staticmethod
    def size(check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sq_sum_bound_bits):
        return _risefl_interface.Proof_size(check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sq_sum_bound_bits)

    def export_to_bytestream(self, it):
        return _risefl_interface.Proof_export_to_bytestream(self, it)

    def import_from_bytestream(self, it):
        return _risefl_interface.Proof_import_from_bytestream(self, it)
    __swig_destroy__ = _risefl_interface.delete_Proof

# Register Proof in _risefl_interface:
_risefl_interface.Proof_swigregister(Proof)

def Proof_size(check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sq_sum_bound_bits):
    return _risefl_interface.Proof_size(check_type, num_blinds_per_group_element, num_norm_bound_samples, inner_prod_bound_bits, sq_sum_bound_bits)

PROTOCOL_TYPE_PRIV = _risefl_interface.PROTOCOL_TYPE_PRIV
PROTOCOL_TYPE_NON_PRIV_INT = _risefl_interface.PROTOCOL_TYPE_NON_PRIV_INT
PROTOCOL_TYPE_NON_PRIV_FLOAT = _risefl_interface.PROTOCOL_TYPE_NON_PRIV_FLOAT
class L2NormCheckParamFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound = property(_risefl_interface.L2NormCheckParamFloat_bound_get, _risefl_interface.L2NormCheckParamFloat_bound_set)

    def __init__(self):
        _risefl_interface.L2NormCheckParamFloat_swiginit(self, _risefl_interface.new_L2NormCheckParamFloat())
    __swig_destroy__ = _risefl_interface.delete_L2NormCheckParamFloat

# Register L2NormCheckParamFloat in _risefl_interface:
_risefl_interface.L2NormCheckParamFloat_swigregister(L2NormCheckParamFloat)

class SphereCheckParamFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound = property(_risefl_interface.SphereCheckParamFloat_bound_get, _risefl_interface.SphereCheckParamFloat_bound_set)
    center = property(_risefl_interface.SphereCheckParamFloat_center_get, _risefl_interface.SphereCheckParamFloat_center_set)

    def __init__(self):
        _risefl_interface.SphereCheckParamFloat_swiginit(self, _risefl_interface.new_SphereCheckParamFloat())
    __swig_destroy__ = _risefl_interface.delete_SphereCheckParamFloat

# Register SphereCheckParamFloat in _risefl_interface:
_risefl_interface.SphereCheckParamFloat_swigregister(SphereCheckParamFloat)

class CosineSimCheckParamFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bound = property(_risefl_interface.CosineSimCheckParamFloat_bound_get, _risefl_interface.CosineSimCheckParamFloat_bound_set)
    pivot = property(_risefl_interface.CosineSimCheckParamFloat_pivot_get, _risefl_interface.CosineSimCheckParamFloat_pivot_set)
    cosine_bound = property(_risefl_interface.CosineSimCheckParamFloat_cosine_bound_get, _risefl_interface.CosineSimCheckParamFloat_cosine_bound_set)

    def __init__(self):
        _risefl_interface.CosineSimCheckParamFloat_swiginit(self, _risefl_interface.new_CosineSimCheckParamFloat())
    __swig_destroy__ = _risefl_interface.delete_CosineSimCheckParamFloat

# Register CosineSimCheckParamFloat in _risefl_interface:
_risefl_interface.CosineSimCheckParamFloat_swigregister(CosineSimCheckParamFloat)

class CheckParamFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    check_type = property(_risefl_interface.CheckParamFloat_check_type_get, _risefl_interface.CheckParamFloat_check_type_set)
    l2_param = property(_risefl_interface.CheckParamFloat_l2_param_get, _risefl_interface.CheckParamFloat_l2_param_set)
    sphere_param = property(_risefl_interface.CheckParamFloat_sphere_param_get, _risefl_interface.CheckParamFloat_sphere_param_set)
    cosine_param = property(_risefl_interface.CheckParamFloat_cosine_param_get, _risefl_interface.CheckParamFloat_cosine_param_set)

    def __init__(self, check_type):
        _risefl_interface.CheckParamFloat_swiginit(self, _risefl_interface.new_CheckParamFloat(check_type))
    __swig_destroy__ = _risefl_interface.delete_CheckParamFloat

# Register CheckParamFloat in _risefl_interface:
_risefl_interface.CheckParamFloat_swigregister(CheckParamFloat)

class CommonInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    protocol_type = property(_risefl_interface.CommonInterface_protocol_type_get, _risefl_interface.CommonInterface_protocol_type_set)
    normalizing_factor = property(_risefl_interface.CommonInterface_normalizing_factor_get, _risefl_interface.CommonInterface_normalizing_factor_set)
    num_clients = property(_risefl_interface.CommonInterface_num_clients_get, _risefl_interface.CommonInterface_num_clients_set)
    max_malicious_clients = property(_risefl_interface.CommonInterface_max_malicious_clients_get, _risefl_interface.CommonInterface_max_malicious_clients_set)
    dim = property(_risefl_interface.CommonInterface_dim_get, _risefl_interface.CommonInterface_dim_set)
    weight_bits = property(_risefl_interface.CommonInterface_weight_bits_get, _risefl_interface.CommonInterface_weight_bits_set)
    server_flags = property(_risefl_interface.CommonInterface_server_flags_get, _risefl_interface.CommonInterface_server_flags_set)
    dh_public_key_collection = property(_risefl_interface.CommonInterface_dh_public_key_collection_get, _risefl_interface.CommonInterface_dh_public_key_collection_set)
    bul_signed_pub_key_collection = property(_risefl_interface.CommonInterface_bul_signed_pub_key_collection_get, _risefl_interface.CommonInterface_bul_signed_pub_key_collection_set)
    predicate = property(_risefl_interface.CommonInterface_predicate_get, _risefl_interface.CommonInterface_predicate_set)
    shamir_check_string_collection = property(_risefl_interface.CommonInterface_shamir_check_string_collection_get, _risefl_interface.CommonInterface_shamir_check_string_collection_set)

    def __init__(self, *args):
        _risefl_interface.CommonInterface_swiginit(self, _risefl_interface.new_CommonInterface(*args))

    def set_param(self, c):
        return _risefl_interface.CommonInterface_set_param(self, c)

    def set_normalizing_factor_and_compute_check_param_from_gamma(self, check_param_float):
        return _risefl_interface.CommonInterface_set_normalizing_factor_and_compute_check_param_from_gamma(self, check_param_float)

    def reset_server_flags(self):
        return _risefl_interface.CommonInterface_reset_server_flags(self)

    def valid_client_count(self):
        return _risefl_interface.CommonInterface_valid_client_count(self)
    __swig_destroy__ = _risefl_interface.delete_CommonInterface

# Register CommonInterface in _risefl_interface:
_risefl_interface.CommonInterface_swigregister(CommonInterface)


def import_flags_start_from_1_from_bytestream(flags, it):
    return _risefl_interface.import_flags_start_from_1_from_bytestream(flags, it)

def export_flags_start_from_1_to_bytestream(flags, it):
    return _risefl_interface.export_flags_start_from_1_to_bytestream(flags, it)

def convert_sign_pub_key_to_string(pub_key):
    return _risefl_interface.convert_sign_pub_key_to_string(pub_key)

def convert_sign_prv_key_to_string(prv_key):
    return _risefl_interface.convert_sign_prv_key_to_string(prv_key)

def convert_string_to_sign_pub_key(key_str):
    return _risefl_interface.convert_string_to_sign_pub_key(key_str)

def convert_string_to_sign_prv_key(key_str):
    return _risefl_interface.convert_string_to_sign_prv_key(key_str)
class ClientInterface(CommonInterface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    client_id = property(_risefl_interface.ClientInterface_client_id_get, _risefl_interface.ClientInterface_client_id_set)
    bul_pub_keys = property(_risefl_interface.ClientInterface_bul_pub_keys_get, _risefl_interface.ClientInterface_bul_pub_keys_set)
    bul_prv_key = property(_risefl_interface.ClientInterface_bul_prv_key_get, _risefl_interface.ClientInterface_bul_prv_key_set)
    weight_updates = property(_risefl_interface.ClientInterface_weight_updates_get, _risefl_interface.ClientInterface_weight_updates_set)
    blinds_to_share = property(_risefl_interface.ClientInterface_blinds_to_share_get, _risefl_interface.ClientInterface_blinds_to_share_set)
    dh_public_key = property(_risefl_interface.ClientInterface_dh_public_key_get, _risefl_interface.ClientInterface_dh_public_key_set)
    dh_private_key = property(_risefl_interface.ClientInterface_dh_private_key_get, _risefl_interface.ClientInterface_dh_private_key_set)
    batch_shamir_share_with_check = property(_risefl_interface.ClientInterface_batch_shamir_share_with_check_get, _risefl_interface.ClientInterface_batch_shamir_share_with_check_set)
    encrypted_shamir_shares = property(_risefl_interface.ClientInterface_encrypted_shamir_shares_get, _risefl_interface.ClientInterface_encrypted_shamir_shares_set)
    proof = property(_risefl_interface.ClientInterface_proof_get, _risefl_interface.ClientInterface_proof_set)
    other_encrypted_shamir_shares = property(_risefl_interface.ClientInterface_other_encrypted_shamir_shares_get, _risefl_interface.ClientInterface_other_encrypted_shamir_shares_set)
    other_shamir_shares = property(_risefl_interface.ClientInterface_other_shamir_shares_get, _risefl_interface.ClientInterface_other_shamir_shares_set)
    flags = property(_risefl_interface.ClientInterface_flags_get, _risefl_interface.ClientInterface_flags_set)
    dispute_clients = property(_risefl_interface.ClientInterface_dispute_clients_get, _risefl_interface.ClientInterface_dispute_clients_set)
    dispute_shares = property(_risefl_interface.ClientInterface_dispute_shares_get, _risefl_interface.ClientInterface_dispute_shares_set)
    other_dispute_shares = property(_risefl_interface.ClientInterface_other_dispute_shares_get, _risefl_interface.ClientInterface_other_dispute_shares_set)
    aggregates = property(_risefl_interface.ClientInterface_aggregates_get, _risefl_interface.ClientInterface_aggregates_set)

    def __init__(self, *args):
        _risefl_interface.ClientInterface_swiginit(self, _risefl_interface.new_ClientInterface(*args))

    def import_weight_updates(self, u):
        return _risefl_interface.ClientInterface_import_weight_updates(self, u)

    def reset_flags(self):
        return _risefl_interface.ClientInterface_reset_flags(self)

    def generate_dh_key_pair(self):
        return _risefl_interface.ClientInterface_generate_dh_key_pair(self)

    def generate_batch_shares_and_check_string(self):
        return _risefl_interface.ClientInterface_generate_batch_shares_and_check_string(self)

    def encrypt_shares(self):
        return _risefl_interface.ClientInterface_encrypt_shares(self)

    def set_aa_seed(self, s):
        return _risefl_interface.ClientInterface_set_aa_seed(self, s)

    def generate_proof(self):
        return _risefl_interface.ClientInterface_generate_proof(self)

    def decrypt_shamir_shares(self):
        return _risefl_interface.ClientInterface_decrypt_shamir_shares(self)

    def check_shamir_share_integrity(self):
        return _risefl_interface.ClientInterface_check_shamir_share_integrity(self)

    def generate_dispute_shares(self):
        return _risefl_interface.ClientInterface_generate_dispute_shares(self)

    def update_other_shamir_shares_with_dispute(self):
        return _risefl_interface.ClientInterface_update_other_shamir_shares_with_dispute(self)

    def compute_aggegrated_share(self):
        return _risefl_interface.ClientInterface_compute_aggegrated_share(self)

    def initialize_from_seed(self, seed):
        return _risefl_interface.ClientInterface_initialize_from_seed(self, seed)

    def send_1_internal(self, check_param, u):
        return _risefl_interface.ClientInterface_send_1_internal(self, check_param, u)

    def send_1_bytes(self, check_param_float, u_float):
        return _risefl_interface.ClientInterface_send_1_bytes(self, check_param_float, u_float)

    def send_1(self, check_param_float, u_float):
        return _risefl_interface.ClientInterface_send_1(self, check_param_float, u_float)

    def receive_and_send_2_bytes(self, bytes):
        return _risefl_interface.ClientInterface_receive_and_send_2_bytes(self, bytes)

    def receive_and_send_2(self, bytes_str):
        return _risefl_interface.ClientInterface_receive_and_send_2(self, bytes_str)

    def receive_and_send_3_bytes(self, bytes):
        return _risefl_interface.ClientInterface_receive_and_send_3_bytes(self, bytes)

    def receive_and_send_3(self, bytes_str):
        return _risefl_interface.ClientInterface_receive_and_send_3(self, bytes_str)

    def receive_and_send_4_bytes(self, bytes):
        return _risefl_interface.ClientInterface_receive_and_send_4_bytes(self, bytes)

    def receive_and_send_4(self, bytes_str):
        return _risefl_interface.ClientInterface_receive_and_send_4(self, bytes_str)

    def receive_and_send_5_bytes(self, bytes):
        return _risefl_interface.ClientInterface_receive_and_send_5_bytes(self, bytes)

    def receive_and_send_5(self, bytes_str):
        return _risefl_interface.ClientInterface_receive_and_send_5(self, bytes_str)
    __swig_destroy__ = _risefl_interface.delete_ClientInterface

# Register ClientInterface in _risefl_interface:
_risefl_interface.ClientInterface_swigregister(ClientInterface)

class VecFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _risefl_interface.VecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _risefl_interface.VecFloat___nonzero__(self)

    def __bool__(self):
        return _risefl_interface.VecFloat___bool__(self)

    def __len__(self):
        return _risefl_interface.VecFloat___len__(self)

    def __getslice__(self, i, j):
        return _risefl_interface.VecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _risefl_interface.VecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _risefl_interface.VecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _risefl_interface.VecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _risefl_interface.VecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _risefl_interface.VecFloat___setitem__(self, *args)

    def pop(self):
        return _risefl_interface.VecFloat_pop(self)

    def append(self, x):
        return _risefl_interface.VecFloat_append(self, x)

    def empty(self):
        return _risefl_interface.VecFloat_empty(self)

    def size(self):
        return _risefl_interface.VecFloat_size(self)

    def swap(self, v):
        return _risefl_interface.VecFloat_swap(self, v)

    def begin(self):
        return _risefl_interface.VecFloat_begin(self)

    def end(self):
        return _risefl_interface.VecFloat_end(self)

    def rbegin(self):
        return _risefl_interface.VecFloat_rbegin(self)

    def rend(self):
        return _risefl_interface.VecFloat_rend(self)

    def clear(self):
        return _risefl_interface.VecFloat_clear(self)

    def get_allocator(self):
        return _risefl_interface.VecFloat_get_allocator(self)

    def pop_back(self):
        return _risefl_interface.VecFloat_pop_back(self)

    def erase(self, *args):
        return _risefl_interface.VecFloat_erase(self, *args)

    def __init__(self, *args):
        _risefl_interface.VecFloat_swiginit(self, _risefl_interface.new_VecFloat(*args))

    def push_back(self, x):
        return _risefl_interface.VecFloat_push_back(self, x)

    def front(self):
        return _risefl_interface.VecFloat_front(self)

    def back(self):
        return _risefl_interface.VecFloat_back(self)

    def assign(self, n, x):
        return _risefl_interface.VecFloat_assign(self, n, x)

    def resize(self, *args):
        return _risefl_interface.VecFloat_resize(self, *args)

    def insert(self, *args):
        return _risefl_interface.VecFloat_insert(self, *args)

    def reserve(self, n):
        return _risefl_interface.VecFloat_reserve(self, n)

    def capacity(self):
        return _risefl_interface.VecFloat_capacity(self)
    __swig_destroy__ = _risefl_interface.delete_VecFloat

# Register VecFloat in _risefl_interface:
_risefl_interface.VecFloat_swigregister(VecFloat)

class VecInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _risefl_interface.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _risefl_interface.VecInt___nonzero__(self)

    def __bool__(self):
        return _risefl_interface.VecInt___bool__(self)

    def __len__(self):
        return _risefl_interface.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _risefl_interface.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _risefl_interface.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _risefl_interface.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _risefl_interface.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _risefl_interface.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _risefl_interface.VecInt___setitem__(self, *args)

    def pop(self):
        return _risefl_interface.VecInt_pop(self)

    def append(self, x):
        return _risefl_interface.VecInt_append(self, x)

    def empty(self):
        return _risefl_interface.VecInt_empty(self)

    def size(self):
        return _risefl_interface.VecInt_size(self)

    def swap(self, v):
        return _risefl_interface.VecInt_swap(self, v)

    def begin(self):
        return _risefl_interface.VecInt_begin(self)

    def end(self):
        return _risefl_interface.VecInt_end(self)

    def rbegin(self):
        return _risefl_interface.VecInt_rbegin(self)

    def rend(self):
        return _risefl_interface.VecInt_rend(self)

    def clear(self):
        return _risefl_interface.VecInt_clear(self)

    def get_allocator(self):
        return _risefl_interface.VecInt_get_allocator(self)

    def pop_back(self):
        return _risefl_interface.VecInt_pop_back(self)

    def erase(self, *args):
        return _risefl_interface.VecInt_erase(self, *args)

    def __init__(self, *args):
        _risefl_interface.VecInt_swiginit(self, _risefl_interface.new_VecInt(*args))

    def push_back(self, x):
        return _risefl_interface.VecInt_push_back(self, x)

    def front(self):
        return _risefl_interface.VecInt_front(self)

    def back(self):
        return _risefl_interface.VecInt_back(self)

    def assign(self, n, x):
        return _risefl_interface.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _risefl_interface.VecInt_resize(self, *args)

    def insert(self, *args):
        return _risefl_interface.VecInt_insert(self, *args)

    def reserve(self, n):
        return _risefl_interface.VecInt_reserve(self, n)

    def capacity(self):
        return _risefl_interface.VecInt_capacity(self)
    __swig_destroy__ = _risefl_interface.delete_VecInt

# Register VecInt in _risefl_interface:
_risefl_interface.VecInt_swigregister(VecInt)

class VecVecFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _risefl_interface.VecVecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _risefl_interface.VecVecFloat___nonzero__(self)

    def __bool__(self):
        return _risefl_interface.VecVecFloat___bool__(self)

    def __len__(self):
        return _risefl_interface.VecVecFloat___len__(self)

    def __getslice__(self, i, j):
        return _risefl_interface.VecVecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _risefl_interface.VecVecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _risefl_interface.VecVecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _risefl_interface.VecVecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _risefl_interface.VecVecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _risefl_interface.VecVecFloat___setitem__(self, *args)

    def pop(self):
        return _risefl_interface.VecVecFloat_pop(self)

    def append(self, x):
        return _risefl_interface.VecVecFloat_append(self, x)

    def empty(self):
        return _risefl_interface.VecVecFloat_empty(self)

    def size(self):
        return _risefl_interface.VecVecFloat_size(self)

    def swap(self, v):
        return _risefl_interface.VecVecFloat_swap(self, v)

    def begin(self):
        return _risefl_interface.VecVecFloat_begin(self)

    def end(self):
        return _risefl_interface.VecVecFloat_end(self)

    def rbegin(self):
        return _risefl_interface.VecVecFloat_rbegin(self)

    def rend(self):
        return _risefl_interface.VecVecFloat_rend(self)

    def clear(self):
        return _risefl_interface.VecVecFloat_clear(self)

    def get_allocator(self):
        return _risefl_interface.VecVecFloat_get_allocator(self)

    def pop_back(self):
        return _risefl_interface.VecVecFloat_pop_back(self)

    def erase(self, *args):
        return _risefl_interface.VecVecFloat_erase(self, *args)

    def __init__(self, *args):
        _risefl_interface.VecVecFloat_swiginit(self, _risefl_interface.new_VecVecFloat(*args))

    def push_back(self, x):
        return _risefl_interface.VecVecFloat_push_back(self, x)

    def front(self):
        return _risefl_interface.VecVecFloat_front(self)

    def back(self):
        return _risefl_interface.VecVecFloat_back(self)

    def assign(self, n, x):
        return _risefl_interface.VecVecFloat_assign(self, n, x)

    def resize(self, *args):
        return _risefl_interface.VecVecFloat_resize(self, *args)

    def insert(self, *args):
        return _risefl_interface.VecVecFloat_insert(self, *args)

    def reserve(self, n):
        return _risefl_interface.VecVecFloat_reserve(self, n)

    def capacity(self):
        return _risefl_interface.VecVecFloat_capacity(self)
    __swig_destroy__ = _risefl_interface.delete_VecVecFloat

# Register VecVecFloat in _risefl_interface:
_risefl_interface.VecVecFloat_swigregister(VecVecFloat)

class RistElemHasher(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, h):
        return _risefl_interface.RistElemHasher___call__(self, h)

    def __init__(self):
        _risefl_interface.RistElemHasher_swiginit(self, _risefl_interface.new_RistElemHasher())
    __swig_destroy__ = _risefl_interface.delete_RistElemHasher

# Register RistElemHasher in _risefl_interface:
_risefl_interface.RistElemHasher_swigregister(RistElemHasher)

class ServerInterface(CommonInterface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    flags_collection = property(_risefl_interface.ServerInterface_flags_collection_get, _risefl_interface.ServerInterface_flags_collection_set)
    committed_updates_collection = property(_risefl_interface.ServerInterface_committed_updates_collection_get, _risefl_interface.ServerInterface_committed_updates_collection_set)
    encrypted_shamir_shares_collection = property(_risefl_interface.ServerInterface_encrypted_shamir_shares_collection_get, _risefl_interface.ServerInterface_encrypted_shamir_shares_collection_set)
    proof_collection = property(_risefl_interface.ServerInterface_proof_collection_get, _risefl_interface.ServerInterface_proof_collection_set)
    bb = property(_risefl_interface.ServerInterface_bb_get, _risefl_interface.ServerInterface_bb_set)
    bb_bias = property(_risefl_interface.ServerInterface_bb_bias_get, _risefl_interface.ServerInterface_bb_bias_set)
    aa_bb = property(_risefl_interface.ServerInterface_aa_bb_get, _risefl_interface.ServerInterface_aa_bb_set)
    dispute_table = property(_risefl_interface.ServerInterface_dispute_table_get, _risefl_interface.ServerInterface_dispute_table_set)
    dispute_shares_collection = property(_risefl_interface.ServerInterface_dispute_shares_collection_get, _risefl_interface.ServerInterface_dispute_shares_collection_set)
    aggregates_collection = property(_risefl_interface.ServerInterface_aggregates_collection_get, _risefl_interface.ServerInterface_aggregates_collection_set)
    small_mult_base_table_bit_size = property(_risefl_interface.ServerInterface_small_mult_base_table_bit_size_get, _risefl_interface.ServerInterface_small_mult_base_table_bit_size_set)
    small_mult_base_table = property(_risefl_interface.ServerInterface_small_mult_base_table_get, _risefl_interface.ServerInterface_small_mult_base_table_set)
    final_update_int = property(_risefl_interface.ServerInterface_final_update_int_get, _risefl_interface.ServerInterface_final_update_int_set)
    final_update_float = property(_risefl_interface.ServerInterface_final_update_float_get, _risefl_interface.ServerInterface_final_update_float_set)
    final_update_float_avg = property(_risefl_interface.ServerInterface_final_update_float_avg_get, _risefl_interface.ServerInterface_final_update_float_avg_set)
    updates_int_collection = property(_risefl_interface.ServerInterface_updates_int_collection_get, _risefl_interface.ServerInterface_updates_int_collection_set)
    updates_float_collection = property(_risefl_interface.ServerInterface_updates_float_collection_get, _risefl_interface.ServerInterface_updates_float_collection_set)
    float_l2_sq_multiplier = property(_risefl_interface.ServerInterface_float_l2_sq_multiplier_get, _risefl_interface.ServerInterface_float_l2_sq_multiplier_set)
    check_param_float = property(_risefl_interface.ServerInterface_check_param_float_get, _risefl_interface.ServerInterface_check_param_float_set)

    def __init__(self, *args):
        _risefl_interface.ServerInterface_swiginit(self, _risefl_interface.new_ServerInterface(*args))

    def import_small_mult_base_table(self, small_table):
        return _risefl_interface.ServerInterface_import_small_mult_base_table(self, small_table)

    def generate_small_mult_base_table(self):
        return _risefl_interface.ServerInterface_generate_small_mult_base_table(self)

    def reset_dispute_table(self):
        return _risefl_interface.ServerInterface_reset_dispute_table(self)

    def import_committed_updates(self, pp, i):
        return _risefl_interface.ServerInterface_import_committed_updates(self, pp, i)

    def generate_aa_seed(self):
        return _risefl_interface.ServerInterface_generate_aa_seed(self)

    def generate_hh_comb_and_bb_and_aabb(self):
        return _risefl_interface.ServerInterface_generate_hh_comb_and_bb_and_aabb(self)

    def generate_dispute_table(self):
        return _risefl_interface.ServerInterface_generate_dispute_table(self)

    def check_linear_comb_batch_commitments_with_bb(self, i):
        return _risefl_interface.ServerInterface_check_linear_comb_batch_commitments_with_bb(self, i)

    def check_sq_bound_proof(self, i):
        return _risefl_interface.ServerInterface_check_sq_bound_proof(self, i)

    def check_proof(self, i):
        return _risefl_interface.ServerInterface_check_proof(self, i)

    def check_proofs(self):
        return _risefl_interface.ServerInterface_check_proofs(self)

    def check_disputes(self):
        return _risefl_interface.ServerInterface_check_disputes(self)

    def compute_final_update(self, parallel_on_clients=False):
        return _risefl_interface.ServerInterface_compute_final_update(self, parallel_on_clients)

    def initialize_from_seed(self, seed):
        return _risefl_interface.ServerInterface_initialize_from_seed(self, seed)

    def initialize_new_iteration(self, check_param_float):
        return _risefl_interface.ServerInterface_initialize_new_iteration(self, check_param_float)

    def receive_1_bytes(self, bytes, i):
        return _risefl_interface.ServerInterface_receive_1_bytes(self, bytes, i)

    def receive_1(self, bytes_str, i):
        return _risefl_interface.ServerInterface_receive_1(self, bytes_str, i)

    def send_2_bytes(self):
        return _risefl_interface.ServerInterface_send_2_bytes(self)

    def send_2(self):
        return _risefl_interface.ServerInterface_send_2(self)

    def receive_2_bytes(self, bytes, i):
        return _risefl_interface.ServerInterface_receive_2_bytes(self, bytes, i)

    def receive_2(self, bytes_str, i):
        return _risefl_interface.ServerInterface_receive_2(self, bytes_str, i)

    def concurrent_process_before_send_3(self):
        return _risefl_interface.ServerInterface_concurrent_process_before_send_3(self)

    def send_3_bytes(self, i):
        return _risefl_interface.ServerInterface_send_3_bytes(self, i)

    def send_3(self, i):
        return _risefl_interface.ServerInterface_send_3(self, i)

    def receive_3_bytes(self, bytes, i):
        return _risefl_interface.ServerInterface_receive_3_bytes(self, bytes, i)

    def receive_3(self, bytes_str, i):
        return _risefl_interface.ServerInterface_receive_3(self, bytes_str, i)

    def process_before_send_4(self):
        return _risefl_interface.ServerInterface_process_before_send_4(self)

    def send_4_bytes(self, i):
        return _risefl_interface.ServerInterface_send_4_bytes(self, i)

    def send_4(self, i):
        return _risefl_interface.ServerInterface_send_4(self, i)

    def receive_4_bytes(self, bytes, i):
        return _risefl_interface.ServerInterface_receive_4_bytes(self, bytes, i)

    def receive_4(self, bytes_str, i):
        return _risefl_interface.ServerInterface_receive_4(self, bytes_str, i)

    def process_before_send_5(self):
        return _risefl_interface.ServerInterface_process_before_send_5(self)

    def send_5_bytes(self, i):
        return _risefl_interface.ServerInterface_send_5_bytes(self, i)

    def send_5(self, i):
        return _risefl_interface.ServerInterface_send_5(self, i)

    def receive_5_bytes(self, bytes, i):
        return _risefl_interface.ServerInterface_receive_5_bytes(self, bytes, i)

    def receive_5(self, bytes_str, i):
        return _risefl_interface.ServerInterface_receive_5(self, bytes_str, i)

    def finish_iteration(self, parallel_on_clients=False):
        return _risefl_interface.ServerInterface_finish_iteration(self, parallel_on_clients)

    def string_api_test(self, a):
        return _risefl_interface.ServerInterface_string_api_test(self, a)
    __swig_destroy__ = _risefl_interface.delete_ServerInterface

# Register ServerInterface in _risefl_interface:
_risefl_interface.ServerInterface_swigregister(ServerInterface)
MAX_MULT_BASE_TABLE_BIT_SIZE = cvar.MAX_MULT_BASE_TABLE_BIT_SIZE


def discrete_log(y, small_table, per_side_step_count):
    return _risefl_interface.discrete_log(y, small_table, per_side_step_count)
class SignPubKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    key = property(_risefl_interface.SignPubKey_key_get, _risefl_interface.SignPubKey_key_set)

    def __init__(self):
        _risefl_interface.SignPubKey_swiginit(self, _risefl_interface.new_SignPubKey())
    __swig_destroy__ = _risefl_interface.delete_SignPubKey

# Register SignPubKey in _risefl_interface:
_risefl_interface.SignPubKey_swigregister(SignPubKey)
SIGNPUBKEYBYTES = cvar.SIGNPUBKEYBYTES
SIGNPRVKEYBYTES = cvar.SIGNPRVKEYBYTES
SIGNBYTES = cvar.SIGNBYTES

class SignPrvKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    key = property(_risefl_interface.SignPrvKey_key_get, _risefl_interface.SignPrvKey_key_set)

    def __init__(self):
        _risefl_interface.SignPrvKey_swiginit(self, _risefl_interface.new_SignPrvKey())
    __swig_destroy__ = _risefl_interface.delete_SignPrvKey

# Register SignPrvKey in _risefl_interface:
_risefl_interface.SignPrvKey_swigregister(SignPrvKey)


def gen_sign_key_pair():
    return _risefl_interface.gen_sign_key_pair()

def sign(mes, prv):
    return _risefl_interface.sign(mes, prv)

def sign_open(signed_mes, pub):
    return _risefl_interface.sign_open(signed_mes, pub)
class PairSignKeys(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _risefl_interface.PairSignKeys_swiginit(self, _risefl_interface.new_PairSignKeys(*args))
    first = property(_risefl_interface.PairSignKeys_first_get, _risefl_interface.PairSignKeys_first_set)
    second = property(_risefl_interface.PairSignKeys_second_get, _risefl_interface.PairSignKeys_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _risefl_interface.delete_PairSignKeys

# Register PairSignKeys in _risefl_interface:
_risefl_interface.PairSignKeys_swigregister(PairSignKeys)

class VecSignPubKeys(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _risefl_interface.VecSignPubKeys_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _risefl_interface.VecSignPubKeys___nonzero__(self)

    def __bool__(self):
        return _risefl_interface.VecSignPubKeys___bool__(self)

    def __len__(self):
        return _risefl_interface.VecSignPubKeys___len__(self)

    def __getslice__(self, i, j):
        return _risefl_interface.VecSignPubKeys___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _risefl_interface.VecSignPubKeys___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _risefl_interface.VecSignPubKeys___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _risefl_interface.VecSignPubKeys___delitem__(self, *args)

    def __getitem__(self, *args):
        return _risefl_interface.VecSignPubKeys___getitem__(self, *args)

    def __setitem__(self, *args):
        return _risefl_interface.VecSignPubKeys___setitem__(self, *args)

    def pop(self):
        return _risefl_interface.VecSignPubKeys_pop(self)

    def append(self, x):
        return _risefl_interface.VecSignPubKeys_append(self, x)

    def empty(self):
        return _risefl_interface.VecSignPubKeys_empty(self)

    def size(self):
        return _risefl_interface.VecSignPubKeys_size(self)

    def swap(self, v):
        return _risefl_interface.VecSignPubKeys_swap(self, v)

    def begin(self):
        return _risefl_interface.VecSignPubKeys_begin(self)

    def end(self):
        return _risefl_interface.VecSignPubKeys_end(self)

    def rbegin(self):
        return _risefl_interface.VecSignPubKeys_rbegin(self)

    def rend(self):
        return _risefl_interface.VecSignPubKeys_rend(self)

    def clear(self):
        return _risefl_interface.VecSignPubKeys_clear(self)

    def get_allocator(self):
        return _risefl_interface.VecSignPubKeys_get_allocator(self)

    def pop_back(self):
        return _risefl_interface.VecSignPubKeys_pop_back(self)

    def erase(self, *args):
        return _risefl_interface.VecSignPubKeys_erase(self, *args)

    def __init__(self, *args):
        _risefl_interface.VecSignPubKeys_swiginit(self, _risefl_interface.new_VecSignPubKeys(*args))

    def push_back(self, x):
        return _risefl_interface.VecSignPubKeys_push_back(self, x)

    def front(self):
        return _risefl_interface.VecSignPubKeys_front(self)

    def back(self):
        return _risefl_interface.VecSignPubKeys_back(self)

    def assign(self, n, x):
        return _risefl_interface.VecSignPubKeys_assign(self, n, x)

    def resize(self, *args):
        return _risefl_interface.VecSignPubKeys_resize(self, *args)

    def insert(self, *args):
        return _risefl_interface.VecSignPubKeys_insert(self, *args)

    def reserve(self, n):
        return _risefl_interface.VecSignPubKeys_reserve(self, n)

    def capacity(self):
        return _risefl_interface.VecSignPubKeys_capacity(self)
    __swig_destroy__ = _risefl_interface.delete_VecSignPubKeys

# Register VecSignPubKeys in _risefl_interface:
_risefl_interface.VecSignPubKeys_swigregister(VecSignPubKeys)

class VecSignPrvKeys(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _risefl_interface.VecSignPrvKeys_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _risefl_interface.VecSignPrvKeys___nonzero__(self)

    def __bool__(self):
        return _risefl_interface.VecSignPrvKeys___bool__(self)

    def __len__(self):
        return _risefl_interface.VecSignPrvKeys___len__(self)

    def __getslice__(self, i, j):
        return _risefl_interface.VecSignPrvKeys___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _risefl_interface.VecSignPrvKeys___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _risefl_interface.VecSignPrvKeys___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _risefl_interface.VecSignPrvKeys___delitem__(self, *args)

    def __getitem__(self, *args):
        return _risefl_interface.VecSignPrvKeys___getitem__(self, *args)

    def __setitem__(self, *args):
        return _risefl_interface.VecSignPrvKeys___setitem__(self, *args)

    def pop(self):
        return _risefl_interface.VecSignPrvKeys_pop(self)

    def append(self, x):
        return _risefl_interface.VecSignPrvKeys_append(self, x)

    def empty(self):
        return _risefl_interface.VecSignPrvKeys_empty(self)

    def size(self):
        return _risefl_interface.VecSignPrvKeys_size(self)

    def swap(self, v):
        return _risefl_interface.VecSignPrvKeys_swap(self, v)

    def begin(self):
        return _risefl_interface.VecSignPrvKeys_begin(self)

    def end(self):
        return _risefl_interface.VecSignPrvKeys_end(self)

    def rbegin(self):
        return _risefl_interface.VecSignPrvKeys_rbegin(self)

    def rend(self):
        return _risefl_interface.VecSignPrvKeys_rend(self)

    def clear(self):
        return _risefl_interface.VecSignPrvKeys_clear(self)

    def get_allocator(self):
        return _risefl_interface.VecSignPrvKeys_get_allocator(self)

    def pop_back(self):
        return _risefl_interface.VecSignPrvKeys_pop_back(self)

    def erase(self, *args):
        return _risefl_interface.VecSignPrvKeys_erase(self, *args)

    def __init__(self, *args):
        _risefl_interface.VecSignPrvKeys_swiginit(self, _risefl_interface.new_VecSignPrvKeys(*args))

    def push_back(self, x):
        return _risefl_interface.VecSignPrvKeys_push_back(self, x)

    def front(self):
        return _risefl_interface.VecSignPrvKeys_front(self)

    def back(self):
        return _risefl_interface.VecSignPrvKeys_back(self)

    def assign(self, n, x):
        return _risefl_interface.VecSignPrvKeys_assign(self, n, x)

    def resize(self, *args):
        return _risefl_interface.VecSignPrvKeys_resize(self, *args)

    def insert(self, *args):
        return _risefl_interface.VecSignPrvKeys_insert(self, *args)

    def reserve(self, n):
        return _risefl_interface.VecSignPrvKeys_reserve(self, n)

    def capacity(self):
        return _risefl_interface.VecSignPrvKeys_capacity(self)
    __swig_destroy__ = _risefl_interface.delete_VecSignPrvKeys

# Register VecSignPrvKeys in _risefl_interface:
_risefl_interface.VecSignPrvKeys_swigregister(VecSignPrvKeys)



